/*--------------------------------------------
  This file has been generated by cigen       
  using the following command :               

  $CIBIN/cigen.exe -p -h X11/Xlib.h -h X11/Xresource.h -f X11/Intrinsic.h -n CiBindIntrinsic -o ../gen/Intrins_B.c

--------------------------------------------*/

#include <X11/Xlib.h>
#include <X11/Xresource.h>
#include <X11/Intrinsic.h>

#ifndef __CI_SWITCH_DEFS__
#define __CI_SWITCH_DEFS__

#ifdef __cplusplus
#define SWITCH_ELLIPSIS ...
#else
#define SWITCH_ELLIPSIS 

#endif

#ifndef __CiDefs__

typedef void            (*CiRoutine)(SWITCH_ELLIPSIS);
typedef char            (*CiCRoutine)(SWITCH_ELLIPSIS);
typedef short           (*CiSRoutine)(SWITCH_ELLIPSIS);
typedef int             (*CiIRoutine)(SWITCH_ELLIPSIS);
typedef long            (*CiLRoutine)(SWITCH_ELLIPSIS);
typedef unsigned char   (*CiUCRoutine)(SWITCH_ELLIPSIS);
typedef unsigned short  (*CiUSRoutine)(SWITCH_ELLIPSIS);
typedef unsigned int    (*CiUIRoutine)(SWITCH_ELLIPSIS);
typedef unsigned long   (*CiULRoutine)(SWITCH_ELLIPSIS);
typedef float           (*CiFRoutine)(SWITCH_ELLIPSIS);
typedef double          (*CiDRoutine)(SWITCH_ELLIPSIS);
typedef void*           (*CiPRoutine)(SWITCH_ELLIPSIS);

#endif

#ifndef __CiType__

typedef union {
  char c;
  short s;
  int i;
  long l;
  char* p;
  float f;
  double d;
} CiPrimValueRec, *CiPrimValue;

#endif

#endif

#ifdef __cplusplus
extern "C" {
#endif

CiRoutine CiBindIntrinsic (char* library);

static void CiBindIntrinsicInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew);

static char* CiBindIntrinsicSetupFunction (CiRoutine* switchFunction);

static void CiBindIntrinsicSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue);
void CiBindIntrinsicCleanup ();

static CiRoutine CiBindIntrinsicFileCompile       = 0;
static CiRoutine CiBindIntrinsicFunctionBind      = 0;
static CiRoutine CiBindIntrinsicVariableBind      = 0;
static CiRoutine CiBindIntrinsicFunctionSwitchNew = 0;

#ifdef __cplusplus
}
#endif

/*- Procedure ------------------------------------------*/
CiRoutine CiBindIntrinsic (char* library)
/*------------------------------------------------------*/
{
  static int first = 1;

  if (first)
    {
      first = 0;
    }
  else if (CiBindIntrinsicFunctionSwitchNew)
    {
      CiBindIntrinsicFunctionSwitchNew ((CiRoutine) CiBindIntrinsicSetupFunction);
    }

  library = 0;

  return ((CiRoutine) CiBindIntrinsicInitFunction);
}

/*- Procedure ------------------------------------------*/
static void CiBindIntrinsicInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew)
/*------------------------------------------------------*/
{
  CiBindIntrinsicFileCompile       = compileFunction;
  pathFunction = 0;
  CiBindIntrinsicFunctionBind      = bindFunction;
  CiBindIntrinsicVariableBind      = bindVariable;
  CiBindIntrinsicFunctionSwitchNew = switchNew;
  CiBindIntrinsicVariableBind (0, 0);
  CiBindIntrinsicFunctionBind (0, 0);
}

/*- Procedure ------------------------------------------*/
static char* CiBindIntrinsicSetupFunction (CiRoutine* switchFunction)
/*------------------------------------------------------*/
{
  static char cases[] = {
    1, 6, 4, 0,
    1, 6, 6, 0,
    5, 6, 0,
    2, 6, 6, 0,
    6, 6, 0,
    1, 6, 6, 6, 6, 0,
    1, 6, 6, 4, 0,
    1, 6, 6, 6, 0,
    1, 6, 0,
    0
  };
  static int first = 1;
  
  if (first)
    {
      first = 0;
  
      CiBindIntrinsicFileCompile ("X11/Xlib.h");
      CiBindIntrinsicFileCompile ("X11/Xresource.h");
      CiBindIntrinsicFileCompile ("X11/Intrinsic.h");
      CiBindIntrinsicFunctionBind ("XtDisplay", (CiRoutine) XtDisplay);
      CiBindIntrinsicFunctionBind ("XtCallCallbacks", (CiRoutine) XtCallCallbacks);
      CiBindIntrinsicFunctionBind ("XtInstallAllAccelerators", (CiRoutine) XtInstallAllAccelerators);
      CiBindIntrinsicFunctionBind ("XtInstallAccelerators", (CiRoutine) XtInstallAccelerators);
      CiBindIntrinsicFunctionBind ("XtClass", (CiRoutine) XtClass);
      CiBindIntrinsicFunctionBind ("XtParent", (CiRoutine) XtParent);
      CiBindIntrinsicFunctionBind ("XtManageChild", (CiRoutine) XtManageChild);
      CiBindIntrinsicFunctionBind ("XtName", (CiRoutine) XtName);
      CiBindIntrinsicFunctionBind ("XtGetValues", (CiRoutine) XtGetValues);
      CiBindIntrinsicFunctionBind ("XtRealizeWidget", (CiRoutine) XtRealizeWidget);
      CiBindIntrinsicFunctionBind ("XtWindow", (CiRoutine) XtWindow);
      CiBindIntrinsicFunctionBind ("XtManageChildren", (CiRoutine) XtManageChildren);
      CiBindIntrinsicFunctionBind ("XtSetValues", (CiRoutine) XtSetValues);
      CiBindIntrinsicFunctionBind ("XtFree", (CiRoutine) XtFree);
      CiBindIntrinsicFunctionBind ("XtUnrealizeWidget", (CiRoutine) XtUnrealizeWidget);
      CiBindIntrinsicFunctionBind ("XtUnmanageChild", (CiRoutine) XtUnmanageChild);
      CiBindIntrinsicFunctionBind ("XtIsSubclass", (CiRoutine) XtIsSubclass);
      CiBindIntrinsicFunctionBind ("XtUnmanageChildren", (CiRoutine) XtUnmanageChildren);
      CiBindIntrinsicFunctionBind ("XtGetConstraintResourceList", (CiRoutine) XtGetConstraintResourceList);
      CiBindIntrinsicFunctionBind ("XtGetResourceList", (CiRoutine) XtGetResourceList);
    }
  *switchFunction = (CiRoutine) CiBindIntrinsicSwitchFunction;
  return ((char*) cases);
}

/*- Procedure ------------------------------------------*/
static void CiBindIntrinsicSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue)
/*------------------------------------------------------*/
{
  CiPrimValueRec prim;
  
  prim.l = 0;
  
  switch (code)
  {
    case 2 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].i);
          }
          break;
      }
      break;
    case 4 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p);
          }
          break;
      }
      break;
    case 9 :
      switch (position)
      {
        case 1 :
          {
            CiLRoutine g = (CiLRoutine) f;

            prim.l = g (args[0].p);
          }
          break;
      }
      break;
    case 13 :
      switch (position)
      {
        case 1 :
          {
            CiCRoutine g = (CiCRoutine) f;

            prim.c = g (args[0].p, args[1].p);
          }
          break;
      }
      break;
    case 22 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p);
          }
          break;
      }
      break;
    case 26 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p, args[2].p, args[3].p);
          }
          break;
      }
      break;
    case 33 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p, args[2].i);
          }
          break;
      }
      break;
    case 35 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p, args[2].p);
          }
          break;
      }
      break;
    case 37 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p);
          }
          break;
      }
      break;
  }
  
  args = 0;
  position = 0;
  
  if (retValue) *retValue = prim;
}

/*--------------------------------------------
  This file has been generated by cigen       
  using the following command :               

  $CIBIN/cigen.exe -p -h X11/Intrinsic.h -f X11/Shell.h -n CiBindShell -o ../gen/Shell_B.c

--------------------------------------------*/

#include <X11/Intrinsic.h>
#include <X11/Shell.h>

#ifndef __CI_SWITCH_DEFS__
#define __CI_SWITCH_DEFS__

#ifdef __cplusplus
#define SWITCH_ELLIPSIS ...
#else
#define SWITCH_ELLIPSIS 

#endif

#ifndef __CiDefs__

typedef void            (*CiRoutine)(SWITCH_ELLIPSIS);
typedef char            (*CiCRoutine)(SWITCH_ELLIPSIS);
typedef short           (*CiSRoutine)(SWITCH_ELLIPSIS);
typedef int             (*CiIRoutine)(SWITCH_ELLIPSIS);
typedef long            (*CiLRoutine)(SWITCH_ELLIPSIS);
typedef unsigned char   (*CiUCRoutine)(SWITCH_ELLIPSIS);
typedef unsigned short  (*CiUSRoutine)(SWITCH_ELLIPSIS);
typedef unsigned int    (*CiUIRoutine)(SWITCH_ELLIPSIS);
typedef unsigned long   (*CiULRoutine)(SWITCH_ELLIPSIS);
typedef float           (*CiFRoutine)(SWITCH_ELLIPSIS);
typedef double          (*CiDRoutine)(SWITCH_ELLIPSIS);
typedef void*           (*CiPRoutine)(SWITCH_ELLIPSIS);

#endif

#ifndef __CiType__

typedef union {
  char c;
  short s;
  int i;
  long l;
  char* p;
  float f;
  double d;
} CiPrimValueRec, *CiPrimValue;

#endif

#endif

#ifdef __cplusplus
extern "C" {
#endif

CiRoutine CiBindShell (char* library);

static void CiBindShellInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew);

static char* CiBindShellSetupFunction (CiRoutine* switchFunction);

static void CiBindShellSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue);
void CiBindShellCleanup ();

static CiRoutine CiBindShellFileCompile       = 0;
static CiRoutine CiBindShellFunctionBind      = 0;
static CiRoutine CiBindShellVariableBind      = 0;
static CiRoutine CiBindShellFunctionSwitchNew = 0;

#ifdef __cplusplus
}
#endif

/*- Procedure ------------------------------------------*/
CiRoutine CiBindShell (char* library)
/*------------------------------------------------------*/
{
  static int first = 1;

  if (first)
    {
      first = 0;
    }
  else if (CiBindShellFunctionSwitchNew)
    {
      CiBindShellFunctionSwitchNew ((CiRoutine) CiBindShellSetupFunction);
    }

  library = 0;

  return ((CiRoutine) CiBindShellInitFunction);
}

/*- Procedure ------------------------------------------*/
static void CiBindShellInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew)
/*------------------------------------------------------*/
{
  CiBindShellFileCompile       = compileFunction;
  pathFunction = 0;
  CiBindShellFunctionBind      = bindFunction;
  CiBindShellVariableBind      = bindVariable;
  CiBindShellFunctionSwitchNew = switchNew;
  CiBindShellVariableBind (0, 0);
  CiBindShellFunctionBind (0, 0);
}

/*- Procedure ------------------------------------------*/
static char* CiBindShellSetupFunction (CiRoutine* switchFunction)
/*------------------------------------------------------*/
{
  static char cases[] = {
    0
  };
  static int first = 1;
  
  if (first)
    {
      first = 0;
  
      CiBindShellFileCompile ("X11/Intrinsic.h");
      CiBindShellFileCompile ("X11/Shell.h");
      CiBindShellVariableBind ("widgetClass", &widgetClass);
      CiBindShellVariableBind ("coreWidgetClass", &coreWidgetClass);
      CiBindShellVariableBind ("overrideShellWidgetClass", &overrideShellWidgetClass);
      CiBindShellVariableBind ("compositeWidgetClass", &compositeWidgetClass);
      CiBindShellVariableBind ("applicationShellWidgetClass", &applicationShellWidgetClass);
      CiBindShellVariableBind ("wmShellWidgetClass", &wmShellWidgetClass);
      CiBindShellVariableBind ("rectObjClass", &rectObjClass);
      CiBindShellVariableBind ("transientShellWidgetClass", &transientShellWidgetClass);
      CiBindShellVariableBind ("objectClass", &objectClass);
      CiBindShellVariableBind ("topLevelShellWidgetClass", &topLevelShellWidgetClass);
      CiBindShellVariableBind ("shellWidgetClass", &shellWidgetClass);
      CiBindShellVariableBind ("constraintWidgetClass", &constraintWidgetClass);
    }
  *switchFunction = (CiRoutine) CiBindShellSwitchFunction;
  return ((char*) cases);
}

/*- Procedure ------------------------------------------*/
static void CiBindShellSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue)
/*------------------------------------------------------*/
{
  CiPrimValueRec prim;
  
  prim.l = 0;
  
  f = 0;
  code = 0;
  
  args = 0;
  position = 0;
  
  if (retValue) *retValue = prim;
}

/*--------------------------------------------
  This file has been generated by cigen       
  using the following command :               

  $CIBIN/cigen.exe -p -h X11/Intrinsic.h -f X11/Vendor.h -n CiBindVendor -o ../gen/Vendor_B.c

--------------------------------------------*/

#include <X11/Intrinsic.h>
#include <X11/Vendor.h>

#ifndef __CI_SWITCH_DEFS__
#define __CI_SWITCH_DEFS__

#ifdef __cplusplus
#define SWITCH_ELLIPSIS ...
#else
#define SWITCH_ELLIPSIS 

#endif

#ifndef __CiDefs__

typedef void            (*CiRoutine)(SWITCH_ELLIPSIS);
typedef char            (*CiCRoutine)(SWITCH_ELLIPSIS);
typedef short           (*CiSRoutine)(SWITCH_ELLIPSIS);
typedef int             (*CiIRoutine)(SWITCH_ELLIPSIS);
typedef long            (*CiLRoutine)(SWITCH_ELLIPSIS);
typedef unsigned char   (*CiUCRoutine)(SWITCH_ELLIPSIS);
typedef unsigned short  (*CiUSRoutine)(SWITCH_ELLIPSIS);
typedef unsigned int    (*CiUIRoutine)(SWITCH_ELLIPSIS);
typedef unsigned long   (*CiULRoutine)(SWITCH_ELLIPSIS);
typedef float           (*CiFRoutine)(SWITCH_ELLIPSIS);
typedef double          (*CiDRoutine)(SWITCH_ELLIPSIS);
typedef void*           (*CiPRoutine)(SWITCH_ELLIPSIS);

#endif

#ifndef __CiType__

typedef union {
  char c;
  short s;
  int i;
  long l;
  char* p;
  float f;
  double d;
} CiPrimValueRec, *CiPrimValue;

#endif

#endif

#ifdef __cplusplus
extern "C" {
#endif

CiRoutine CiBindVendor (char* library);

static void CiBindVendorInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew);

static char* CiBindVendorSetupFunction (CiRoutine* switchFunction);

static void CiBindVendorSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue);
void CiBindVendorCleanup ();

static CiRoutine CiBindVendorFileCompile       = 0;
static CiRoutine CiBindVendorFunctionBind      = 0;
static CiRoutine CiBindVendorVariableBind      = 0;
static CiRoutine CiBindVendorFunctionSwitchNew = 0;

#ifdef __cplusplus
}
#endif

/*- Procedure ------------------------------------------*/
CiRoutine CiBindVendor (char* library)
/*------------------------------------------------------*/
{
  static int first = 1;

  if (first)
    {
      first = 0;
    }
  else if (CiBindVendorFunctionSwitchNew)
    {
      CiBindVendorFunctionSwitchNew ((CiRoutine) CiBindVendorSetupFunction);
    }

  library = 0;

  return ((CiRoutine) CiBindVendorInitFunction);
}

/*- Procedure ------------------------------------------*/
static void CiBindVendorInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew)
/*------------------------------------------------------*/
{
  CiBindVendorFileCompile       = compileFunction;
  pathFunction = 0;
  CiBindVendorFunctionBind      = bindFunction;
  CiBindVendorVariableBind      = bindVariable;
  CiBindVendorFunctionSwitchNew = switchNew;
  CiBindVendorVariableBind (0, 0);
  CiBindVendorFunctionBind (0, 0);
}

/*- Procedure ------------------------------------------*/
static char* CiBindVendorSetupFunction (CiRoutine* switchFunction)
/*------------------------------------------------------*/
{
  static char cases[] = {
    0
  };
  static int first = 1;
  
  if (first)
    {
      first = 0;
  
      CiBindVendorFileCompile ("X11/Intrinsic.h");
      CiBindVendorFileCompile ("X11/Vendor.h");
      CiBindVendorVariableBind ("vendorShellWidgetClass", &vendorShellWidgetClass);
    }
  *switchFunction = (CiRoutine) CiBindVendorSwitchFunction;
  return ((char*) cases);
}

/*- Procedure ------------------------------------------*/
static void CiBindVendorSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue)
/*------------------------------------------------------*/
{
  CiPrimValueRec prim;
  
  prim.l = 0;
  
  f = 0;
  code = 0;
  
  args = 0;
  position = 0;
  
  if (retValue) *retValue = prim;
}

/*--------------------------------------------
  This file has been generated by cigen       
  using the following command :               

  $CIBIN/cigen.exe -p -f X11/Xlib.h -n CiBindXlib -o ../gen/Xlib_B.c

--------------------------------------------*/

#include <X11/Xlib.h>

#ifndef __CI_SWITCH_DEFS__
#define __CI_SWITCH_DEFS__

#ifdef __cplusplus
#define SWITCH_ELLIPSIS ...
#else
#define SWITCH_ELLIPSIS 

#endif

#ifndef __CiDefs__

typedef void            (*CiRoutine)(SWITCH_ELLIPSIS);
typedef char            (*CiCRoutine)(SWITCH_ELLIPSIS);
typedef short           (*CiSRoutine)(SWITCH_ELLIPSIS);
typedef int             (*CiIRoutine)(SWITCH_ELLIPSIS);
typedef long            (*CiLRoutine)(SWITCH_ELLIPSIS);
typedef unsigned char   (*CiUCRoutine)(SWITCH_ELLIPSIS);
typedef unsigned short  (*CiUSRoutine)(SWITCH_ELLIPSIS);
typedef unsigned int    (*CiUIRoutine)(SWITCH_ELLIPSIS);
typedef unsigned long   (*CiULRoutine)(SWITCH_ELLIPSIS);
typedef float           (*CiFRoutine)(SWITCH_ELLIPSIS);
typedef double          (*CiDRoutine)(SWITCH_ELLIPSIS);
typedef void*           (*CiPRoutine)(SWITCH_ELLIPSIS);

#endif

#ifndef __CiType__

typedef union {
  char c;
  short s;
  int i;
  long l;
  char* p;
  float f;
  double d;
} CiPrimValueRec, *CiPrimValue;

#endif

#endif

#ifdef __cplusplus
extern "C" {
#endif

CiRoutine CiBindXlib (char* library);

static void CiBindXlibInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew);

static char* CiBindXlibSetupFunction (CiRoutine* switchFunction);

static void CiBindXlibSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue);
void CiBindXlibCleanup ();

static CiRoutine CiBindXlibFileCompile       = 0;
static CiRoutine CiBindXlibFunctionBind      = 0;
static CiRoutine CiBindXlibVariableBind      = 0;
static CiRoutine CiBindXlibFunctionSwitchNew = 0;

#ifdef __cplusplus
}
#endif

/*- Procedure ------------------------------------------*/
CiRoutine CiBindXlib (char* library)
/*------------------------------------------------------*/
{
  static int first = 1;

  if (first)
    {
      first = 0;
    }
  else if (CiBindXlibFunctionSwitchNew)
    {
      CiBindXlibFunctionSwitchNew ((CiRoutine) CiBindXlibSetupFunction);
    }

  library = 0;

  return ((CiRoutine) CiBindXlibInitFunction);
}

/*- Procedure ------------------------------------------*/
static void CiBindXlibInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew)
/*------------------------------------------------------*/
{
  CiBindXlibFileCompile       = compileFunction;
  pathFunction = 0;
  CiBindXlibFunctionBind      = bindFunction;
  CiBindXlibVariableBind      = bindVariable;
  CiBindXlibFunctionSwitchNew = switchNew;
  CiBindXlibVariableBind (0, 0);
  CiBindXlibFunctionBind (0, 0);
}

/*- Procedure ------------------------------------------*/
static char* CiBindXlibSetupFunction (CiRoutine* switchFunction)
/*------------------------------------------------------*/
{
  static char cases[] = {
    6, 6, 5, 5, 6, 0,
    1, 6, 4, 0,
    1, 6, 5, 0,
    1, 6, 5, 6, 6, 4, 4, 0,
    1, 6, 5, 6, 4, 4, 6, 4, 0,
    1, 6, 6, 0,
    1, 6, 6, 4, 4, 4, 4, 0,
    5, 6, 0,
    1, 6, 5, 6, 6, 4, 4, 4, 0,
    1, 6, 6, 5, 6, 0,
    1, 6, 5, 6, 4, 4, 4, 4, 0,
    1, 6, 5, 6, 6, 4, 0,
    1, 6, 5, 5, 0,
    6, 6, 0,
    4, 6, 5, 6, 6, 6, 6, 6, 6, 6, 0,
    1, 6, 5, 6, 4, 4, 0,
    1, 6, 6, 4, 0,
    1, 6, 6, 5, 0,
    1, 6, 5, 6, 4, 4, 4, 4, 4, 4, 0,
    1, 6, 0,
    6, 6, 6, 4, 6, 0,
    0
  };
  static int first = 1;
  
  if (first)
    {
      first = 0;
  
      CiBindXlibFileCompile ("X11/Xlib.h");
      CiBindXlibFunctionBind ("XDrawString", (CiRoutine) XDrawString);
      CiBindXlibFunctionBind ("XSync", (CiRoutine) XSync);
      CiBindXlibFunctionBind ("XUndefineCursor", (CiRoutine) XUndefineCursor);
      CiBindXlibFunctionBind ("XDrawArc", (CiRoutine) XDrawArc);
      CiBindXlibFunctionBind ("XDrawLines", (CiRoutine) XDrawLines);
      CiBindXlibFunctionBind ("XDrawImageString", (CiRoutine) XDrawImageString);
      CiBindXlibFunctionBind ("XFillRectangle", (CiRoutine) XFillRectangle);
      CiBindXlibFunctionBind ("XSetFunction", (CiRoutine) XSetFunction);
      CiBindXlibFunctionBind ("XSetArcMode", (CiRoutine) XSetArcMode);
      CiBindXlibFunctionBind ("XSetLineAttributes", (CiRoutine) XSetLineAttributes);
      CiBindXlibFunctionBind ("XDefineCursor", (CiRoutine) XDefineCursor);
      CiBindXlibFunctionBind ("XDefaultScreenOfDisplay", (CiRoutine) XDefaultScreenOfDisplay);
      CiBindXlibFunctionBind ("XDrawArcs", (CiRoutine) XDrawArcs);
      CiBindXlibFunctionBind ("XFreeFontNames", (CiRoutine) XFreeFontNames);
      CiBindXlibFunctionBind ("XWhitePixelOfScreen", (CiRoutine) XWhitePixelOfScreen);
      CiBindXlibFunctionBind ("XDrawLine", (CiRoutine) XDrawLine);
      CiBindXlibFunctionBind ("XGetGeometry", (CiRoutine) XGetGeometry);
      CiBindXlibFunctionBind ("XDrawPoint", (CiRoutine) XDrawPoint);
      CiBindXlibFunctionBind ("XDefaultRootWindow", (CiRoutine) XDefaultRootWindow);
      CiBindXlibFunctionBind ("XFillPolygon", (CiRoutine) XFillPolygon);
      CiBindXlibFunctionBind ("XDrawPoints", (CiRoutine) XDrawPoints);
      CiBindXlibFunctionBind ("XClearWindow", (CiRoutine) XClearWindow);
      CiBindXlibFunctionBind ("XSetFillStyle", (CiRoutine) XSetFillStyle);
      CiBindXlibFunctionBind ("XFillRectangles", (CiRoutine) XFillRectangles);
      CiBindXlibFunctionBind ("XFreePixmap", (CiRoutine) XFreePixmap);
      CiBindXlibFunctionBind ("XFillArcs", (CiRoutine) XFillArcs);
      CiBindXlibFunctionBind ("XFreeGC", (CiRoutine) XFreeGC);
      CiBindXlibFunctionBind ("XBlackPixelOfScreen", (CiRoutine) XBlackPixelOfScreen);
      CiBindXlibFunctionBind ("XChangeGC", (CiRoutine) XChangeGC);
      CiBindXlibFunctionBind ("XDrawSegments", (CiRoutine) XDrawSegments);
      CiBindXlibFunctionBind ("XCreateGC", (CiRoutine) XCreateGC);
      CiBindXlibFunctionBind ("XFillArc", (CiRoutine) XFillArc);
      CiBindXlibFunctionBind ("XSetFillRule", (CiRoutine) XSetFillRule);
      CiBindXlibFunctionBind ("XSetForeground", (CiRoutine) XSetForeground);
      CiBindXlibFunctionBind ("XSetBackground", (CiRoutine) XSetBackground);
      CiBindXlibFunctionBind ("XDrawRectangles", (CiRoutine) XDrawRectangles);
      CiBindXlibFunctionBind ("XListFonts", (CiRoutine) XListFonts);
      CiBindXlibFunctionBind ("XDrawRectangle", (CiRoutine) XDrawRectangle);
      CiBindXlibFunctionBind ("XFlush", (CiRoutine) XFlush);
    }
  *switchFunction = (CiRoutine) CiBindXlibSwitchFunction;
  return ((char*) cases);
}

/*- Procedure ------------------------------------------*/
static void CiBindXlibSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue)
/*------------------------------------------------------*/
{
  CiPrimValueRec prim;
  
  prim.l = 0;
  
  switch (code)
  {
    case 1 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p, args[1].l, args[2].l, args[3].p);
          }
          break;
      }
      break;
    case 2 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].i);
          }
          break;
      }
      break;
    case 3 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].l);
          }
          break;
        case 2 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].l, args[2].p, args[3].p, 
               args[4].i, args[5].i);
          }
          break;
      }
      break;
    case 4 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].l, args[2].p, args[3].i, 
               args[4].i, args[5].p, args[6].i);
          }
          break;
        case 2 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p);
          }
          break;
      }
      break;
    case 8 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p, args[2].i, args[3].i, 
               args[4].i, args[5].i);
          }
          break;
      }
      break;
    case 9 :
      switch (position)
      {
        case 1 :
          {
            CiLRoutine g = (CiLRoutine) f;

            prim.l = g (args[0].p);
          }
          break;
      }
      break;
    case 12 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].l, args[2].p, args[3].p, 
               args[4].i, args[5].i, args[6].i);
          }
          break;
      }
      break;
    case 13 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p, args[2].l, args[3].p);
          }
          break;
      }
      break;
    case 18 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].l, args[2].p, args[3].i, 
               args[4].i, args[5].i, args[6].i);
          }
          break;
        case 2 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].l, args[2].p, args[3].p, 
               args[4].i);
          }
          break;
      }
      break;
    case 21 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].l, args[2].l);
          }
          break;
      }
      break;
    case 22 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p);
          }
          break;
      }
      break;
    case 23 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].l, args[2].p, args[3].p, 
                        args[4].p, args[5].p, args[6].p, args[7].p, 
                        args[8].p);
          }
          break;
      }
      break;
    case 32 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].l, args[2].p, args[3].i, 
               args[4].i);
          }
          break;
      }
      break;
    case 33 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p, args[2].i);
          }
          break;
      }
      break;
    case 34 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p, args[2].l);
          }
          break;
      }
      break;
    case 36 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].l, args[2].p, args[3].i, 
               args[4].i, args[5].i, args[6].i, args[7].i, 
               args[8].i);
          }
          break;
      }
      break;
    case 37 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p);
          }
          break;
        case 2 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p, args[1].p, args[2].i, args[3].p);
          }
          break;
      }
      break;
  }
  
  args = 0;
  position = 0;
  
  if (retValue) *retValue = prim;
}

/*--------------------------------------------
  This file has been generated by cigen       
  using the following command :               

  $CIBIN/cigen.exe -p -h X11/Xlib.h -f X11/Xresource.h -n CiBindXresource -o ../gen/Xres_B.c

--------------------------------------------*/

#include <X11/Xlib.h>
#include <X11/Xresource.h>

#ifndef __CI_SWITCH_DEFS__
#define __CI_SWITCH_DEFS__

#ifdef __cplusplus
#define SWITCH_ELLIPSIS ...
#else
#define SWITCH_ELLIPSIS 

#endif

#ifndef __CiDefs__

typedef void            (*CiRoutine)(SWITCH_ELLIPSIS);
typedef char            (*CiCRoutine)(SWITCH_ELLIPSIS);
typedef short           (*CiSRoutine)(SWITCH_ELLIPSIS);
typedef int             (*CiIRoutine)(SWITCH_ELLIPSIS);
typedef long            (*CiLRoutine)(SWITCH_ELLIPSIS);
typedef unsigned char   (*CiUCRoutine)(SWITCH_ELLIPSIS);
typedef unsigned short  (*CiUSRoutine)(SWITCH_ELLIPSIS);
typedef unsigned int    (*CiUIRoutine)(SWITCH_ELLIPSIS);
typedef unsigned long   (*CiULRoutine)(SWITCH_ELLIPSIS);
typedef float           (*CiFRoutine)(SWITCH_ELLIPSIS);
typedef double          (*CiDRoutine)(SWITCH_ELLIPSIS);
typedef void*           (*CiPRoutine)(SWITCH_ELLIPSIS);

#endif

#ifndef __CiType__

typedef union {
  char c;
  short s;
  int i;
  long l;
  char* p;
  float f;
  double d;
} CiPrimValueRec, *CiPrimValue;

#endif

#endif

#ifdef __cplusplus
extern "C" {
#endif

CiRoutine CiBindXresource (char* library);

static void CiBindXresourceInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew);

static char* CiBindXresourceSetupFunction (CiRoutine* switchFunction);

static void CiBindXresourceSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue);
void CiBindXresourceCleanup ();

static CiRoutine CiBindXresourceFileCompile       = 0;
static CiRoutine CiBindXresourceFunctionBind      = 0;
static CiRoutine CiBindXresourceVariableBind      = 0;
static CiRoutine CiBindXresourceFunctionSwitchNew = 0;

#ifdef __cplusplus
}
#endif

/*- Procedure ------------------------------------------*/
CiRoutine CiBindXresource (char* library)
/*------------------------------------------------------*/
{
  static int first = 1;

  if (first)
    {
      first = 0;
    }
  else if (CiBindXresourceFunctionSwitchNew)
    {
      CiBindXresourceFunctionSwitchNew ((CiRoutine) CiBindXresourceSetupFunction);
    }

  library = 0;

  return ((CiRoutine) CiBindXresourceInitFunction);
}

/*- Procedure ------------------------------------------*/
static void CiBindXresourceInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew)
/*------------------------------------------------------*/
{
  CiBindXresourceFileCompile       = compileFunction;
  pathFunction = 0;
  CiBindXresourceFunctionBind      = bindFunction;
  CiBindXresourceVariableBind      = bindVariable;
  CiBindXresourceFunctionSwitchNew = switchNew;
  CiBindXresourceVariableBind (0, 0);
  CiBindXresourceFunctionBind (0, 0);
}

/*- Procedure ------------------------------------------*/
static char* CiBindXresourceSetupFunction (CiRoutine* switchFunction)
/*------------------------------------------------------*/
{
  static char cases[] = {
    0
  };
  static int first = 1;
  
  if (first)
    {
      first = 0;
  
      CiBindXresourceFileCompile ("X11/Xlib.h");
      CiBindXresourceFileCompile ("X11/Xresource.h");
    }
  *switchFunction = (CiRoutine) CiBindXresourceSwitchFunction;
  return ((char*) cases);
}

/*- Procedure ------------------------------------------*/
static void CiBindXresourceSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue)
/*------------------------------------------------------*/
{
  CiPrimValueRec prim;
  
  prim.l = 0;
  
  f = 0;
  code = 0;
  
  args = 0;
  position = 0;
  
  if (retValue) *retValue = prim;
}

/*--------------------------------------------
  This file has been generated by cigen       
  using the following command :               

  $CIBIN/cigen.exe -p -h X11/Xlib.h -f X11/Xutil.h -n CiBindXutil -o ../gen/Xutil_B.c

--------------------------------------------*/

#include <X11/Xlib.h>
#include <X11/Xutil.h>

#ifndef __CI_SWITCH_DEFS__
#define __CI_SWITCH_DEFS__

#ifdef __cplusplus
#define SWITCH_ELLIPSIS ...
#else
#define SWITCH_ELLIPSIS 

#endif

#ifndef __CiDefs__

typedef void            (*CiRoutine)(SWITCH_ELLIPSIS);
typedef char            (*CiCRoutine)(SWITCH_ELLIPSIS);
typedef short           (*CiSRoutine)(SWITCH_ELLIPSIS);
typedef int             (*CiIRoutine)(SWITCH_ELLIPSIS);
typedef long            (*CiLRoutine)(SWITCH_ELLIPSIS);
typedef unsigned char   (*CiUCRoutine)(SWITCH_ELLIPSIS);
typedef unsigned short  (*CiUSRoutine)(SWITCH_ELLIPSIS);
typedef unsigned int    (*CiUIRoutine)(SWITCH_ELLIPSIS);
typedef unsigned long   (*CiULRoutine)(SWITCH_ELLIPSIS);
typedef float           (*CiFRoutine)(SWITCH_ELLIPSIS);
typedef double          (*CiDRoutine)(SWITCH_ELLIPSIS);
typedef void*           (*CiPRoutine)(SWITCH_ELLIPSIS);

#endif

#ifndef __CiType__

typedef union {
  char c;
  short s;
  int i;
  long l;
  char* p;
  float f;
  double d;
} CiPrimValueRec, *CiPrimValue;

#endif

#endif

#ifdef __cplusplus
extern "C" {
#endif

CiRoutine CiBindXutil (char* library);

static void CiBindXutilInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew);

static char* CiBindXutilSetupFunction (CiRoutine* switchFunction);

static void CiBindXutilSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue);
void CiBindXutilCleanup ();

static CiRoutine CiBindXutilFileCompile       = 0;
static CiRoutine CiBindXutilFunctionBind      = 0;
static CiRoutine CiBindXutilVariableBind      = 0;
static CiRoutine CiBindXutilFunctionSwitchNew = 0;

#ifdef __cplusplus
}
#endif

/*- Procedure ------------------------------------------*/
CiRoutine CiBindXutil (char* library)
/*------------------------------------------------------*/
{
  static int first = 1;

  if (first)
    {
      first = 0;
    }
  else if (CiBindXutilFunctionSwitchNew)
    {
      CiBindXutilFunctionSwitchNew ((CiRoutine) CiBindXutilSetupFunction);
    }

  library = 0;

  return ((CiRoutine) CiBindXutilInitFunction);
}

/*- Procedure ------------------------------------------*/
static void CiBindXutilInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew)
/*------------------------------------------------------*/
{
  CiBindXutilFileCompile       = compileFunction;
  pathFunction = 0;
  CiBindXutilFunctionBind      = bindFunction;
  CiBindXutilVariableBind      = bindVariable;
  CiBindXutilFunctionSwitchNew = switchNew;
  CiBindXutilVariableBind (0, 0);
  CiBindXutilFunctionBind (0, 0);
}

/*- Procedure ------------------------------------------*/
static char* CiBindXutilSetupFunction (CiRoutine* switchFunction)
/*------------------------------------------------------*/
{
  static char cases[] = {
    0
  };
  static int first = 1;
  
  if (first)
    {
      first = 0;
  
      CiBindXutilFileCompile ("X11/Xlib.h");
      CiBindXutilFileCompile ("X11/Xutil.h");
    }
  *switchFunction = (CiRoutine) CiBindXutilSwitchFunction;
  return ((char*) cases);
}

/*- Procedure ------------------------------------------*/
static void CiBindXutilSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue)
/*------------------------------------------------------*/
{
  CiPrimValueRec prim;
  
  prim.l = 0;
  
  f = 0;
  code = 0;
  
  args = 0;
  position = 0;
  
  if (retValue) *retValue = prim;
}

