#ifdef HAS_XM
/*--------------------------------------------
  This file has been generated by cigen       
  using the following command :               

  $CIBIN/cigen.exe -p -h X11/Intrinsic.h -f Xm/Form.h -n CiBindForm -o x.lis

--------------------------------------------*/

#include <X11/Intrinsic.h>
#include <Xm/Form.h>

#ifndef __CI_SWITCH_DEFS__
#define __CI_SWITCH_DEFS__

#ifdef __cplusplus
#define SWITCH_ELLIPSIS ...
#else
#define SWITCH_ELLIPSIS 

#endif

#ifndef __CiDefs__

typedef void            (*CiRoutine)(SWITCH_ELLIPSIS);
typedef char            (*CiCRoutine)(SWITCH_ELLIPSIS);
typedef short           (*CiSRoutine)(SWITCH_ELLIPSIS);
typedef int             (*CiIRoutine)(SWITCH_ELLIPSIS);
typedef long            (*CiLRoutine)(SWITCH_ELLIPSIS);
typedef unsigned char   (*CiUCRoutine)(SWITCH_ELLIPSIS);
typedef unsigned short  (*CiUSRoutine)(SWITCH_ELLIPSIS);
typedef unsigned int    (*CiUIRoutine)(SWITCH_ELLIPSIS);
typedef unsigned long   (*CiULRoutine)(SWITCH_ELLIPSIS);
typedef float           (*CiFRoutine)(SWITCH_ELLIPSIS);
typedef double          (*CiDRoutine)(SWITCH_ELLIPSIS);
typedef void*           (*CiPRoutine)(SWITCH_ELLIPSIS);

#endif

#ifndef __CiType__

typedef union {
  char c;
  short s;
  int i;
  long l;
  char* p;
  float f;
  double d;
} CiPrimValueRec, *CiPrimValue;

#endif

#endif

#ifdef __cplusplus
extern "C" {
#endif

CiRoutine CiBindForm (char* library);

static void CiBindFormInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew);

static char* CiBindFormSetupFunction (CiRoutine* switchFunction);

static void CiBindFormSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue);
void CiBindFormCleanup ();

static CiRoutine CiBindFormFileCompile       = 0;
static CiRoutine CiBindFormFunctionBind      = 0;
static CiRoutine CiBindFormVariableBind      = 0;
static CiRoutine CiBindFormFunctionSwitchNew = 0;

#ifdef __cplusplus
}
#endif

/*- Procedure ------------------------------------------*/
CiRoutine CiBindForm (char* library)
/*------------------------------------------------------*/
{
  static int first = 1;

  if (first)
    {
      first = 0;
    }
  else if (CiBindFormFunctionSwitchNew)
    {
      CiBindFormFunctionSwitchNew ((CiRoutine) CiBindFormSetupFunction);
    }

  library = 0;

  return ((CiRoutine) CiBindFormInitFunction);
}

/*- Procedure ------------------------------------------*/
static void CiBindFormInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew)
/*------------------------------------------------------*/
{
  CiBindFormFileCompile       = compileFunction;
  pathFunction = 0;
  CiBindFormFunctionBind      = bindFunction;
  CiBindFormVariableBind      = bindVariable;
  CiBindFormFunctionSwitchNew = switchNew;
  CiBindFormVariableBind (0, 0);
  CiBindFormFunctionBind (0, 0);
}

/*- Procedure ------------------------------------------*/
static char* CiBindFormSetupFunction (CiRoutine* switchFunction)
/*------------------------------------------------------*/
{
  static char cases[] = {
    0
  };
  static int first = 1;
  
  if (first)
    {
      first = 0;
  
      CiBindFormFileCompile ("X11/Intrinsic.h");
      CiBindFormFileCompile ("Xm/Form.h");
      CiBindFormVariableBind ("xmFormWidgetClass", &xmFormWidgetClass);
    }
  *switchFunction = (CiRoutine) CiBindFormSwitchFunction;
  return ((char*) cases);
}

/*- Procedure ------------------------------------------*/
static void CiBindFormSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue)
/*------------------------------------------------------*/
{
  CiPrimValueRec prim;
  
  prim.l = 0;
  
  f = 0;
  code = 0;
  
  args = 0;
  position = 0;
  
  if (retValue) *retValue = prim;
}

#else /*HAS_XM*/
#include <stddef.h>
#endif /*HAS_XM*/
#ifdef HAS_XM
/*--------------------------------------------
  This file has been generated by cigen       
  using the following command :               

  $CIBIN/cigen.exe -p -h Xm/Xm.h -f Xm/List.h -n CiBindList -o x.lis

--------------------------------------------*/

#include <Xm/Xm.h>
#include <Xm/List.h>

#ifndef __CI_SWITCH_DEFS__
#define __CI_SWITCH_DEFS__

#ifdef __cplusplus
#define SWITCH_ELLIPSIS ...
#else
#define SWITCH_ELLIPSIS 

#endif

#ifndef __CiDefs__

typedef void            (*CiRoutine)(SWITCH_ELLIPSIS);
typedef char            (*CiCRoutine)(SWITCH_ELLIPSIS);
typedef short           (*CiSRoutine)(SWITCH_ELLIPSIS);
typedef int             (*CiIRoutine)(SWITCH_ELLIPSIS);
typedef long            (*CiLRoutine)(SWITCH_ELLIPSIS);
typedef unsigned char   (*CiUCRoutine)(SWITCH_ELLIPSIS);
typedef unsigned short  (*CiUSRoutine)(SWITCH_ELLIPSIS);
typedef unsigned int    (*CiUIRoutine)(SWITCH_ELLIPSIS);
typedef unsigned long   (*CiULRoutine)(SWITCH_ELLIPSIS);
typedef float           (*CiFRoutine)(SWITCH_ELLIPSIS);
typedef double          (*CiDRoutine)(SWITCH_ELLIPSIS);
typedef void*           (*CiPRoutine)(SWITCH_ELLIPSIS);

#endif

#ifndef __CiType__

typedef union {
  char c;
  short s;
  int i;
  long l;
  char* p;
  float f;
  double d;
} CiPrimValueRec, *CiPrimValue;

#endif

#endif

#ifdef __cplusplus
extern "C" {
#endif

CiRoutine CiBindList (char* library);

static void CiBindListInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew);

static char* CiBindListSetupFunction (CiRoutine* switchFunction);

static void CiBindListSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue);
void CiBindListCleanup ();

static CiRoutine CiBindListFileCompile       = 0;
static CiRoutine CiBindListFunctionBind      = 0;
static CiRoutine CiBindListVariableBind      = 0;
static CiRoutine CiBindListFunctionSwitchNew = 0;

#ifdef __cplusplus
}
#endif

/*- Procedure ------------------------------------------*/
CiRoutine CiBindList (char* library)
/*------------------------------------------------------*/
{
  static int first = 1;

  if (first)
    {
      first = 0;
    }
  else if (CiBindListFunctionSwitchNew)
    {
      CiBindListFunctionSwitchNew ((CiRoutine) CiBindListSetupFunction);
    }

  library = 0;

  return ((CiRoutine) CiBindListInitFunction);
}

/*- Procedure ------------------------------------------*/
static void CiBindListInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew)
/*------------------------------------------------------*/
{
  CiBindListFileCompile       = compileFunction;
  pathFunction = 0;
  CiBindListFunctionBind      = bindFunction;
  CiBindListVariableBind      = bindVariable;
  CiBindListFunctionSwitchNew = switchNew;
  CiBindListVariableBind (0, 0);
  CiBindListFunctionBind (0, 0);
}

/*- Procedure ------------------------------------------*/
static char* CiBindListSetupFunction (CiRoutine* switchFunction)
/*------------------------------------------------------*/
{
  static char cases[] = {
    1, 6, 4, 0,
    1, 6, 6, 0,
    1, 6, 4, 4, 0,
    2, 6, 6, 6, 0,
    1, 6, 6, 4, 0,
    1, 6, 0,
    0
  };
  static int first = 1;
  
  if (first)
    {
      first = 0;
  
      CiBindListFileCompile ("Xm/Xm.h");
      CiBindListFileCompile ("Xm/List.h");
      CiBindListFunctionBind ("XmListDeleteAllItems", (CiRoutine) XmListDeleteAllItems);
      CiBindListFunctionBind ("XmListDeleteItem", (CiRoutine) XmListDeleteItem);
      CiBindListVariableBind ("xmListWidgetClass", &xmListWidgetClass);
      CiBindListFunctionBind ("XmListDeleteItemsPos", (CiRoutine) XmListDeleteItemsPos);
      CiBindListFunctionBind ("XmListGetSelectedPos", (CiRoutine) XmListGetSelectedPos);
      CiBindListFunctionBind ("XmListDeletePos", (CiRoutine) XmListDeletePos);
      CiBindListFunctionBind ("XmListDeleteItems", (CiRoutine) XmListDeleteItems);
    }
  *switchFunction = (CiRoutine) CiBindListSwitchFunction;
  return ((char*) cases);
}

/*- Procedure ------------------------------------------*/
static void CiBindListSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue)
/*------------------------------------------------------*/
{
  CiPrimValueRec prim;
  
  prim.l = 0;
  
  switch (code)
  {
    case 2 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].i);
          }
          break;
      }
      break;
    case 4 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p);
          }
          break;
      }
      break;
    case 7 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].i, args[2].i);
          }
          break;
      }
      break;
    case 32 :
      switch (position)
      {
        case 1 :
          {
            CiCRoutine g = (CiCRoutine) f;

            prim.c = g (args[0].p, args[1].p, args[2].p);
          }
          break;
      }
      break;
    case 33 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p, args[2].i);
          }
          break;
      }
      break;
    case 37 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p);
          }
          break;
      }
      break;
  }
  
  args = 0;
  position = 0;
  
  if (retValue) *retValue = prim;
}

#else /*HAS_XM*/
#include <stddef.h>
#endif /*HAS_XM*/
#ifdef HAS_XM
/*--------------------------------------------
  This file has been generated by cigen       
  using the following command :               

  $CIBIN/cigen.exe -p -h X11/Intrinsic.h -f Xm/RowColumn.h -n CiBindRowColumn -o x.lis

--------------------------------------------*/

#include <X11/Intrinsic.h>
#include <Xm/RowColumn.h>

#ifndef __CI_SWITCH_DEFS__
#define __CI_SWITCH_DEFS__

#ifdef __cplusplus
#define SWITCH_ELLIPSIS ...
#else
#define SWITCH_ELLIPSIS 

#endif

#ifndef __CiDefs__

typedef void            (*CiRoutine)(SWITCH_ELLIPSIS);
typedef char            (*CiCRoutine)(SWITCH_ELLIPSIS);
typedef short           (*CiSRoutine)(SWITCH_ELLIPSIS);
typedef int             (*CiIRoutine)(SWITCH_ELLIPSIS);
typedef long            (*CiLRoutine)(SWITCH_ELLIPSIS);
typedef unsigned char   (*CiUCRoutine)(SWITCH_ELLIPSIS);
typedef unsigned short  (*CiUSRoutine)(SWITCH_ELLIPSIS);
typedef unsigned int    (*CiUIRoutine)(SWITCH_ELLIPSIS);
typedef unsigned long   (*CiULRoutine)(SWITCH_ELLIPSIS);
typedef float           (*CiFRoutine)(SWITCH_ELLIPSIS);
typedef double          (*CiDRoutine)(SWITCH_ELLIPSIS);
typedef void*           (*CiPRoutine)(SWITCH_ELLIPSIS);

#endif

#ifndef __CiType__

typedef union {
  char c;
  short s;
  int i;
  long l;
  char* p;
  float f;
  double d;
} CiPrimValueRec, *CiPrimValue;

#endif

#endif

#ifdef __cplusplus
extern "C" {
#endif

CiRoutine CiBindRowColumn (char* library);

static void CiBindRowColumnInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew);

static char* CiBindRowColumnSetupFunction (CiRoutine* switchFunction);

static void CiBindRowColumnSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue);
void CiBindRowColumnCleanup ();

static CiRoutine CiBindRowColumnFileCompile       = 0;
static CiRoutine CiBindRowColumnFunctionBind      = 0;
static CiRoutine CiBindRowColumnVariableBind      = 0;
static CiRoutine CiBindRowColumnFunctionSwitchNew = 0;

#ifdef __cplusplus
}
#endif

/*- Procedure ------------------------------------------*/
CiRoutine CiBindRowColumn (char* library)
/*------------------------------------------------------*/
{
  static int first = 1;

  if (first)
    {
      first = 0;
    }
  else if (CiBindRowColumnFunctionSwitchNew)
    {
      CiBindRowColumnFunctionSwitchNew ((CiRoutine) CiBindRowColumnSetupFunction);
    }

  library = 0;

  return ((CiRoutine) CiBindRowColumnInitFunction);
}

/*- Procedure ------------------------------------------*/
static void CiBindRowColumnInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew)
/*------------------------------------------------------*/
{
  CiBindRowColumnFileCompile       = compileFunction;
  pathFunction = 0;
  CiBindRowColumnFunctionBind      = bindFunction;
  CiBindRowColumnVariableBind      = bindVariable;
  CiBindRowColumnFunctionSwitchNew = switchNew;
  CiBindRowColumnVariableBind (0, 0);
  CiBindRowColumnFunctionBind (0, 0);
}

/*- Procedure ------------------------------------------*/
static char* CiBindRowColumnSetupFunction (CiRoutine* switchFunction)
/*------------------------------------------------------*/
{
  static char cases[] = {
    1, 6, 6, 0,
    0
  };
  static int first = 1;
  
  if (first)
    {
      first = 0;
  
      CiBindRowColumnFileCompile ("X11/Intrinsic.h");
      CiBindRowColumnFileCompile ("Xm/RowColumn.h");
      CiBindRowColumnVariableBind ("xmRowColumnWidgetClass", &xmRowColumnWidgetClass);
      CiBindRowColumnFunctionBind ("XmMenuPosition", (CiRoutine) XmMenuPosition);
    }
  *switchFunction = (CiRoutine) CiBindRowColumnSwitchFunction;
  return ((char*) cases);
}

/*- Procedure ------------------------------------------*/
static void CiBindRowColumnSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue)
/*------------------------------------------------------*/
{
  CiPrimValueRec prim;
  
  prim.l = 0;
  
  switch (code)
  {
    case 4 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p);
          }
          break;
      }
      break;
  }
  
  args = 0;
  position = 0;
  
  if (retValue) *retValue = prim;
}

#else /*HAS_XM*/
#include <stddef.h>
#endif /*HAS_XM*/
#ifdef HAS_XM
/*--------------------------------------------
  This file has been generated by cigen       
  using the following command :               

  $CIBIN/cigen.exe -p -h X11/Intrinsic.h -f Xm/Scale.h -n CiBindScale -o x.lis

--------------------------------------------*/

#include <X11/Intrinsic.h>
#include <Xm/Scale.h>

#ifndef __CI_SWITCH_DEFS__
#define __CI_SWITCH_DEFS__

#ifdef __cplusplus
#define SWITCH_ELLIPSIS ...
#else
#define SWITCH_ELLIPSIS 

#endif

#ifndef __CiDefs__

typedef void            (*CiRoutine)(SWITCH_ELLIPSIS);
typedef char            (*CiCRoutine)(SWITCH_ELLIPSIS);
typedef short           (*CiSRoutine)(SWITCH_ELLIPSIS);
typedef int             (*CiIRoutine)(SWITCH_ELLIPSIS);
typedef long            (*CiLRoutine)(SWITCH_ELLIPSIS);
typedef unsigned char   (*CiUCRoutine)(SWITCH_ELLIPSIS);
typedef unsigned short  (*CiUSRoutine)(SWITCH_ELLIPSIS);
typedef unsigned int    (*CiUIRoutine)(SWITCH_ELLIPSIS);
typedef unsigned long   (*CiULRoutine)(SWITCH_ELLIPSIS);
typedef float           (*CiFRoutine)(SWITCH_ELLIPSIS);
typedef double          (*CiDRoutine)(SWITCH_ELLIPSIS);
typedef void*           (*CiPRoutine)(SWITCH_ELLIPSIS);

#endif

#ifndef __CiType__

typedef union {
  char c;
  short s;
  int i;
  long l;
  char* p;
  float f;
  double d;
} CiPrimValueRec, *CiPrimValue;

#endif

#endif

#ifdef __cplusplus
extern "C" {
#endif

CiRoutine CiBindScale (char* library);

static void CiBindScaleInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew);

static char* CiBindScaleSetupFunction (CiRoutine* switchFunction);

static void CiBindScaleSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue);
void CiBindScaleCleanup ();

static CiRoutine CiBindScaleFileCompile       = 0;
static CiRoutine CiBindScaleFunctionBind      = 0;
static CiRoutine CiBindScaleVariableBind      = 0;
static CiRoutine CiBindScaleFunctionSwitchNew = 0;

#ifdef __cplusplus
}
#endif

/*- Procedure ------------------------------------------*/
CiRoutine CiBindScale (char* library)
/*------------------------------------------------------*/
{
  static int first = 1;

  if (first)
    {
      first = 0;
    }
  else if (CiBindScaleFunctionSwitchNew)
    {
      CiBindScaleFunctionSwitchNew ((CiRoutine) CiBindScaleSetupFunction);
    }

  library = 0;

  return ((CiRoutine) CiBindScaleInitFunction);
}

/*- Procedure ------------------------------------------*/
static void CiBindScaleInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew)
/*------------------------------------------------------*/
{
  CiBindScaleFileCompile       = compileFunction;
  pathFunction = 0;
  CiBindScaleFunctionBind      = bindFunction;
  CiBindScaleVariableBind      = bindVariable;
  CiBindScaleFunctionSwitchNew = switchNew;
  CiBindScaleVariableBind (0, 0);
  CiBindScaleFunctionBind (0, 0);
}

/*- Procedure ------------------------------------------*/
static char* CiBindScaleSetupFunction (CiRoutine* switchFunction)
/*------------------------------------------------------*/
{
  static char cases[] = {
    1, 6, 4, 0,
    1, 6, 6, 0,
    0
  };
  static int first = 1;
  
  if (first)
    {
      first = 0;
  
      CiBindScaleFileCompile ("X11/Intrinsic.h");
      CiBindScaleFileCompile ("Xm/Scale.h");
      CiBindScaleFunctionBind ("XmScaleSetValue", (CiRoutine) XmScaleSetValue);
      CiBindScaleFunctionBind ("XmScaleGetValue", (CiRoutine) XmScaleGetValue);
      CiBindScaleVariableBind ("xmScaleWidgetClass", &xmScaleWidgetClass);
    }
  *switchFunction = (CiRoutine) CiBindScaleSwitchFunction;
  return ((char*) cases);
}

/*- Procedure ------------------------------------------*/
static void CiBindScaleSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue)
/*------------------------------------------------------*/
{
  CiPrimValueRec prim;
  
  prim.l = 0;
  
  switch (code)
  {
    case 2 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].i);
          }
          break;
      }
      break;
    case 4 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p);
          }
          break;
      }
      break;
  }
  
  args = 0;
  position = 0;
  
  if (retValue) *retValue = prim;
}

#else /*HAS_XM*/
#include <stddef.h>
#endif /*HAS_XM*/
#ifdef HAS_XM
/*--------------------------------------------
  This file has been generated by cigen       
  using the following command :               

  $CIBIN/cigen.exe -p -h Xm/Xm.h -f Xm/Text.h -n CiBindText -o x.lis

--------------------------------------------*/

#include <Xm/Xm.h>
#include <Xm/Text.h>

#ifndef __CI_SWITCH_DEFS__
#define __CI_SWITCH_DEFS__

#ifdef __cplusplus
#define SWITCH_ELLIPSIS ...
#else
#define SWITCH_ELLIPSIS 

#endif

#ifndef __CiDefs__

typedef void            (*CiRoutine)(SWITCH_ELLIPSIS);
typedef char            (*CiCRoutine)(SWITCH_ELLIPSIS);
typedef short           (*CiSRoutine)(SWITCH_ELLIPSIS);
typedef int             (*CiIRoutine)(SWITCH_ELLIPSIS);
typedef long            (*CiLRoutine)(SWITCH_ELLIPSIS);
typedef unsigned char   (*CiUCRoutine)(SWITCH_ELLIPSIS);
typedef unsigned short  (*CiUSRoutine)(SWITCH_ELLIPSIS);
typedef unsigned int    (*CiUIRoutine)(SWITCH_ELLIPSIS);
typedef unsigned long   (*CiULRoutine)(SWITCH_ELLIPSIS);
typedef float           (*CiFRoutine)(SWITCH_ELLIPSIS);
typedef double          (*CiDRoutine)(SWITCH_ELLIPSIS);
typedef void*           (*CiPRoutine)(SWITCH_ELLIPSIS);

#endif

#ifndef __CiType__

typedef union {
  char c;
  short s;
  int i;
  long l;
  char* p;
  float f;
  double d;
} CiPrimValueRec, *CiPrimValue;

#endif

#endif

#ifdef __cplusplus
extern "C" {
#endif

CiRoutine CiBindText (char* library);

static void CiBindTextInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew);

static char* CiBindTextSetupFunction (CiRoutine* switchFunction);

static void CiBindTextSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue);
void CiBindTextCleanup ();

static CiRoutine CiBindTextFileCompile       = 0;
static CiRoutine CiBindTextFunctionBind      = 0;
static CiRoutine CiBindTextVariableBind      = 0;
static CiRoutine CiBindTextFunctionSwitchNew = 0;

#ifdef __cplusplus
}
#endif

/*- Procedure ------------------------------------------*/
CiRoutine CiBindText (char* library)
/*------------------------------------------------------*/
{
  static int first = 1;

  if (first)
    {
      first = 0;
    }
  else if (CiBindTextFunctionSwitchNew)
    {
      CiBindTextFunctionSwitchNew ((CiRoutine) CiBindTextSetupFunction);
    }

  library = 0;

  return ((CiRoutine) CiBindTextInitFunction);
}

/*- Procedure ------------------------------------------*/
static void CiBindTextInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew)
/*------------------------------------------------------*/
{
  CiBindTextFileCompile       = compileFunction;
  pathFunction = 0;
  CiBindTextFunctionBind      = bindFunction;
  CiBindTextVariableBind      = bindVariable;
  CiBindTextFunctionSwitchNew = switchNew;
  CiBindTextVariableBind (0, 0);
  CiBindTextFunctionBind (0, 0);
}

/*- Procedure ------------------------------------------*/
static char* CiBindTextSetupFunction (CiRoutine* switchFunction)
/*------------------------------------------------------*/
{
  static char cases[] = {
    1, 6, 2, 0,
    1, 6, 5, 0,
    1, 6, 5, 5, 6, 0,
    1, 6, 6, 0,
    5, 6, 0,
    2, 6, 0,
    6, 6, 0,
    0
  };
  static int first = 1;
  
  if (first)
    {
      first = 0;
  
      CiBindTextFileCompile ("Xm/Xm.h");
      CiBindTextFileCompile ("Xm/Text.h");
      CiBindTextFunctionBind ("XmTextReplace", (CiRoutine) XmTextReplace);
      CiBindTextFunctionBind ("XmTextGetEditable", (CiRoutine) XmTextGetEditable);
      CiBindTextFunctionBind ("XmTextSetInsertionPosition", (CiRoutine) XmTextSetInsertionPosition);
      CiBindTextFunctionBind ("XmTextGetString", (CiRoutine) XmTextGetString);
      CiBindTextFunctionBind ("XmTextSetString", (CiRoutine) XmTextSetString);
      CiBindTextFunctionBind ("XmTextGetLastPosition", (CiRoutine) XmTextGetLastPosition);
      CiBindTextVariableBind ("xmTextWidgetClass", &xmTextWidgetClass);
      CiBindTextFunctionBind ("XmTextSetEditable", (CiRoutine) XmTextSetEditable);
    }
  *switchFunction = (CiRoutine) CiBindTextSwitchFunction;
  return ((char*) cases);
}

/*- Procedure ------------------------------------------*/
static void CiBindTextSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue)
/*------------------------------------------------------*/
{
  CiPrimValueRec prim;
  
  prim.l = 0;
  
  switch (code)
  {
    case 0 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].c);
          }
          break;
      }
      break;
    case 3 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].l);
          }
          break;
      }
      break;
    case 4 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].l, args[2].l, args[3].p);
          }
          break;
        case 2 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p);
          }
          break;
      }
      break;
    case 9 :
      switch (position)
      {
        case 1 :
          {
            CiLRoutine g = (CiLRoutine) f;

            prim.l = g (args[0].p);
          }
          break;
      }
      break;
    case 10 :
      switch (position)
      {
        case 1 :
          {
            CiCRoutine g = (CiCRoutine) f;

            prim.c = g (args[0].p);
          }
          break;
      }
      break;
    case 22 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p);
          }
          break;
      }
      break;
  }
  
  args = 0;
  position = 0;
  
  if (retValue) *retValue = prim;
}

#else /*HAS_XM*/
#include <stddef.h>
#endif /*HAS_XM*/
#ifdef HAS_XM
/*--------------------------------------------
  This file has been generated by cigen       
  using the following command :               

  $CIBIN/cigen.exe -p -h X11/Intrinsic.h -f Xm/ToggleB.h -n CiBindToggleB -o x.lis

--------------------------------------------*/

#include <X11/Intrinsic.h>
#include <Xm/ToggleB.h>

#ifndef __CI_SWITCH_DEFS__
#define __CI_SWITCH_DEFS__

#ifdef __cplusplus
#define SWITCH_ELLIPSIS ...
#else
#define SWITCH_ELLIPSIS 

#endif

#ifndef __CiDefs__

typedef void            (*CiRoutine)(SWITCH_ELLIPSIS);
typedef char            (*CiCRoutine)(SWITCH_ELLIPSIS);
typedef short           (*CiSRoutine)(SWITCH_ELLIPSIS);
typedef int             (*CiIRoutine)(SWITCH_ELLIPSIS);
typedef long            (*CiLRoutine)(SWITCH_ELLIPSIS);
typedef unsigned char   (*CiUCRoutine)(SWITCH_ELLIPSIS);
typedef unsigned short  (*CiUSRoutine)(SWITCH_ELLIPSIS);
typedef unsigned int    (*CiUIRoutine)(SWITCH_ELLIPSIS);
typedef unsigned long   (*CiULRoutine)(SWITCH_ELLIPSIS);
typedef float           (*CiFRoutine)(SWITCH_ELLIPSIS);
typedef double          (*CiDRoutine)(SWITCH_ELLIPSIS);
typedef void*           (*CiPRoutine)(SWITCH_ELLIPSIS);

#endif

#ifndef __CiType__

typedef union {
  char c;
  short s;
  int i;
  long l;
  char* p;
  float f;
  double d;
} CiPrimValueRec, *CiPrimValue;

#endif

#endif

#ifdef __cplusplus
extern "C" {
#endif

CiRoutine CiBindToggleB (char* library);

static void CiBindToggleBInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew);

static char* CiBindToggleBSetupFunction (CiRoutine* switchFunction);

static void CiBindToggleBSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue);
void CiBindToggleBCleanup ();

static CiRoutine CiBindToggleBFileCompile       = 0;
static CiRoutine CiBindToggleBFunctionBind      = 0;
static CiRoutine CiBindToggleBVariableBind      = 0;
static CiRoutine CiBindToggleBFunctionSwitchNew = 0;

#ifdef __cplusplus
}
#endif

/*- Procedure ------------------------------------------*/
CiRoutine CiBindToggleB (char* library)
/*------------------------------------------------------*/
{
  static int first = 1;

  if (first)
    {
      first = 0;
    }
  else if (CiBindToggleBFunctionSwitchNew)
    {
      CiBindToggleBFunctionSwitchNew ((CiRoutine) CiBindToggleBSetupFunction);
    }

  library = 0;

  return ((CiRoutine) CiBindToggleBInitFunction);
}

/*- Procedure ------------------------------------------*/
static void CiBindToggleBInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew)
/*------------------------------------------------------*/
{
  CiBindToggleBFileCompile       = compileFunction;
  pathFunction = 0;
  CiBindToggleBFunctionBind      = bindFunction;
  CiBindToggleBVariableBind      = bindVariable;
  CiBindToggleBFunctionSwitchNew = switchNew;
  CiBindToggleBVariableBind (0, 0);
  CiBindToggleBFunctionBind (0, 0);
}

/*- Procedure ------------------------------------------*/
static char* CiBindToggleBSetupFunction (CiRoutine* switchFunction)
/*------------------------------------------------------*/
{
  static char cases[] = {
    2, 6, 0,
    1, 6, 2, 2, 0,
    0
  };
  static int first = 1;
  
  if (first)
    {
      first = 0;
  
      CiBindToggleBFileCompile ("X11/Intrinsic.h");
      CiBindToggleBFileCompile ("Xm/ToggleB.h");
      CiBindToggleBFunctionBind ("XmToggleButtonSetState", (CiRoutine) XmToggleButtonSetState);
      CiBindToggleBFunctionBind ("XmToggleButtonGetState", (CiRoutine) XmToggleButtonGetState);
      CiBindToggleBVariableBind ("xmToggleButtonWidgetClass", &xmToggleButtonWidgetClass);
    }
  *switchFunction = (CiRoutine) CiBindToggleBSwitchFunction;
  return ((char*) cases);
}

/*- Procedure ------------------------------------------*/
static void CiBindToggleBSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue)
/*------------------------------------------------------*/
{
  CiPrimValueRec prim;
  
  prim.l = 0;
  
  switch (code)
  {
    case 10 :
      switch (position)
      {
        case 1 :
          {
            CiCRoutine g = (CiCRoutine) f;

            prim.c = g (args[0].p);
          }
          break;
      }
      break;
    case 19 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].c, args[2].c);
          }
          break;
      }
      break;
  }
  
  args = 0;
  position = 0;
  
  if (retValue) *retValue = prim;
}

#else /*HAS_XM*/
#include <stddef.h>
#endif /*HAS_XM*/
#ifdef HAS_XM
/*--------------------------------------------
  This file has been generated by cigen       
  using the following command :               

  $CIBIN/cigen.exe -p -h stdarg.h -h stdio.h -h Xm/Xm.h -f XmTools.h -n CiBindXmTools -o x.lis

--------------------------------------------*/

#include <stdarg.h>
#include <stdio.h>
#include <Xm/Xm.h>
#include <XmTools.h>

#ifndef __CI_SWITCH_DEFS__
#define __CI_SWITCH_DEFS__

#ifdef __cplusplus
#define SWITCH_ELLIPSIS ...
#else
#define SWITCH_ELLIPSIS 

#endif

#ifndef __CiDefs__

typedef void            (*CiRoutine)(SWITCH_ELLIPSIS);
typedef char            (*CiCRoutine)(SWITCH_ELLIPSIS);
typedef short           (*CiSRoutine)(SWITCH_ELLIPSIS);
typedef int             (*CiIRoutine)(SWITCH_ELLIPSIS);
typedef long            (*CiLRoutine)(SWITCH_ELLIPSIS);
typedef unsigned char   (*CiUCRoutine)(SWITCH_ELLIPSIS);
typedef unsigned short  (*CiUSRoutine)(SWITCH_ELLIPSIS);
typedef unsigned int    (*CiUIRoutine)(SWITCH_ELLIPSIS);
typedef unsigned long   (*CiULRoutine)(SWITCH_ELLIPSIS);
typedef float           (*CiFRoutine)(SWITCH_ELLIPSIS);
typedef double          (*CiDRoutine)(SWITCH_ELLIPSIS);
typedef void*           (*CiPRoutine)(SWITCH_ELLIPSIS);

#endif

#ifndef __CiType__

typedef union {
  char c;
  short s;
  int i;
  long l;
  char* p;
  float f;
  double d;
} CiPrimValueRec, *CiPrimValue;

#endif

#endif

#ifdef __cplusplus
extern "C" {
#endif

CiRoutine CiBindXmTools (char* library);

static void CiBindXmToolsInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew);

static char* CiBindXmToolsSetupFunction (CiRoutine* switchFunction);

static void CiBindXmToolsSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue);
void CiBindXmToolsCleanup ();

static CiRoutine CiBindXmToolsFileCompile       = 0;
static CiRoutine CiBindXmToolsFunctionBind      = 0;
static CiRoutine CiBindXmToolsVariableBind      = 0;
static CiRoutine CiBindXmToolsFunctionSwitchNew = 0;

#ifdef __cplusplus
}
#endif

/*- Procedure ------------------------------------------*/
CiRoutine CiBindXmTools (char* library)
/*------------------------------------------------------*/
{
  static int first = 1;

  if (first)
    {
      first = 0;
    }
  else if (CiBindXmToolsFunctionSwitchNew)
    {
      CiBindXmToolsFunctionSwitchNew ((CiRoutine) CiBindXmToolsSetupFunction);
    }

  library = 0;

  return ((CiRoutine) CiBindXmToolsInitFunction);
}

/*- Procedure ------------------------------------------*/
static void CiBindXmToolsInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew)
/*------------------------------------------------------*/
{
  CiBindXmToolsFileCompile       = compileFunction;
  pathFunction = 0;
  CiBindXmToolsFunctionBind      = bindFunction;
  CiBindXmToolsVariableBind      = bindVariable;
  CiBindXmToolsFunctionSwitchNew = switchNew;
  CiBindXmToolsVariableBind (0, 0);
  CiBindXmToolsFunctionBind (0, 0);
}

/*- Procedure ------------------------------------------*/
static char* CiBindXmToolsSetupFunction (CiRoutine* switchFunction)
/*------------------------------------------------------*/
{
  static char cases[] = {
    1, 6, 6, 6, 4, 4, 2, 0,
    1, 6, 4, 4, 4, 4, 6, 0,
    6, 6, 4, 6, 2, 0,
    1, 6, 6, 0,
    1, 6, 4, 4, 0,
    6, 6, 4, 0,
    8, 6, 0,
    1, 6, 4, 6, 6, 0,
    6, 6, 6, 0,
    1, 6, 4, 6, 0,
    2, 6, 0,
    4, 6, 6, 6, 6, 0,
    1, 0,
    1, 4, 6, 6, 0,
    4, 0,
    1, 6, 4, 4, 4, 4, 0,
    1, 4, 6, 0,
    6, 0,
    6, 6, 6, 6, 4, 0,
    6, 6, 0,
    6, 4, 6, 0,
    6, 6, 6, 6, 6, 0,
    4, 6, 4, 0,
    8, 6, 8, 0,
    1, 6, 6, 6, 4, 6, 6, 0,
    6, 6, 6, 4, 4, 0,
    1, 6, 6, 6, 0,
    1, 4, 0,
    4, 6, 0,
    6, 6, 6, 6, 0,
    1, 6, 0,
    0
  };
  static int first = 1;
  
  if (first)
    {
      first = 0;
  
      CiBindXmToolsFileCompile ("stdarg.h");
      CiBindXmToolsFileCompile ("stdio.h");
      CiBindXmToolsFileCompile ("Xm/Xm.h");
      CiBindXmToolsFileCompile ("XmTools.h");
      CiBindXmToolsFunctionBind ("XmTextSetValueFromStream", (CiRoutine) XmTextSetValueFromStream);
      CiBindXmToolsFunctionBind ("XmDialogAskForText", (CiRoutine) XmDialogAskForText);
      CiBindXmToolsFunctionBind ("XmTextConvertValueToWidget", (CiRoutine) XmTextConvertValueToWidget);
      CiBindXmToolsFunctionBind ("XmSelectionBoxConvertTextToInteger", (CiRoutine) XmSelectionBoxConvertTextToInteger);
      CiBindXmToolsFunctionBind ("XmTextGetValue", (CiRoutine) XmTextGetValue);
      CiBindXmToolsFunctionBind ("XmMapWidget", (CiRoutine) XmMapWidget);
      CiBindXmToolsFunctionBind ("XmCreateShellText", (CiRoutine) XmCreateShellText);
      CiBindXmToolsFunctionBind ("XmLabelSetLabelString", (CiRoutine) XmLabelSetLabelString);
      CiBindXmToolsFunctionBind ("XmLabelSetShapeAccordingToPixmap", (CiRoutine) XmLabelSetShapeAccordingToPixmap);
      CiBindXmToolsFunctionBind ("XmTextAppendString", (CiRoutine) XmTextAppendString);
      CiBindXmToolsFunctionBind ("XmStringTableCreateFromText", (CiRoutine) XmStringTableCreateFromText);
      CiBindXmToolsFunctionBind ("XmDialogAskForInteger", (CiRoutine) XmDialogAskForInteger);
      CiBindXmToolsFunctionBind ("XmOptionSetOption", (CiRoutine) XmOptionSetOption);
      CiBindXmToolsFunctionBind ("XmGetResourceOptions", (CiRoutine) XmGetResourceOptions);
      CiBindXmToolsFunctionBind ("XmDialogAskForBufferedPassword", (CiRoutine) XmDialogAskForBufferedPassword);
      CiBindXmToolsFunctionBind ("XmTextConvertValueToDouble", (CiRoutine) XmTextConvertValueToDouble);
      CiBindXmToolsFunctionBind ("XmTextSetNumberOfRowsAndColumns", (CiRoutine) XmTextSetNumberOfRowsAndColumns);
      CiBindXmToolsFunctionBind ("XmConsoleSetExitFunction", (CiRoutine) XmConsoleSetExitFunction);
      CiBindXmToolsFunctionBind ("XmConsolePutF", (CiRoutine) XmConsolePutF);
      CiBindXmToolsFunctionBind ("XmConsolePutV", (CiRoutine) XmConsolePutV);
      CiBindXmToolsFunctionBind ("XmTextPutPixmapInPS_Stream", (CiRoutine) XmTextPutPixmapInPS_Stream);
      CiBindXmToolsFunctionBind ("XmOptionInitialize", (CiRoutine) XmOptionInitialize);
      CiBindXmToolsFunctionBind ("XmListSetItemsFromStream", (CiRoutine) XmListSetItemsFromStream);
      CiBindXmToolsFunctionBind ("XmTextSetValueF", (CiRoutine) XmTextSetValueF);
      CiBindXmToolsFunctionBind ("XmConsolePrint", (CiRoutine) XmConsolePrint);
      CiBindXmToolsFunctionBind ("XmConvertStringToResourceChange", (CiRoutine) XmConvertStringToResourceChange);
      CiBindXmToolsFunctionBind ("XmDialogAskForFile", (CiRoutine) XmDialogAskForFile);
      CiBindXmToolsFunctionBind ("XmGlueWidget", (CiRoutine) XmGlueWidget);
      CiBindXmToolsFunctionBind ("XmConvertResourceValueToString", (CiRoutine) XmConvertResourceValueToString);
      CiBindXmToolsFunctionBind ("XmDialogAskForPassword", (CiRoutine) XmDialogAskForPassword);
      CiBindXmToolsFunctionBind ("XmGetCallbackEvent", (CiRoutine) XmGetCallbackEvent);
      CiBindXmToolsFunctionBind ("XmUnmapWidget", (CiRoutine) XmUnmapWidget);
      CiBindXmToolsFunctionBind ("XmConvertFontListToString", (CiRoutine) XmConvertFontListToString);
      CiBindXmToolsFunctionBind ("XmConsolePrintF", (CiRoutine) XmConsolePrintF);
      CiBindXmToolsFunctionBind ("XmFormAlignChildren", (CiRoutine) XmFormAlignChildren);
      CiBindXmToolsFunctionBind ("XmFormBuildGrid", (CiRoutine) XmFormBuildGrid);
      CiBindXmToolsFunctionBind ("XmTextSetValueFromWidgetName", (CiRoutine) XmTextSetValueFromWidgetName);
      CiBindXmToolsFunctionBind ("XmClearClass", (CiRoutine) XmClearClass);
      CiBindXmToolsFunctionBind ("XmDialogAskForString", (CiRoutine) XmDialogAskForString);
      CiBindXmToolsFunctionBind ("XmSetCompoundStringResourceFromString", (CiRoutine) XmSetCompoundStringResourceFromString);
      CiBindXmToolsFunctionBind ("XmSelectionBoxConvertTextToDouble", (CiRoutine) XmSelectionBoxConvertTextToDouble);
      CiBindXmToolsFunctionBind ("XmConsolePrintV", (CiRoutine) XmConsolePrintV);
      CiBindXmToolsFunctionBind ("XmListSetItemsFromText", (CiRoutine) XmListSetItemsFromText);
      CiBindXmToolsFunctionBind ("XmListGetSelectedItem", (CiRoutine) XmListGetSelectedItem);
      CiBindXmToolsFunctionBind ("XmConvertCompoundStringToString", (CiRoutine) XmConvertCompoundStringToString);
      CiBindXmToolsFunctionBind ("XmGetCallbackData", (CiRoutine) XmGetCallbackData);
      CiBindXmToolsFunctionBind ("XmStringTableDelete", (CiRoutine) XmStringTableDelete);
      CiBindXmToolsFunctionBind ("XmTextConvertValueToInteger", (CiRoutine) XmTextConvertValueToInteger);
      CiBindXmToolsFunctionBind ("XmLowerWidget", (CiRoutine) XmLowerWidget);
      CiBindXmToolsFunctionBind ("XmFormGetNumberOfRowsAndColumns", (CiRoutine) XmFormGetNumberOfRowsAndColumns);
      CiBindXmToolsFunctionBind ("XmListAppendString", (CiRoutine) XmListAppendString);
      CiBindXmToolsFunctionBind ("XmConsoleGetTextWidget", (CiRoutine) XmConsoleGetTextWidget);
      CiBindXmToolsFunctionBind ("XmDialogSetGetFirstShellFunction", (CiRoutine) XmDialogSetGetFirstShellFunction);
      CiBindXmToolsFunctionBind ("XmDialogAskForBoolean", (CiRoutine) XmDialogAskForBoolean);
      CiBindXmToolsFunctionBind ("XmConvertStringToFontList", (CiRoutine) XmConvertStringToFontList);
      CiBindXmToolsFunctionBind ("XmSelectionBoxInitialize", (CiRoutine) XmSelectionBoxInitialize);
      CiBindXmToolsFunctionBind ("XmRaiseWidget", (CiRoutine) XmRaiseWidget);
      CiBindXmToolsFunctionBind ("XmListSetItemsFromFile", (CiRoutine) XmListSetItemsFromFile);
      CiBindXmToolsFunctionBind ("XmDialogAskForDouble", (CiRoutine) XmDialogAskForDouble);
      CiBindXmToolsFunctionBind ("XmTextAppendValueF", (CiRoutine) XmTextAppendValueF);
      CiBindXmToolsFunctionBind ("XmStringTableCreateFromString", (CiRoutine) XmStringTableCreateFromString);
      CiBindXmToolsFunctionBind ("XmDialogWarn", (CiRoutine) XmDialogWarn);
      CiBindXmToolsFunctionBind ("XmInitializeClass", (CiRoutine) XmInitializeClass);
      CiBindXmToolsFunctionBind ("XmPopBalloon", (CiRoutine) XmPopBalloon);
      CiBindXmToolsFunctionBind ("XmTextAppendValueV", (CiRoutine) XmTextAppendValueV);
      CiBindXmToolsFunctionBind ("XmTextSetValueFromFile", (CiRoutine) XmTextSetValueFromFile);
      CiBindXmToolsFunctionBind ("XmStringTableConvertToString", (CiRoutine) XmStringTableConvertToString);
      CiBindXmToolsFunctionBind ("XmSetBalloonShape", (CiRoutine) XmSetBalloonShape);
      CiBindXmToolsFunctionBind ("XmDialogSetLocalLoopFunction", (CiRoutine) XmDialogSetLocalLoopFunction);
      CiBindXmToolsFunctionBind ("XmListSetSelectedItem", (CiRoutine) XmListSetSelectedItem);
      CiBindXmToolsFunctionBind ("XmConsoleDestroy", (CiRoutine) XmConsoleDestroy);
      CiBindXmToolsFunctionBind ("XmOptionVisit", (CiRoutine) XmOptionVisit);
      CiBindXmToolsFunctionBind ("XmAttachWidgetAtPosition", (CiRoutine) XmAttachWidgetAtPosition);
      CiBindXmToolsFunctionBind ("XmSetSideAttachment", (CiRoutine) XmSetSideAttachment);
      CiBindXmToolsFunctionBind ("XmAttachWidgetAtPositionAndMark", (CiRoutine) XmAttachWidgetAtPositionAndMark);
      CiBindXmToolsFunctionBind ("XmTextConvertValueToBoolean", (CiRoutine) XmTextConvertValueToBoolean);
      CiBindXmToolsFunctionBind ("XmOptionGetOption", (CiRoutine) XmOptionGetOption);
      CiBindXmToolsFunctionBind ("XmSelectionBoxSetText", (CiRoutine) XmSelectionBoxSetText);
      CiBindXmToolsFunctionBind ("XmStringTableGetSize", (CiRoutine) XmStringTableGetSize);
      CiBindXmToolsFunctionBind ("XmMapAndRaiseWidget", (CiRoutine) XmMapAndRaiseWidget);
      CiBindXmToolsFunctionBind ("XmMenuPopAside", (CiRoutine) XmMenuPopAside);
      CiBindXmToolsFunctionBind ("XmDialogAskForList", (CiRoutine) XmDialogAskForList);
    }
  *switchFunction = (CiRoutine) CiBindXmToolsSwitchFunction;
  return ((char*) cases);
}

/*- Procedure ------------------------------------------*/
static void CiBindXmToolsSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue)
/*------------------------------------------------------*/
{
  CiPrimValueRec prim;
  
  prim.l = 0;
  
  switch (code)
  {
    case 0 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p, args[2].p, args[3].i, 
               args[4].i, args[5].c);
          }
          break;
        case 2 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].i, args[2].i, args[3].i, 
               args[4].i, args[5].p);
          }
          break;
      }
      break;
    case 1 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p, args[1].i, args[2].p, args[3].c);
          }
          break;
      }
      break;
    case 4 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p);
          }
          break;
      }
      break;
    case 7 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].i, args[2].i);
          }
          break;
        case 2 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p, args[1].i);
          }
          break;
      }
      break;
    case 8 :
      switch (position)
      {
        case 1 :
          {
            CiDRoutine g = (CiDRoutine) f;

            prim.d = g (args[0].p);
          }
          break;
        case 2 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].i, args[2].p, args[3].p);
          }
          break;
      }
      break;
    case 9 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p, args[1].p);
          }
          break;
        case 2 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].i, args[2].p);
          }
          break;
      }
      break;
    case 10 :
      switch (position)
      {
        case 1 :
          {
            CiCRoutine g = (CiCRoutine) f;

            prim.c = g (args[0].p);
          }
          break;
      }
      break;
    case 13 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].p, args[2].p, args[3].p);
          }
          break;
      }
      break;
    case 14 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g ();
          }
          break;
      }
      break;
    case 17 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].i, args[1].p, args[2].p);
          }
          break;
        case 2 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g ();
          }
          break;
        case 3 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].i, args[2].i, args[3].i, 
               args[4].i);
          }
          break;
      }
      break;
    case 18 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].i, args[1].p);
          }
          break;
      }
      break;
    case 19 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g ();
          }
          break;
      }
      break;
    case 21 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p, args[1].p, args[2].p, args[3].i);
          }
          break;
      }
      break;
    case 22 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p);
          }
          break;
      }
      break;
    case 23 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].i, args[1].p);
          }
          break;
        case 2 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p, args[1].p, args[2].p, args[3].p);
          }
          break;
      }
      break;
    case 29 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].i);
          }
          break;
        case 2 :
          {
            CiDRoutine g = (CiDRoutine) f;

            prim.d = g (args[0].p, args[1].d);
          }
          break;
      }
      break;
    case 30 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p, args[2].p, args[3].i, 
               args[4].p, args[5].p);
          }
          break;
      }
      break;
    case 35 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p, args[1].p, args[2].i, args[3].i);
          }
          break;
        case 2 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p, args[2].p);
          }
          break;
        case 3 :
          {
            CiRoutine g = f;

            g (args[0].i);
          }
          break;
      }
      break;
    case 36 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p);
          }
          break;
        case 2 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p, args[1].p, args[2].p);
          }
          break;
      }
      break;
    case 37 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p);
          }
          break;
      }
      break;
  }
  
  args = 0;
  position = 0;
  
  if (retValue) *retValue = prim;
}

#else /*HAS_XM*/
#include <stddef.h>
#endif /*HAS_XM*/
#ifdef HAS_XM
/*--------------------------------------------
  This file has been generated by cigen       
  using the following command :               

  $CIBIN/cigen.exe -p -h X11/Intrinsic.h -f Xm/Xm.h -n CiBindXm -o x.lis

--------------------------------------------*/

#include <X11/Intrinsic.h>
#include <Xm/Xm.h>

#ifndef __CI_SWITCH_DEFS__
#define __CI_SWITCH_DEFS__

#ifdef __cplusplus
#define SWITCH_ELLIPSIS ...
#else
#define SWITCH_ELLIPSIS 

#endif

#ifndef __CiDefs__

typedef void            (*CiRoutine)(SWITCH_ELLIPSIS);
typedef char            (*CiCRoutine)(SWITCH_ELLIPSIS);
typedef short           (*CiSRoutine)(SWITCH_ELLIPSIS);
typedef int             (*CiIRoutine)(SWITCH_ELLIPSIS);
typedef long            (*CiLRoutine)(SWITCH_ELLIPSIS);
typedef unsigned char   (*CiUCRoutine)(SWITCH_ELLIPSIS);
typedef unsigned short  (*CiUSRoutine)(SWITCH_ELLIPSIS);
typedef unsigned int    (*CiUIRoutine)(SWITCH_ELLIPSIS);
typedef unsigned long   (*CiULRoutine)(SWITCH_ELLIPSIS);
typedef float           (*CiFRoutine)(SWITCH_ELLIPSIS);
typedef double          (*CiDRoutine)(SWITCH_ELLIPSIS);
typedef void*           (*CiPRoutine)(SWITCH_ELLIPSIS);

#endif

#ifndef __CiType__

typedef union {
  char c;
  short s;
  int i;
  long l;
  char* p;
  float f;
  double d;
} CiPrimValueRec, *CiPrimValue;

#endif

#endif

#ifdef __cplusplus
extern "C" {
#endif

CiRoutine CiBindXm (char* library);

static void CiBindXmInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew);

static char* CiBindXmSetupFunction (CiRoutine* switchFunction);

static void CiBindXmSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue);
void CiBindXmCleanup ();

static CiRoutine CiBindXmFileCompile       = 0;
static CiRoutine CiBindXmFunctionBind      = 0;
static CiRoutine CiBindXmVariableBind      = 0;
static CiRoutine CiBindXmFunctionSwitchNew = 0;

#ifdef __cplusplus
}
#endif

/*- Procedure ------------------------------------------*/
CiRoutine CiBindXm (char* library)
/*------------------------------------------------------*/
{
  static int first = 1;

  if (first)
    {
      first = 0;
    }
  else if (CiBindXmFunctionSwitchNew)
    {
      CiBindXmFunctionSwitchNew ((CiRoutine) CiBindXmSetupFunction);
    }

  library = 0;

  return ((CiRoutine) CiBindXmInitFunction);
}

/*- Procedure ------------------------------------------*/
static void CiBindXmInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew)
/*------------------------------------------------------*/
{
  CiBindXmFileCompile       = compileFunction;
  pathFunction = 0;
  CiBindXmFunctionBind      = bindFunction;
  CiBindXmVariableBind      = bindVariable;
  CiBindXmFunctionSwitchNew = switchNew;
  CiBindXmVariableBind (0, 0);
  CiBindXmFunctionBind (0, 0);
}

/*- Procedure ------------------------------------------*/
static char* CiBindXmSetupFunction (CiRoutine* switchFunction)
/*------------------------------------------------------*/
{
  static char cases[] = {
    6, 6, 6, 0,
    1, 6, 0,
    0
  };
  static int first = 1;
  
  if (first)
    {
      first = 0;
  
      CiBindXmFileCompile ("X11/Intrinsic.h");
      CiBindXmFileCompile ("Xm/Xm.h");
      CiBindXmFunctionBind ("XmStringFree", (CiRoutine) XmStringFree);
      CiBindXmFunctionBind ("XmStringLtoRCreate", (CiRoutine) XmStringLtoRCreate);
    }
  *switchFunction = (CiRoutine) CiBindXmSwitchFunction;
  return ((char*) cases);
}

/*- Procedure ------------------------------------------*/
static void CiBindXmSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue)
/*------------------------------------------------------*/
{
  CiPrimValueRec prim;
  
  prim.l = 0;
  
  switch (code)
  {
    case 9 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p, args[1].p);
          }
          break;
      }
      break;
    case 37 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p);
          }
          break;
      }
      break;
  }
  
  args = 0;
  position = 0;
  
  if (retValue) *retValue = prim;
}

#else /*HAS_XM*/
#include <stddef.h>
#endif /*HAS_XM*/
