/*--------------------------------------------
  This file has been generated by cigen       
  using the following command :               

  $CIBIN/cigen.exe -p -f HBook.h -n CiBindHBook -o ../gen/HBook_B.c

--------------------------------------------*/

#include <HBook.h>

#ifndef __CI_SWITCH_DEFS__
#define __CI_SWITCH_DEFS__

#ifdef __cplusplus
#define SWITCH_ELLIPSIS ...
#else
#define SWITCH_ELLIPSIS 

#endif

#ifndef __CiDefs__

typedef void            (*CiRoutine)(SWITCH_ELLIPSIS);
typedef char            (*CiCRoutine)(SWITCH_ELLIPSIS);
typedef short           (*CiSRoutine)(SWITCH_ELLIPSIS);
typedef int             (*CiIRoutine)(SWITCH_ELLIPSIS);
typedef long            (*CiLRoutine)(SWITCH_ELLIPSIS);
typedef unsigned char   (*CiUCRoutine)(SWITCH_ELLIPSIS);
typedef unsigned short  (*CiUSRoutine)(SWITCH_ELLIPSIS);
typedef unsigned int    (*CiUIRoutine)(SWITCH_ELLIPSIS);
typedef unsigned long   (*CiULRoutine)(SWITCH_ELLIPSIS);
typedef float           (*CiFRoutine)(SWITCH_ELLIPSIS);
typedef double          (*CiDRoutine)(SWITCH_ELLIPSIS);
typedef void*           (*CiPRoutine)(SWITCH_ELLIPSIS);

#endif

#ifndef __CiType__

typedef union {
  char c;
  short s;
  int i;
  long l;
  char* p;
  float f;
  double d;
} CiPrimValueRec, *CiPrimValue;

#endif

#endif

#ifdef __cplusplus
extern "C" {
#endif

CiRoutine CiBindHBook (char* library);

static void CiBindHBookInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew);

static char* CiBindHBookSetupFunction (CiRoutine* switchFunction);

static void CiBindHBookSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue);
void CiBindHBookCleanup ();

static CiRoutine CiBindHBookFileCompile       = 0;
static CiRoutine CiBindHBookFunctionBind      = 0;
static CiRoutine CiBindHBookVariableBind      = 0;
static CiRoutine CiBindHBookFunctionSwitchNew = 0;

#ifdef __cplusplus
}
#endif

/*- Procedure ------------------------------------------*/
CiRoutine CiBindHBook (char* library)
/*------------------------------------------------------*/
{
  static int first = 1;

  if (first)
    {
      first = 0;
    }
  else if (CiBindHBookFunctionSwitchNew)
    {
      CiBindHBookFunctionSwitchNew ((CiRoutine) CiBindHBookSetupFunction);
    }

  library = 0;

  return ((CiRoutine) CiBindHBookInitFunction);
}

/*- Procedure ------------------------------------------*/
static void CiBindHBookInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew)
/*------------------------------------------------------*/
{
  CiBindHBookFileCompile       = compileFunction;
  pathFunction = 0;
  CiBindHBookFunctionBind      = bindFunction;
  CiBindHBookVariableBind      = bindVariable;
  CiBindHBookFunctionSwitchNew = switchNew;
  CiBindHBookVariableBind (0, 0);
  CiBindHBookFunctionBind (0, 0);
}

/*- Procedure ------------------------------------------*/
static char* CiBindHBookSetupFunction (CiRoutine* switchFunction)
/*------------------------------------------------------*/
{
  static char cases[] = {
    4, 4, 6, 6, 4, 6, 6, 6, 0,
    1, 4, 6, 4, 4, 6, 0,
    6, 6, 4, 6, 6, 0,
    1, 4, 6, 6, 6, 6, 0,
    4, 4, 6, 6, 6, 4, 0,
    4, 4, 6, 6, 6, 6, 0,
    1, 0,
    1, 4, 6, 4, 8, 8, 0,
    1, 4, 6, 0,
    6, 0,
    6, 6, 0,
    1, 4, 6, 4, 8, 8, 4, 8, 8, 0,
    1, 6, 6, 6, 6, 0,
    4, 4, 0,
    1, 4, 6, 4, 8, 8, 8, 8, 0,
    1, 4, 0,
    4, 6, 0,
    1, 4, 6, 6, 6, 6, 6, 6, 6, 0,
    1, 6, 0,
    0
  };
  static int first = 1;
  
  if (first)
    {
      first = 0;
  
      CiBindHBookFileCompile ("HBook.h");
      CiBindHBookFunctionBind ("HBookGetIdentifiers", (CiRoutine) HBookGetIdentifiers);
      CiBindHBookFunctionBind ("HBookGetAttribute", (CiRoutine) HBookGetAttribute);
      CiBindHBookFunctionBind ("HBookGetSubDirectories", (CiRoutine) HBookGetSubDirectories);
      CiBindHBookFunctionBind ("HBookGetDimension", (CiRoutine) HBookGetDimension);
      CiBindHBookFunctionBind ("HBookConstruct", (CiRoutine) HBookConstruct);
      CiBindHBookFunctionBind ("HBookGetEntries", (CiRoutine) HBookGetEntries);
      CiBindHBookFunctionBind ("HBookBringDirectoryInMemory", (CiRoutine) HBookBringDirectoryInMemory);
      CiBindHBookFunctionBind ("HBookSetOption", (CiRoutine) HBookSetOption);
      CiBindHBookFunctionBind ("HBookClearClass", (CiRoutine) HBookClearClass);
      CiBindHBookFunctionBind ("HBookConvert", (CiRoutine) HBookConvert);
      CiBindHBookFunctionBind ("HBookGetDirectoryName", (CiRoutine) HBookGetDirectoryName);
      CiBindHBookFunctionBind ("HBookCreateProfileHistogram", (CiRoutine) HBookCreateProfileHistogram);
      CiBindHBookFunctionBind ("HBookSetAttribute", (CiRoutine) HBookSetAttribute);
      CiBindHBookFunctionBind ("HBookInitialize", (CiRoutine) HBookInitialize);
      CiBindHBookFunctionBind ("HBookGetNextEntry", (CiRoutine) HBookGetNextEntry);
      CiBindHBookFunctionBind ("HBookDoMethod", (CiRoutine) HBookDoMethod);
      CiBindHBookFunctionBind ("HBookGetHistogramInformations", (CiRoutine) HBookGetHistogramInformations);
      CiBindHBookFunctionBind ("HBookBuildIdentifier", (CiRoutine) HBookBuildIdentifier);
      CiBindHBookFunctionBind ("HBookSetUserFunction", (CiRoutine) HBookSetUserFunction);
      CiBindHBookFunctionBind ("HBookDelete", (CiRoutine) HBookDelete);
      CiBindHBookFunctionBind ("HBookCreateTwoDimensionalHistogram", (CiRoutine) HBookCreateTwoDimensionalHistogram);
      CiBindHBookFunctionBind ("HBookGetTupleInformations", (CiRoutine) HBookGetTupleInformations);
      CiBindHBookFunctionBind ("HBookSetDirectory", (CiRoutine) HBookSetDirectory);
      CiBindHBookFunctionBind ("HBookCreateTuple", (CiRoutine) HBookCreateTuple);
      CiBindHBookFunctionBind ("HBookAddConverter", (CiRoutine) HBookAddConverter);
      CiBindHBookFunctionBind ("HBookCreateOneDimensionalHistogram", (CiRoutine) HBookCreateOneDimensionalHistogram);
      CiBindHBookFunctionBind ("HBookSetTitle", (CiRoutine) HBookSetTitle);
    }
  *switchFunction = (CiRoutine) CiBindHBookSwitchFunction;
  return ((char*) cases);
}

/*- Procedure ------------------------------------------*/
static void CiBindHBookSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue)
/*------------------------------------------------------*/
{
  CiPrimValueRec prim;
  
  prim.l = 0;
  
  switch (code)
  {
    case 2 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].i, args[1].p, args[2].p, args[3].i, 
                        args[4].p, args[5].p, args[6].p);
          }
          break;
      }
      break;
    case 3 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].i, args[1].p, args[2].i, args[3].i, 
               args[4].p);
          }
          break;
      }
      break;
    case 5 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p, args[1].i, args[2].p, args[3].p);
          }
          break;
      }
      break;
    case 7 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].i, args[1].p, args[2].p, args[3].p, 
               args[4].p);
          }
          break;
      }
      break;
    case 12 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].i, args[1].p, args[2].p, args[3].p, 
                        args[4].i);
          }
          break;
      }
      break;
    case 14 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].i, args[1].p, args[2].p, args[3].p, 
                        args[4].p);
          }
          break;
        case 2 :
          {
            CiRoutine g = f;

            g ();
          }
          break;
      }
      break;
    case 17 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].i, args[1].p, args[2].i, args[3].d, 
               args[4].d);
          }
          break;
      }
      break;
    case 18 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].i, args[1].p);
          }
          break;
      }
      break;
    case 19 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g ();
          }
          break;
      }
      break;
    case 22 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p);
          }
          break;
      }
      break;
    case 24 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].i, args[1].p, args[2].i, args[3].d, 
               args[4].d, args[5].i, args[6].d, args[7].d);
          }
          break;
      }
      break;
    case 26 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p, args[2].p, args[3].p);
          }
          break;
      }
      break;
    case 34 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].i);
          }
          break;
      }
      break;
    case 35 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].i, args[1].p, args[2].i, args[3].d, 
               args[4].d, args[5].d, args[6].d);
          }
          break;
        case 2 :
          {
            CiRoutine g = f;

            g (args[0].i);
          }
          break;
      }
      break;
    case 36 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p);
          }
          break;
        case 2 :
          {
            CiRoutine g = f;

            g (args[0].i, args[1].p, args[2].p, args[3].p, 
               args[4].p, args[5].p, args[6].p, args[7].p);
          }
          break;
      }
      break;
    case 37 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p);
          }
          break;
      }
      break;
  }
  
  args = 0;
  position = 0;
  
  if (retValue) *retValue = prim;
}

/*--------------------------------------------
  This file has been generated by cigen       
  using the following command :               

  $CIBIN/cigen.exe -p -f HF77.h -n CiBindHF77 -o ../gen/HF77_B.c

--------------------------------------------*/

#include <HF77.h>

#ifndef __CI_SWITCH_DEFS__
#define __CI_SWITCH_DEFS__

#ifdef __cplusplus
#define SWITCH_ELLIPSIS ...
#else
#define SWITCH_ELLIPSIS 

#endif

#ifndef __CiDefs__

typedef void            (*CiRoutine)(SWITCH_ELLIPSIS);
typedef char            (*CiCRoutine)(SWITCH_ELLIPSIS);
typedef short           (*CiSRoutine)(SWITCH_ELLIPSIS);
typedef int             (*CiIRoutine)(SWITCH_ELLIPSIS);
typedef long            (*CiLRoutine)(SWITCH_ELLIPSIS);
typedef unsigned char   (*CiUCRoutine)(SWITCH_ELLIPSIS);
typedef unsigned short  (*CiUSRoutine)(SWITCH_ELLIPSIS);
typedef unsigned int    (*CiUIRoutine)(SWITCH_ELLIPSIS);
typedef unsigned long   (*CiULRoutine)(SWITCH_ELLIPSIS);
typedef float           (*CiFRoutine)(SWITCH_ELLIPSIS);
typedef double          (*CiDRoutine)(SWITCH_ELLIPSIS);
typedef void*           (*CiPRoutine)(SWITCH_ELLIPSIS);

#endif

#ifndef __CiType__

typedef union {
  char c;
  short s;
  int i;
  long l;
  char* p;
  float f;
  double d;
} CiPrimValueRec, *CiPrimValue;

#endif

#endif

#ifdef __cplusplus
extern "C" {
#endif

CiRoutine CiBindHF77 (char* library);

static void CiBindHF77InitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew);

static char* CiBindHF77SetupFunction (CiRoutine* switchFunction);

static void CiBindHF77SwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue);
void CiBindHF77Cleanup ();

static CiRoutine CiBindHF77FileCompile       = 0;
static CiRoutine CiBindHF77FunctionBind      = 0;
static CiRoutine CiBindHF77VariableBind      = 0;
static CiRoutine CiBindHF77FunctionSwitchNew = 0;

#ifdef __cplusplus
}
#endif

/*- Procedure ------------------------------------------*/
CiRoutine CiBindHF77 (char* library)
/*------------------------------------------------------*/
{
  static int first = 1;

  if (first)
    {
      first = 0;
    }
  else if (CiBindHF77FunctionSwitchNew)
    {
      CiBindHF77FunctionSwitchNew ((CiRoutine) CiBindHF77SetupFunction);
    }

  library = 0;

  return ((CiRoutine) CiBindHF77InitFunction);
}

/*- Procedure ------------------------------------------*/
static void CiBindHF77InitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew)
/*------------------------------------------------------*/
{
  CiBindHF77FileCompile       = compileFunction;
  pathFunction = 0;
  CiBindHF77FunctionBind      = bindFunction;
  CiBindHF77VariableBind      = bindVariable;
  CiBindHF77FunctionSwitchNew = switchNew;
  CiBindHF77VariableBind (0, 0);
  CiBindHF77FunctionBind (0, 0);
}

/*- Procedure ------------------------------------------*/
static char* CiBindHF77SetupFunction (CiRoutine* switchFunction)
/*------------------------------------------------------*/
{
  static char cases[] = {
    1, 6, 6, 0,
    1, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0,
    1, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0,
    1, 6, 6, 6, 6, 6, 6, 0,
    4, 6, 6, 6, 6, 6, 6, 0,
    1, 0,
    7, 6, 6, 6, 6, 0,
    1, 6, 6, 6, 6, 6, 0,
    7, 6, 6, 0,
    1, 6, 6, 6, 6, 6, 6, 6, 0,
    4, 6, 6, 6, 0,
    1, 6, 6, 6, 6, 0,
    4, 6, 6, 0,
    7, 6, 6, 6, 0,
    1, 6, 6, 6, 0,
    4, 6, 0,
    1, 6, 0,
    0
  };
  static int first = 1;
  
  if (first)
    {
      first = 0;
  
      CiBindHF77FileCompile ("HF77.h");
      CiBindHF77FunctionBind ("ohidop", (CiRoutine) ohidop);
      CiBindHF77FunctionBind ("ohinit", (CiRoutine) ohinit);
      CiBindHF77FunctionBind ("ohlsr", (CiRoutine) ohlsr);
      CiBindHF77FunctionBind ("ohpwd", (CiRoutine) ohpwd);
      CiBindHF77FunctionBind ("ohisp", (CiRoutine) ohisp);
      CiBindHF77FunctionBind ("hplego", (CiRoutine) hplego);
      CiBindHF77FunctionBind ("ohtit", (CiRoutine) ohtit);
      CiBindHF77FunctionBind ("ohpset", (CiRoutine) ohpset);
      CiBindHF77FunctionBind ("ohmr", (CiRoutine) ohmr);
      CiBindHF77FunctionBind ("hidall", (CiRoutine) hidall);
      CiBindHF77FunctionBind ("oigwid", (CiRoutine) oigwid);
      CiBindHF77FunctionBind ("ohgmap", (CiRoutine) ohgmap);
      CiBindHF77FunctionBind ("ohpzon", (CiRoutine) ohpzon);
      CiBindHF77FunctionBind ("ohpax", (CiRoutine) ohpax);
      CiBindHF77FunctionBind ("ohrout", (CiRoutine) ohrout);
      CiBindHF77FunctionBind ("ohrend", (CiRoutine) ohrend);
      CiBindHF77FunctionBind ("ohlnxt", (CiRoutine) ohlnxt);
      CiBindHF77FunctionBind ("iclwk", (CiRoutine) iclwk);
      CiBindHF77FunctionBind ("iuwk", (CiRoutine) iuwk);
      CiBindHF77FunctionBind ("ohmmap", (CiRoutine) ohmmap);
      CiBindHF77FunctionBind ("oisrat", (CiRoutine) oisrat);
      CiBindHF77FunctionBind ("ohraz", (CiRoutine) ohraz);
      CiBindHF77FunctionBind ("hfitex", (CiRoutine) hfitex);
      CiBindHF77FunctionBind ("hrfile", (CiRoutine) hrfile);
      CiBindHF77FunctionBind ("hexist", (CiRoutine) hexist);
      CiBindHF77FunctionBind ("hie", (CiRoutine) hie);
      CiBindHF77FunctionBind ("hgcont", (CiRoutine) hgcont);
      CiBindHF77FunctionBind ("hij", (CiRoutine) hij);
      CiBindHF77FunctionBind ("hprint", (CiRoutine) hprint);
      CiBindHF77FunctionBind ("ohtype", (CiRoutine) ohtype);
      CiBindHF77FunctionBind ("hix", (CiRoutine) hix);
      CiBindHF77FunctionBind ("ohgunm", (CiRoutine) ohgunm);
      CiBindHF77FunctionBind ("hdelet", (CiRoutine) hdelet);
      CiBindHF77FunctionBind ("ohbk1", (CiRoutine) ohbk1);
      CiBindHF77FunctionBind ("ohbk2", (CiRoutine) ohbk2);
      CiBindHF77FunctionBind ("hnoent", (CiRoutine) hnoent);
      CiBindHF77FunctionBind ("hlimit", (CiRoutine) hlimit);
      CiBindHF77FunctionBind ("ohpopt", (CiRoutine) ohpopt);
      CiBindHF77FunctionBind ("idawk", (CiRoutine) idawk);
      CiBindHF77FunctionBind ("hmaxim", (CiRoutine) hmaxim);
      CiBindHF77FunctionBind ("ohmunm", (CiRoutine) ohmunm);
      CiBindHF77FunctionBind ("ohstat", (CiRoutine) ohstat);
      CiBindHF77FunctionBind ("oiswk", (CiRoutine) oiswk);
      CiBindHF77FunctionBind ("ohbkn", (CiRoutine) ohbkn);
      CiBindHF77FunctionBind ("ohbkp", (CiRoutine) ohbkp);
      CiBindHF77FunctionBind ("hmapg", (CiRoutine) hmapg);
      CiBindHF77FunctionBind ("hmapm", (CiRoutine) hmapm);
      CiBindHF77FunctionBind ("ohptit", (CiRoutine) ohptit);
      CiBindHF77FunctionBind ("hbarx", (CiRoutine) hbarx);
      CiBindHF77FunctionBind ("ohplot", (CiRoutine) ohplot);
      CiBindHF77FunctionBind ("hfn", (CiRoutine) hfn);
      CiBindHF77FunctionBind ("hplgiv", (CiRoutine) hplgiv);
      CiBindHF77FunctionBind ("hfitga", (CiRoutine) hfitga);
      CiBindHF77FunctionBind ("iscr", (CiRoutine) iscr);
      CiBindHF77FunctionBind ("igrsiz", (CiRoutine) igrsiz);
      CiBindHF77FunctionBind ("hrin", (CiRoutine) hrin);
      CiBindHF77FunctionBind ("ohopen", (CiRoutine) ohopen);
      CiBindHF77FunctionBind ("hxi", (CiRoutine) hxi);
      CiBindHF77FunctionBind ("ohgivh", (CiRoutine) ohgivh);
      CiBindHF77FunctionBind ("ohgivn", (CiRoutine) ohgivn);
      CiBindHF77FunctionBind ("hfitpo", (CiRoutine) hfitpo);
      CiBindHF77FunctionBind ("hplnt", (CiRoutine) hplnt);
      CiBindHF77FunctionBind ("iclrwk", (CiRoutine) iclrwk);
      CiBindHF77FunctionBind ("ohgr", (CiRoutine) ohgr);
      CiBindHF77FunctionBind ("iacwk", (CiRoutine) iacwk);
      CiBindHF77FunctionBind ("hminim", (CiRoutine) hminim);
      CiBindHF77FunctionBind ("hi", (CiRoutine) hi);
      CiBindHF77FunctionBind ("ohcd", (CiRoutine) ohcd);
      CiBindHF77FunctionBind ("uctoh", (CiRoutine) uctoh);
      CiBindHF77FunctionBind ("hplint", (CiRoutine) hplint);
      CiBindHF77FunctionBind ("hgn", (CiRoutine) hgn);
      CiBindHF77FunctionBind ("iopwk", (CiRoutine) iopwk);
      CiBindHF77FunctionBind ("hfreeg", (CiRoutine) hfreeg);
      CiBindHF77FunctionBind ("hfreem", (CiRoutine) hfreem);
      CiBindHF77FunctionBind ("hfill", (CiRoutine) hfill);
      CiBindHF77FunctionBind ("ohpsiz", (CiRoutine) ohpsiz);
    }
  *switchFunction = (CiRoutine) CiBindHF77SwitchFunction;
  return ((char*) cases);
}

/*- Procedure ------------------------------------------*/
static void CiBindHF77SwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue)
/*------------------------------------------------------*/
{
  CiPrimValueRec prim;
  
  prim.l = 0;
  
  switch (code)
  {
    case 4 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p);
          }
          break;
        case 2 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p, args[2].p, args[3].p, 
               args[4].p, args[5].p, args[6].p, args[7].p, 
               args[8].p, args[9].p);
          }
          break;
      }
      break;
    case 5 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p, args[2].p, args[3].p, 
               args[4].p, args[5].p, args[6].p, args[7].p, 
               args[8].p);
          }
          break;
      }
      break;
    case 8 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p, args[2].p, args[3].p, 
               args[4].p, args[5].p);
          }
          break;
      }
      break;
    case 11 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].p, args[2].p, args[3].p, 
                        args[4].p, args[5].p);
          }
          break;
      }
      break;
    case 14 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g ();
          }
          break;
      }
      break;
    case 16 :
      switch (position)
      {
        case 1 :
          {
            CiFRoutine g = (CiFRoutine) f;

            prim.f = g (args[0].p, args[1].p, args[2].p, args[3].p);
          }
          break;
      }
      break;
    case 17 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p, args[2].p, args[3].p, 
               args[4].p);
          }
          break;
      }
      break;
    case 18 :
      switch (position)
      {
        case 1 :
          {
            CiFRoutine g = (CiFRoutine) f;

            prim.f = g (args[0].p, args[1].p);
          }
          break;
      }
      break;
    case 23 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p, args[2].p, args[3].p, 
               args[4].p, args[5].p, args[6].p);
          }
          break;
      }
      break;
    case 26 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].p, args[2].p);
          }
          break;
        case 2 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p, args[2].p, args[3].p);
          }
          break;
      }
      break;
    case 31 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].p);
          }
          break;
      }
      break;
    case 33 :
      switch (position)
      {
        case 1 :
          {
            CiFRoutine g = (CiFRoutine) f;

            prim.f = g (args[0].p, args[1].p, args[2].p);
          }
          break;
      }
      break;
    case 35 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p, args[2].p);
          }
          break;
      }
      break;
    case 36 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p);
          }
          break;
      }
      break;
    case 37 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p);
          }
          break;
      }
      break;
  }
  
  args = 0;
  position = 0;
  
  if (retValue) *retValue = prim;
}

/*--------------------------------------------
  This file has been generated by cigen       
  using the following command :               

  $CIBIN/cigen.exe -p -f HFile.h -n CiBindHFile -o ../gen/HFile_B.c

--------------------------------------------*/

#include <HFile.h>

#ifndef __CI_SWITCH_DEFS__
#define __CI_SWITCH_DEFS__

#ifdef __cplusplus
#define SWITCH_ELLIPSIS ...
#else
#define SWITCH_ELLIPSIS 

#endif

#ifndef __CiDefs__

typedef void            (*CiRoutine)(SWITCH_ELLIPSIS);
typedef char            (*CiCRoutine)(SWITCH_ELLIPSIS);
typedef short           (*CiSRoutine)(SWITCH_ELLIPSIS);
typedef int             (*CiIRoutine)(SWITCH_ELLIPSIS);
typedef long            (*CiLRoutine)(SWITCH_ELLIPSIS);
typedef unsigned char   (*CiUCRoutine)(SWITCH_ELLIPSIS);
typedef unsigned short  (*CiUSRoutine)(SWITCH_ELLIPSIS);
typedef unsigned int    (*CiUIRoutine)(SWITCH_ELLIPSIS);
typedef unsigned long   (*CiULRoutine)(SWITCH_ELLIPSIS);
typedef float           (*CiFRoutine)(SWITCH_ELLIPSIS);
typedef double          (*CiDRoutine)(SWITCH_ELLIPSIS);
typedef void*           (*CiPRoutine)(SWITCH_ELLIPSIS);

#endif

#ifndef __CiType__

typedef union {
  char c;
  short s;
  int i;
  long l;
  char* p;
  float f;
  double d;
} CiPrimValueRec, *CiPrimValue;

#endif

#endif

#ifdef __cplusplus
extern "C" {
#endif

CiRoutine CiBindHFile (char* library);

static void CiBindHFileInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew);

static char* CiBindHFileSetupFunction (CiRoutine* switchFunction);

static void CiBindHFileSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue);
void CiBindHFileCleanup ();

static CiRoutine CiBindHFileFileCompile       = 0;
static CiRoutine CiBindHFileFunctionBind      = 0;
static CiRoutine CiBindHFileVariableBind      = 0;
static CiRoutine CiBindHFileFunctionSwitchNew = 0;

#ifdef __cplusplus
}
#endif

/*- Procedure ------------------------------------------*/
CiRoutine CiBindHFile (char* library)
/*------------------------------------------------------*/
{
  static int first = 1;

  if (first)
    {
      first = 0;
    }
  else if (CiBindHFileFunctionSwitchNew)
    {
      CiBindHFileFunctionSwitchNew ((CiRoutine) CiBindHFileSetupFunction);
    }

  library = 0;

  return ((CiRoutine) CiBindHFileInitFunction);
}

/*- Procedure ------------------------------------------*/
static void CiBindHFileInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew)
/*------------------------------------------------------*/
{
  CiBindHFileFileCompile       = compileFunction;
  pathFunction = 0;
  CiBindHFileFunctionBind      = bindFunction;
  CiBindHFileVariableBind      = bindVariable;
  CiBindHFileFunctionSwitchNew = switchNew;
  CiBindHFileVariableBind (0, 0);
  CiBindHFileFunctionBind (0, 0);
}

/*- Procedure ------------------------------------------*/
static char* CiBindHFileSetupFunction (CiRoutine* switchFunction)
/*------------------------------------------------------*/
{
  static char cases[] = {
    6, 6, 6, 0,
    1, 0,
    6, 0,
    4, 6, 6, 6, 4, 6, 6, 6, 0,
    6, 6, 0,
    4, 6, 6, 6, 6, 6, 0,
    4, 6, 6, 0,
    4, 6, 0,
    1, 6, 0,
    0
  };
  static int first = 1;
  
  if (first)
    {
      first = 0;
  
      CiBindHFileFileCompile ("HFile.h");
      CiBindHFileFunctionBind ("HFileGetAttribute", (CiRoutine) HFileGetAttribute);
      CiBindHFileFunctionBind ("HFileGetIdentifiers", (CiRoutine) HFileGetIdentifiers);
      CiBindHFileFunctionBind ("HFileUpdate", (CiRoutine) HFileUpdate);
      CiBindHFileFunctionBind ("HFileClearClass", (CiRoutine) HFileClearClass);
      CiBindHFileFunctionBind ("HFileGetType", (CiRoutine) HFileGetType);
      CiBindHFileFunctionBind ("HFileBringDirectoryInMemory", (CiRoutine) HFileBringDirectoryInMemory);
      CiBindHFileFunctionBind ("HFileDoMethod", (CiRoutine) HFileDoMethod);
      CiBindHFileFunctionBind ("HFileOpenZEBRA_FileForReading", (CiRoutine) HFileOpenZEBRA_FileForReading);
      CiBindHFileFunctionBind ("HFileIsValid", (CiRoutine) HFileIsValid);
      CiBindHFileFunctionBind ("HFileGetIdentifier", (CiRoutine) HFileGetIdentifier);
      CiBindHFileFunctionBind ("HFileGetName", (CiRoutine) HFileGetName);
      CiBindHFileFunctionBind ("HFileDelete", (CiRoutine) HFileDelete);
      CiBindHFileFunctionBind ("HFileSetDirectory", (CiRoutine) HFileSetDirectory);
      CiBindHFileFunctionBind ("HFileMake", (CiRoutine) HFileMake);
      CiBindHFileFunctionBind ("HFileGetFirstIdentifier", (CiRoutine) HFileGetFirstIdentifier);
    }
  *switchFunction = (CiRoutine) CiBindHFileSwitchFunction;
  return ((char*) cases);
}

/*- Procedure ------------------------------------------*/
static void CiBindHFileSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue)
/*------------------------------------------------------*/
{
  CiPrimValueRec prim;
  
  prim.l = 0;
  
  switch (code)
  {
    case 9 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p, args[1].p);
          }
          break;
      }
      break;
    case 14 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g ();
          }
          break;
      }
      break;
    case 19 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g ();
          }
          break;
      }
      break;
    case 20 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].p, args[2].p, args[3].i, 
                        args[4].p, args[5].p, args[6].p);
          }
          break;
      }
      break;
    case 22 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p);
          }
          break;
      }
      break;
    case 24 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].p, args[2].p, args[3].p, 
                        args[4].p);
          }
          break;
      }
      break;
    case 31 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].p);
          }
          break;
      }
      break;
    case 36 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p);
          }
          break;
      }
      break;
    case 37 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p);
          }
          break;
      }
      break;
  }
  
  args = 0;
  position = 0;
  
  if (retValue) *retValue = prim;
}

/*--------------------------------------------
  This file has been generated by cigen       
  using the following command :               

  $CIBIN/cigen.exe -p -f HPlot.h -n CiBindHPlot -o ../gen/HPlot_B.c

--------------------------------------------*/

#include <HPlot.h>

#ifndef __CI_SWITCH_DEFS__
#define __CI_SWITCH_DEFS__

#ifdef __cplusplus
#define SWITCH_ELLIPSIS ...
#else
#define SWITCH_ELLIPSIS 

#endif

#ifndef __CiDefs__

typedef void            (*CiRoutine)(SWITCH_ELLIPSIS);
typedef char            (*CiCRoutine)(SWITCH_ELLIPSIS);
typedef short           (*CiSRoutine)(SWITCH_ELLIPSIS);
typedef int             (*CiIRoutine)(SWITCH_ELLIPSIS);
typedef long            (*CiLRoutine)(SWITCH_ELLIPSIS);
typedef unsigned char   (*CiUCRoutine)(SWITCH_ELLIPSIS);
typedef unsigned short  (*CiUSRoutine)(SWITCH_ELLIPSIS);
typedef unsigned int    (*CiUIRoutine)(SWITCH_ELLIPSIS);
typedef unsigned long   (*CiULRoutine)(SWITCH_ELLIPSIS);
typedef float           (*CiFRoutine)(SWITCH_ELLIPSIS);
typedef double          (*CiDRoutine)(SWITCH_ELLIPSIS);
typedef void*           (*CiPRoutine)(SWITCH_ELLIPSIS);

#endif

#ifndef __CiType__

typedef union {
  char c;
  short s;
  int i;
  long l;
  char* p;
  float f;
  double d;
} CiPrimValueRec, *CiPrimValue;

#endif

#endif

#ifdef __cplusplus
extern "C" {
#endif

CiRoutine CiBindHPlot (char* library);

static void CiBindHPlotInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew);

static char* CiBindHPlotSetupFunction (CiRoutine* switchFunction);

static void CiBindHPlotSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue);
void CiBindHPlotCleanup ();

static CiRoutine CiBindHPlotFileCompile       = 0;
static CiRoutine CiBindHPlotFunctionBind      = 0;
static CiRoutine CiBindHPlotVariableBind      = 0;
static CiRoutine CiBindHPlotFunctionSwitchNew = 0;

#ifdef __cplusplus
}
#endif

/*- Procedure ------------------------------------------*/
CiRoutine CiBindHPlot (char* library)
/*------------------------------------------------------*/
{
  static int first = 1;

  if (first)
    {
      first = 0;
    }
  else if (CiBindHPlotFunctionSwitchNew)
    {
      CiBindHPlotFunctionSwitchNew ((CiRoutine) CiBindHPlotSetupFunction);
    }

  library = 0;

  return ((CiRoutine) CiBindHPlotInitFunction);
}

/*- Procedure ------------------------------------------*/
static void CiBindHPlotInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew)
/*------------------------------------------------------*/
{
  CiBindHPlotFileCompile       = compileFunction;
  pathFunction = 0;
  CiBindHPlotFunctionBind      = bindFunction;
  CiBindHPlotVariableBind      = bindVariable;
  CiBindHPlotFunctionSwitchNew = switchNew;
  CiBindHPlotVariableBind (0, 0);
  CiBindHPlotFunctionBind (0, 0);
}

/*- Procedure ------------------------------------------*/
static char* CiBindHPlotSetupFunction (CiRoutine* switchFunction)
/*------------------------------------------------------*/
{
  static char cases[] = {
    1, 6, 6, 0,
    1, 6, 8, 0,
    1, 4, 4, 4, 6, 0,
    1, 4, 6, 0,
    1, 6, 0,
    0
  };
  static int first = 1;
  
  if (first)
    {
      first = 0;
  
      CiBindHPlotFileCompile ("HPlot.h");
      CiBindHPlotFunctionBind ("HPlotSetOption", (CiRoutine) HPlotSetOption);
      CiBindHPlotFunctionBind ("HPlotSetTitle", (CiRoutine) HPlotSetTitle);
      CiBindHPlotFunctionBind ("HPlotDrawHistogram", (CiRoutine) HPlotDrawHistogram);
      CiBindHPlotFunctionBind ("HPlotSetParameter", (CiRoutine) HPlotSetParameter);
      CiBindHPlotFunctionBind ("HPlotGetPictureSize", (CiRoutine) HPlotGetPictureSize);
      CiBindHPlotFunctionBind ("HPlotSetZones", (CiRoutine) HPlotSetZones);
      CiBindHPlotFunctionBind ("HPlotSetAxesTitle", (CiRoutine) HPlotSetAxesTitle);
    }
  *switchFunction = (CiRoutine) CiBindHPlotSwitchFunction;
  return ((char*) cases);
}

/*- Procedure ------------------------------------------*/
static void CiBindHPlotSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue)
/*------------------------------------------------------*/
{
  CiPrimValueRec prim;
  
  prim.l = 0;
  
  switch (code)
  {
    case 4 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p);
          }
          break;
      }
      break;
    case 6 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].d);
          }
          break;
      }
      break;
    case 12 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].i, args[1].i, args[2].i, args[3].p);
          }
          break;
      }
      break;
    case 18 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].i, args[1].p);
          }
          break;
      }
      break;
    case 37 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p);
          }
          break;
      }
      break;
  }
  
  args = 0;
  position = 0;
  
  if (retValue) *retValue = prim;
}

/*--------------------------------------------
  This file has been generated by cigen       
  using the following command :               

  $CIBIN/cigen.exe -p -f Kuip.h -n CiBindKuip -o ../gen/Kuip_B.c

--------------------------------------------*/

#include <Kuip.h>

#ifndef __CI_SWITCH_DEFS__
#define __CI_SWITCH_DEFS__

#ifdef __cplusplus
#define SWITCH_ELLIPSIS ...
#else
#define SWITCH_ELLIPSIS 

#endif

#ifndef __CiDefs__

typedef void            (*CiRoutine)(SWITCH_ELLIPSIS);
typedef char            (*CiCRoutine)(SWITCH_ELLIPSIS);
typedef short           (*CiSRoutine)(SWITCH_ELLIPSIS);
typedef int             (*CiIRoutine)(SWITCH_ELLIPSIS);
typedef long            (*CiLRoutine)(SWITCH_ELLIPSIS);
typedef unsigned char   (*CiUCRoutine)(SWITCH_ELLIPSIS);
typedef unsigned short  (*CiUSRoutine)(SWITCH_ELLIPSIS);
typedef unsigned int    (*CiUIRoutine)(SWITCH_ELLIPSIS);
typedef unsigned long   (*CiULRoutine)(SWITCH_ELLIPSIS);
typedef float           (*CiFRoutine)(SWITCH_ELLIPSIS);
typedef double          (*CiDRoutine)(SWITCH_ELLIPSIS);
typedef void*           (*CiPRoutine)(SWITCH_ELLIPSIS);

#endif

#ifndef __CiType__

typedef union {
  char c;
  short s;
  int i;
  long l;
  char* p;
  float f;
  double d;
} CiPrimValueRec, *CiPrimValue;

#endif

#endif

#ifdef __cplusplus
extern "C" {
#endif

CiRoutine CiBindKuip (char* library);

static void CiBindKuipInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew);

static char* CiBindKuipSetupFunction (CiRoutine* switchFunction);

static void CiBindKuipSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue);
void CiBindKuipCleanup ();

static CiRoutine CiBindKuipFileCompile       = 0;
static CiRoutine CiBindKuipFunctionBind      = 0;
static CiRoutine CiBindKuipVariableBind      = 0;
static CiRoutine CiBindKuipFunctionSwitchNew = 0;

#ifdef __cplusplus
}
#endif

/*- Procedure ------------------------------------------*/
CiRoutine CiBindKuip (char* library)
/*------------------------------------------------------*/
{
  static int first = 1;

  if (first)
    {
      first = 0;
    }
  else if (CiBindKuipFunctionSwitchNew)
    {
      CiBindKuipFunctionSwitchNew ((CiRoutine) CiBindKuipSetupFunction);
    }

  library = 0;

  return ((CiRoutine) CiBindKuipInitFunction);
}

/*- Procedure ------------------------------------------*/
static void CiBindKuipInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew)
/*------------------------------------------------------*/
{
  CiBindKuipFileCompile       = compileFunction;
  pathFunction = 0;
  CiBindKuipFunctionBind      = bindFunction;
  CiBindKuipVariableBind      = bindVariable;
  CiBindKuipFunctionSwitchNew = switchNew;
  CiBindKuipVariableBind (0, 0);
  CiBindKuipFunctionBind (0, 0);
}

/*- Procedure ------------------------------------------*/
static char* CiBindKuipSetupFunction (CiRoutine* switchFunction)
/*------------------------------------------------------*/
{
  static char cases[] = {
    4, 0,
    6, 0,
    8, 0,
    1, 4, 0,
    4, 6, 0,
    1, 6, 0,
    0
  };
  static int first = 1;
  
  if (first)
    {
      first = 0;
  
      CiBindKuipFileCompile ("Kuip.h");
      CiBindKuipFunctionBind ("okinit", (CiRoutine) okinit);
      CiBindKuipFunctionBind ("KuipInitialize", (CiRoutine) KuipInitialize);
      CiBindKuipFunctionBind ("ku_getc", (CiRoutine) ku_getc);
      CiBindKuipFunctionBind ("okited", (CiRoutine) okited);
      CiBindKuipFunctionBind ("ku_gete", (CiRoutine) ku_gete);
      CiBindKuipFunctionBind ("ku_getf", (CiRoutine) ku_getf);
      CiBindKuipFunctionBind ("ku_geti", (CiRoutine) ku_geti);
      CiBindKuipFunctionBind ("ku_getl", (CiRoutine) ku_getl);
      CiBindKuipFunctionBind ("ku_getr", (CiRoutine) ku_getr);
      CiBindKuipFunctionBind ("ku_gets", (CiRoutine) ku_gets);
      CiBindKuipFunctionBind ("ku_exec", (CiRoutine) ku_exec);
      CiBindKuipFunctionBind ("KuipExecuteScript", (CiRoutine) KuipExecuteScript);
    }
  *switchFunction = (CiRoutine) CiBindKuipSwitchFunction;
  return ((char*) cases);
}

/*- Procedure ------------------------------------------*/
static void CiBindKuipSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue)
/*------------------------------------------------------*/
{
  CiPrimValueRec prim;
  
  prim.l = 0;
  
  switch (code)
  {
    case 17 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g ();
          }
          break;
      }
      break;
    case 19 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g ();
          }
          break;
      }
      break;
    case 21 :
      switch (position)
      {
        case 1 :
          {
            CiDRoutine g = (CiDRoutine) f;

            prim.d = g ();
          }
          break;
      }
      break;
    case 35 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].i);
          }
          break;
      }
      break;
    case 36 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p);
          }
          break;
      }
      break;
    case 37 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p);
          }
          break;
      }
      break;
  }
  
  args = 0;
  position = 0;
  
  if (retValue) *retValue = prim;
}

/*--------------------------------------------
  This file has been generated by cigen       
  using the following command :               

  $CIBIN/cigen.exe -p -h X11/Intrinsic.h -f XzPlotter.h -n CiBindXzPlotter -o ../gen/XzPlotter_B.c

--------------------------------------------*/

#include <X11/Intrinsic.h>
#include <XzPlotter.h>

#ifndef __CI_SWITCH_DEFS__
#define __CI_SWITCH_DEFS__

#ifdef __cplusplus
#define SWITCH_ELLIPSIS ...
#else
#define SWITCH_ELLIPSIS 

#endif

#ifndef __CiDefs__

typedef void            (*CiRoutine)(SWITCH_ELLIPSIS);
typedef char            (*CiCRoutine)(SWITCH_ELLIPSIS);
typedef short           (*CiSRoutine)(SWITCH_ELLIPSIS);
typedef int             (*CiIRoutine)(SWITCH_ELLIPSIS);
typedef long            (*CiLRoutine)(SWITCH_ELLIPSIS);
typedef unsigned char   (*CiUCRoutine)(SWITCH_ELLIPSIS);
typedef unsigned short  (*CiUSRoutine)(SWITCH_ELLIPSIS);
typedef unsigned int    (*CiUIRoutine)(SWITCH_ELLIPSIS);
typedef unsigned long   (*CiULRoutine)(SWITCH_ELLIPSIS);
typedef float           (*CiFRoutine)(SWITCH_ELLIPSIS);
typedef double          (*CiDRoutine)(SWITCH_ELLIPSIS);
typedef void*           (*CiPRoutine)(SWITCH_ELLIPSIS);

#endif

#ifndef __CiType__

typedef union {
  char c;
  short s;
  int i;
  long l;
  char* p;
  float f;
  double d;
} CiPrimValueRec, *CiPrimValue;

#endif

#endif

#ifdef __cplusplus
extern "C" {
#endif

CiRoutine CiBindXzPlotter (char* library);

static void CiBindXzPlotterInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew);

static char* CiBindXzPlotterSetupFunction (CiRoutine* switchFunction);

static void CiBindXzPlotterSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue);
void CiBindXzPlotterCleanup ();

static CiRoutine CiBindXzPlotterFileCompile       = 0;
static CiRoutine CiBindXzPlotterFunctionBind      = 0;
static CiRoutine CiBindXzPlotterVariableBind      = 0;
static CiRoutine CiBindXzPlotterFunctionSwitchNew = 0;

#ifdef __cplusplus
}
#endif

/*- Procedure ------------------------------------------*/
CiRoutine CiBindXzPlotter (char* library)
/*------------------------------------------------------*/
{
  static int first = 1;

  if (first)
    {
      first = 0;
    }
  else if (CiBindXzPlotterFunctionSwitchNew)
    {
      CiBindXzPlotterFunctionSwitchNew ((CiRoutine) CiBindXzPlotterSetupFunction);
    }

  library = 0;

  return ((CiRoutine) CiBindXzPlotterInitFunction);
}

/*- Procedure ------------------------------------------*/
static void CiBindXzPlotterInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew)
/*------------------------------------------------------*/
{
  CiBindXzPlotterFileCompile       = compileFunction;
  pathFunction = 0;
  CiBindXzPlotterFunctionBind      = bindFunction;
  CiBindXzPlotterVariableBind      = bindVariable;
  CiBindXzPlotterFunctionSwitchNew = switchNew;
  CiBindXzPlotterVariableBind (0, 0);
  CiBindXzPlotterFunctionBind (0, 0);
}

/*- Procedure ------------------------------------------*/
static char* CiBindXzPlotterSetupFunction (CiRoutine* switchFunction)
/*------------------------------------------------------*/
{
  static char cases[] = {
    1, 6, 4, 0,
    1, 6, 6, 0,
    1, 0,
    1, 6, 4, 4, 4, 6, 0,
    1, 6, 4, 4, 4, 0,
    6, 6, 0,
    1, 6, 4, 8, 8, 0,
    1, 6, 0,
    1, 6, 6, 8, 0,
    0
  };
  static int first = 1;
  
  if (first)
    {
      first = 0;
  
      CiBindXzPlotterFileCompile ("X11/Intrinsic.h");
      CiBindXzPlotterFileCompile ("XzPlotter.h");
      CiBindXzPlotterFunctionBind ("XzPlotterClear", (CiRoutine) XzPlotterClear);
      CiBindXzPlotterFunctionBind ("XzPlotterClearClass", (CiRoutine) XzPlotterClearClass);
      CiBindXzPlotterVariableBind ("xzPlotterWidgetClass", &xzPlotterWidgetClass);
      CiBindXzPlotterFunctionBind ("XzPlotterDrawManhattanPlot", (CiRoutine) XzPlotterDrawManhattanPlot);
      CiBindXzPlotterFunctionBind ("XzPlotterGetCollectedBinsInformations", (CiRoutine) XzPlotterGetCollectedBinsInformations);
      CiBindXzPlotterFunctionBind ("XzPlotterDrawTuple", (CiRoutine) XzPlotterDrawTuple);
      CiBindXzPlotterFunctionBind ("XzPlotterSetPageTitle", (CiRoutine) XzPlotterSetPageTitle);
      CiBindXzPlotterFunctionBind ("XzPlotterSetZones", (CiRoutine) XzPlotterSetZones);
      CiBindXzPlotterFunctionBind ("XzPlotterAddCommand", (CiRoutine) XzPlotterAddCommand);
      CiBindXzPlotterFunctionBind ("XzPlotterSetParameter", (CiRoutine) XzPlotterSetParameter);
      CiBindXzPlotterFunctionBind ("XzPlotterDrawHistogram", (CiRoutine) XzPlotterDrawHistogram);
      CiBindXzPlotterFunctionBind ("XzPlotterSetTitle", (CiRoutine) XzPlotterSetTitle);
      CiBindXzPlotterFunctionBind ("XzPlotterSetOption", (CiRoutine) XzPlotterSetOption);
    }
  *switchFunction = (CiRoutine) CiBindXzPlotterSwitchFunction;
  return ((char*) cases);
}

/*- Procedure ------------------------------------------*/
static void CiBindXzPlotterSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue)
/*------------------------------------------------------*/
{
  CiPrimValueRec prim;
  
  prim.l = 0;
  
  switch (code)
  {
    case 2 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].i);
          }
          break;
      }
      break;
    case 4 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p);
          }
          break;
      }
      break;
    case 14 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g ();
          }
          break;
      }
      break;
    case 19 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].i, args[2].i, args[3].i, 
               args[4].p);
          }
          break;
      }
      break;
    case 20 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].i, args[2].i, args[3].i);
          }
          break;
      }
      break;
    case 22 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p);
          }
          break;
      }
      break;
    case 36 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].i, args[2].d, args[3].d);
          }
          break;
      }
      break;
    case 37 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p);
          }
          break;
        case 2 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p, args[2].d);
          }
          break;
      }
      break;
  }
  
  args = 0;
  position = 0;
  
  if (retValue) *retValue = prim;
}

/*--------------------------------------------
  This file has been generated by cigen       
  using the following command :               

  $CIBIN/cigen.exe -p -f XzTypes.h -n CiBindXzTypes -o ../gen/XzTypes_B.c

--------------------------------------------*/

#include <XzTypes.h>

#ifndef __CI_SWITCH_DEFS__
#define __CI_SWITCH_DEFS__

#ifdef __cplusplus
#define SWITCH_ELLIPSIS ...
#else
#define SWITCH_ELLIPSIS 

#endif

#ifndef __CiDefs__

typedef void            (*CiRoutine)(SWITCH_ELLIPSIS);
typedef char            (*CiCRoutine)(SWITCH_ELLIPSIS);
typedef short           (*CiSRoutine)(SWITCH_ELLIPSIS);
typedef int             (*CiIRoutine)(SWITCH_ELLIPSIS);
typedef long            (*CiLRoutine)(SWITCH_ELLIPSIS);
typedef unsigned char   (*CiUCRoutine)(SWITCH_ELLIPSIS);
typedef unsigned short  (*CiUSRoutine)(SWITCH_ELLIPSIS);
typedef unsigned int    (*CiUIRoutine)(SWITCH_ELLIPSIS);
typedef unsigned long   (*CiULRoutine)(SWITCH_ELLIPSIS);
typedef float           (*CiFRoutine)(SWITCH_ELLIPSIS);
typedef double          (*CiDRoutine)(SWITCH_ELLIPSIS);
typedef void*           (*CiPRoutine)(SWITCH_ELLIPSIS);

#endif

#ifndef __CiType__

typedef union {
  char c;
  short s;
  int i;
  long l;
  char* p;
  float f;
  double d;
} CiPrimValueRec, *CiPrimValue;

#endif

#endif

#ifdef __cplusplus
extern "C" {
#endif

CiRoutine CiBindXzTypes (char* library);

static void CiBindXzTypesInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew);

static char* CiBindXzTypesSetupFunction (CiRoutine* switchFunction);

static void CiBindXzTypesSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue);
void CiBindXzTypesCleanup ();

static CiRoutine CiBindXzTypesFileCompile       = 0;
static CiRoutine CiBindXzTypesFunctionBind      = 0;
static CiRoutine CiBindXzTypesVariableBind      = 0;
static CiRoutine CiBindXzTypesFunctionSwitchNew = 0;

#ifdef __cplusplus
}
#endif

/*- Procedure ------------------------------------------*/
CiRoutine CiBindXzTypes (char* library)
/*------------------------------------------------------*/
{
  static int first = 1;

  if (first)
    {
      first = 0;
    }
  else if (CiBindXzTypesFunctionSwitchNew)
    {
      CiBindXzTypesFunctionSwitchNew ((CiRoutine) CiBindXzTypesSetupFunction);
    }

  library = 0;

  return ((CiRoutine) CiBindXzTypesInitFunction);
}

/*- Procedure ------------------------------------------*/
static void CiBindXzTypesInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew)
/*------------------------------------------------------*/
{
  CiBindXzTypesFileCompile       = compileFunction;
  pathFunction = 0;
  CiBindXzTypesFunctionBind      = bindFunction;
  CiBindXzTypesVariableBind      = bindVariable;
  CiBindXzTypesFunctionSwitchNew = switchNew;
  CiBindXzTypesVariableBind (0, 0);
  CiBindXzTypesFunctionBind (0, 0);
}

/*- Procedure ------------------------------------------*/
static char* CiBindXzTypesSetupFunction (CiRoutine* switchFunction)
/*------------------------------------------------------*/
{
  static char cases[] = {
    1, 0,
    0
  };
  static int first = 1;
  
  if (first)
    {
      first = 0;
  
      CiBindXzTypesFileCompile ("XzTypes.h");
      CiBindXzTypesFunctionBind ("XzSetTypes", (CiRoutine) XzSetTypes);
    }
  *switchFunction = (CiRoutine) CiBindXzTypesSwitchFunction;
  return ((char*) cases);
}

/*- Procedure ------------------------------------------*/
static void CiBindXzTypesSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue)
/*------------------------------------------------------*/
{
  CiPrimValueRec prim;
  
  prim.l = 0;
  
  switch (code)
  {
    case 14 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g ();
          }
          break;
      }
      break;
  }
  
  args = 0;
  position = 0;
  
  if (retValue) *retValue = prim;
}

