/*--------------------------------------------
  This file has been generated by cigen       
  using the following command :               

  $CIBIN/cigen.exe -p -h stdarg.h -h X11/Xlib.h -h X11/Xresource.h -f XDisplay.h -n CiBindXDisplay -o ../gen/XDisplay_B.c

--------------------------------------------*/

#include <stdarg.h>
#include <X11/Xlib.h>
#include <X11/Xresource.h>
#include <XDisplay.h>

#ifndef __CI_SWITCH_DEFS__
#define __CI_SWITCH_DEFS__

#ifdef __cplusplus
#define SWITCH_ELLIPSIS ...
#else
#define SWITCH_ELLIPSIS 

#endif

#ifndef __CiDefs__

typedef void            (*CiRoutine)(SWITCH_ELLIPSIS);
typedef char            (*CiCRoutine)(SWITCH_ELLIPSIS);
typedef short           (*CiSRoutine)(SWITCH_ELLIPSIS);
typedef int             (*CiIRoutine)(SWITCH_ELLIPSIS);
typedef long            (*CiLRoutine)(SWITCH_ELLIPSIS);
typedef unsigned char   (*CiUCRoutine)(SWITCH_ELLIPSIS);
typedef unsigned short  (*CiUSRoutine)(SWITCH_ELLIPSIS);
typedef unsigned int    (*CiUIRoutine)(SWITCH_ELLIPSIS);
typedef unsigned long   (*CiULRoutine)(SWITCH_ELLIPSIS);
typedef float           (*CiFRoutine)(SWITCH_ELLIPSIS);
typedef double          (*CiDRoutine)(SWITCH_ELLIPSIS);
typedef void*           (*CiPRoutine)(SWITCH_ELLIPSIS);

#endif

#ifndef __CiType__

typedef union {
  char c;
  short s;
  int i;
  long l;
  char* p;
  float f;
  double d;
} CiPrimValueRec, *CiPrimValue;

#endif

#endif

#ifdef __cplusplus
extern "C" {
#endif

CiRoutine CiBindXDisplay (char* library);

static void CiBindXDisplayInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew);

static char* CiBindXDisplaySetupFunction (CiRoutine* switchFunction);

static void CiBindXDisplaySwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue);
void CiBindXDisplayCleanup ();

static CiRoutine CiBindXDisplayFileCompile       = 0;
static CiRoutine CiBindXDisplayFunctionBind      = 0;
static CiRoutine CiBindXDisplayVariableBind      = 0;
static CiRoutine CiBindXDisplayFunctionSwitchNew = 0;

#ifdef __cplusplus
}
#endif

/*- Procedure ------------------------------------------*/
CiRoutine CiBindXDisplay (char* library)
/*------------------------------------------------------*/
{
  static int first = 1;

  if (first)
    {
      first = 0;
    }
  else if (CiBindXDisplayFunctionSwitchNew)
    {
      CiBindXDisplayFunctionSwitchNew ((CiRoutine) CiBindXDisplaySetupFunction);
    }

  library = 0;

  return ((CiRoutine) CiBindXDisplayInitFunction);
}

/*- Procedure ------------------------------------------*/
static void CiBindXDisplayInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew)
/*------------------------------------------------------*/
{
  CiBindXDisplayFileCompile       = compileFunction;
  pathFunction = 0;
  CiBindXDisplayFunctionBind      = bindFunction;
  CiBindXDisplayVariableBind      = bindVariable;
  CiBindXDisplayFunctionSwitchNew = switchNew;
  CiBindXDisplayVariableBind (0, 0);
  CiBindXDisplayFunctionBind (0, 0);
}

/*- Procedure ------------------------------------------*/
static char* CiBindXDisplaySetupFunction (CiRoutine* switchFunction)
/*------------------------------------------------------*/
{
  static char cases[] = {
    5, 6, 6, 0,
    4, 6, 4, 6, 0,
    1, 6, 4, 0,
    1, 6, 5, 5, 4, 0,
    1, 6, 5, 0,
    5, 6, 5, 4, 4, 4, 4, 0,
    1, 6, 6, 0,
    6, 6, 5, 0,
    1, 6, 6, 6, 6, 6, 6, 0,
    5, 6, 0,
    4, 6, 8, 8, 8, 6, 6, 0,
    6, 6, 6, 0,
    1, 6, 4, 6, 0,
    5, 6, 4, 4, 0,
    1, 0,
    1, 6, 6, 6, 6, 6, 0,
    1, 6, 5, 6, 6, 0,
    1, 6, 5, 6, 6, 6, 0,
    1, 6, 4, 4, 5, 0,
    6, 6, 0,
    1, 6, 5, 5, 4, 6, 0,
    5, 6, 5, 5, 0,
    1, 6, 6, 6, 5, 0,
    1, 6, 6, 6, 6, 0,
    6, 6, 8, 8, 8, 0,
    4, 6, 5, 0,
    4, 6, 5, 5, 5, 0,
    4, 6, 6, 0,
    6, 6, 6, 4, 0,
    1, 6, 6, 6, 0,
    4, 6, 0,
    1, 6, 0,
    5, 6, 5, 0,
    0
  };
  static int first = 1;
  
  if (first)
    {
      first = 0;
  
      CiBindXDisplayFileCompile ("stdarg.h");
      CiBindXDisplayFileCompile ("X11/Xlib.h");
      CiBindXDisplayFileCompile ("X11/Xresource.h");
      CiBindXDisplayFileCompile ("XDisplay.h");
      CiBindXDisplayFunctionBind ("XImageDestroy", (CiRoutine) XImageDestroy);
      CiBindXDisplayFunctionBind ("XImageDelete", (CiRoutine) XImageDelete);
      CiBindXDisplayFunctionBind ("XDisplayDumpResource", (CiRoutine) XDisplayDumpResource);
      CiBindXDisplayFunctionBind ("XDisplayGetBlackPixel", (CiRoutine) XDisplayGetBlackPixel);
      CiBindXDisplayFunctionBind ("XDisplayGetPixmapImage", (CiRoutine) XDisplayGetPixmapImage);
      CiBindXDisplayFunctionBind ("XDisplayGetRubberGC", (CiRoutine) XDisplayGetRubberGC);
      CiBindXDisplayFunctionBind ("XDisplayLoadPixmapFile", (CiRoutine) XDisplayLoadPixmapFile);
      CiBindXDisplayFunctionBind ("XDisplayPutFileInResourceDatabase", (CiRoutine) XDisplayPutFileInResourceDatabase);
      CiBindXDisplayFunctionBind ("XDisplayConvertColorNameToRGB", (CiRoutine) XDisplayConvertColorNameToRGB);
      CiBindXDisplayFunctionBind ("XDisplayGetSize", (CiRoutine) XDisplayGetSize);
      CiBindXDisplayFunctionBind ("XImageAddPixel", (CiRoutine) XImageAddPixel);
      CiBindXDisplayFunctionBind ("XDisplayGetPixelFromRGB", (CiRoutine) XDisplayGetPixelFromRGB);
      CiBindXDisplayFunctionBind ("XImageGetBytes", (CiRoutine) XImageGetBytes);
      CiBindXDisplayFunctionBind ("XDisplayPutPixmapInRootWindow", (CiRoutine) XDisplayPutPixmapInRootWindow);
      CiBindXDisplayFunctionBind ("XDisplayGetBitsPerPixel", (CiRoutine) XDisplayGetBitsPerPixel);
      CiBindXDisplayFunctionBind ("XDisplayDrawRectangle", (CiRoutine) XDisplayDrawRectangle);
      CiBindXDisplayFunctionBind ("XDisplayIconifyWindow", (CiRoutine) XDisplayIconifyWindow);
      CiBindXDisplayFunctionBind ("XDisplayGetRGBsOfColorNames", (CiRoutine) XDisplayGetRGBsOfColorNames);
      CiBindXDisplayFunctionBind ("XDisplayGetDrawableDepth", (CiRoutine) XDisplayGetDrawableDepth);
      CiBindXDisplayFunctionBind ("XImageConvolute", (CiRoutine) XImageConvolute);
      CiBindXDisplayFunctionBind ("XStringGetMask", (CiRoutine) XStringGetMask);
      CiBindXDisplayFunctionBind ("XDisplayGetPixelRGB", (CiRoutine) XDisplayGetPixelRGB);
      CiBindXDisplayFunctionBind ("XImageGetSize", (CiRoutine) XImageGetSize);
      CiBindXDisplayFunctionBind ("XDisplayRingBell", (CiRoutine) XDisplayRingBell);
      CiBindXDisplayFunctionBind ("XDisplayExpandImage", (CiRoutine) XDisplayExpandImage);
      CiBindXDisplayFunctionBind ("XDisplayPutPixmapInPS_Stream", (CiRoutine) XDisplayPutPixmapInPS_Stream);
      CiBindXDisplayFunctionBind ("XDisplayPutImageInPS_Stream", (CiRoutine) XDisplayPutImageInPS_Stream);
      CiBindXDisplayFunctionBind ("XDisplaySetWindowShapeE", (CiRoutine) XDisplaySetWindowShapeE);
      CiBindXDisplayFunctionBind ("XDisplayClearClass", (CiRoutine) XDisplayClearClass);
      CiBindXDisplayFunctionBind ("XDisplayConvertPixelToColorName", (CiRoutine) XDisplayConvertPixelToColorName);
      CiBindXDisplayFunctionBind ("XDisplaySetWindowShapeV", (CiRoutine) XDisplaySetWindowShapeV);
      CiBindXDisplayFunctionBind ("XDisplayDumpScreen", (CiRoutine) XDisplayDumpScreen);
      CiBindXDisplayFunctionBind ("XDisplayGetImageColormap", (CiRoutine) XDisplayGetImageColormap);
      CiBindXDisplayFunctionBind ("XDisplaySendMessage", (CiRoutine) XDisplaySendMessage);
      CiBindXDisplayFunctionBind ("XImagePutPixel", (CiRoutine) XImagePutPixel);
      CiBindXDisplayFunctionBind ("XDisplayConvertPixmapToBitmap", (CiRoutine) XDisplayConvertPixmapToBitmap);
      CiBindXDisplayFunctionBind ("XDisplaySynchronize", (CiRoutine) XDisplaySynchronize);
      CiBindXDisplayFunctionBind ("XDisplaySetWindowToNormalState", (CiRoutine) XDisplaySetWindowToNormalState);
      CiBindXDisplayFunctionBind ("XDisplayGetDepth", (CiRoutine) XDisplayGetDepth);
      CiBindXDisplayFunctionBind ("XDisplayGetDrawablePixmap", (CiRoutine) XDisplayGetDrawablePixmap);
      CiBindXDisplayFunctionBind ("XColorGetRGB", (CiRoutine) XColorGetRGB);
      CiBindXDisplayFunctionBind ("XDisplayConvertRGB_ToColorName", (CiRoutine) XDisplayConvertRGB_ToColorName);
      CiBindXDisplayFunctionBind ("XDisplayPutImageInGIF_Stream", (CiRoutine) XDisplayPutImageInGIF_Stream);
      CiBindXDisplayFunctionBind ("XImagePutBitmapInXBM_Stream", (CiRoutine) XImagePutBitmapInXBM_Stream);
      CiBindXDisplayFunctionBind ("XDisplayAdaptImageToScreen", (CiRoutine) XDisplayAdaptImageToScreen);
      CiBindXDisplayFunctionBind ("XImageGetPixel", (CiRoutine) XImageGetPixel);
      CiBindXDisplayFunctionBind ("XDisplayGetDrawableSize", (CiRoutine) XDisplayGetDrawableSize);
      CiBindXDisplayFunctionBind ("XDisplayGetWhitePixel", (CiRoutine) XDisplayGetWhitePixel);
      CiBindXDisplayFunctionBind ("XDisplayCompressImage", (CiRoutine) XDisplayCompressImage);
      CiBindXDisplayFunctionBind ("XDisplayFreePixels", (CiRoutine) XDisplayFreePixels);
      CiBindXDisplayFunctionBind ("XDisplayGetWindowPixmap", (CiRoutine) XDisplayGetWindowPixmap);
      CiBindXDisplayFunctionBind ("XDisplayPutStringInResourceDatabase", (CiRoutine) XDisplayPutStringInResourceDatabase);
      CiBindXDisplayFunctionBind ("XDisplayHasExtension", (CiRoutine) XDisplayHasExtension);
    }
  *switchFunction = (CiRoutine) CiBindXDisplaySwitchFunction;
  return ((char*) cases);
}

/*- Procedure ------------------------------------------*/
static void CiBindXDisplaySwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue)
/*------------------------------------------------------*/
{
  CiPrimValueRec prim;
  
  prim.l = 0;
  
  switch (code)
  {
    case 0 :
      switch (position)
      {
        case 1 :
          {
            CiLRoutine g = (CiLRoutine) f;

            prim.l = g (args[0].p, args[1].p);
          }
          break;
        case 2 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].i, args[2].p);
          }
          break;
      }
      break;
    case 2 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].i);
          }
          break;
        case 2 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].l, args[2].l, args[3].i);
          }
          break;
      }
      break;
    case 3 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].l);
          }
          break;
        case 2 :
          {
            CiLRoutine g = (CiLRoutine) f;

            prim.l = g (args[0].p, args[1].l, args[2].i, args[3].i, 
                        args[4].i, args[5].i);
          }
          break;
      }
      break;
    case 4 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p);
          }
          break;
      }
      break;
    case 8 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p, args[1].l);
          }
          break;
        case 2 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p, args[2].p, args[3].p, 
               args[4].p, args[5].p);
          }
          break;
      }
      break;
    case 9 :
      switch (position)
      {
        case 1 :
          {
            CiLRoutine g = (CiLRoutine) f;

            prim.l = g (args[0].p);
          }
          break;
        case 2 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].d, args[2].d, args[3].d, 
                        args[4].p, args[5].p);
          }
          break;
        case 3 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p, args[1].p);
          }
          break;
        case 4 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].i, args[2].p);
          }
          break;
      }
      break;
    case 11 :
      switch (position)
      {
        case 1 :
          {
            CiLRoutine g = (CiLRoutine) f;

            prim.l = g (args[0].p, args[1].i, args[2].i);
          }
          break;
      }
      break;
    case 14 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g ();
          }
          break;
      }
      break;
    case 17 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p, args[2].p, args[3].p, 
               args[4].p);
          }
          break;
        case 2 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].l, args[2].p, args[3].p);
          }
          break;
      }
      break;
    case 20 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].l, args[2].p, args[3].p, 
               args[4].p);
          }
          break;
      }
      break;
    case 21 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].i, args[2].i, args[3].l);
          }
          break;
      }
      break;
    case 22 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p);
          }
          break;
      }
      break;
    case 25 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].l, args[2].l, args[3].i, 
               args[4].p);
          }
          break;
        case 2 :
          {
            CiLRoutine g = (CiLRoutine) f;

            prim.l = g (args[0].p, args[1].l, args[2].l);
          }
          break;
        case 3 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p, args[2].p, args[3].l);
          }
          break;
      }
      break;
    case 26 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p, args[2].p, args[3].p);
          }
          break;
      }
      break;
    case 29 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p, args[1].d, args[2].d, args[3].d);
          }
          break;
      }
      break;
    case 30 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].l);
          }
          break;
        case 2 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].l, args[2].l, args[3].l);
          }
          break;
      }
      break;
    case 31 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].p);
          }
          break;
      }
      break;
    case 34 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p, args[1].p, args[2].i);
          }
          break;
      }
      break;
    case 35 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p, args[2].p);
          }
          break;
      }
      break;
    case 36 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p);
          }
          break;
      }
      break;
    case 37 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p);
          }
          break;
      }
      break;
    case 39 :
      switch (position)
      {
        case 1 :
          {
            CiLRoutine g = (CiLRoutine) f;

            prim.l = g (args[0].p, args[1].l);
          }
          break;
      }
      break;
  }
  
  args = 0;
  position = 0;
  
  if (retValue) *retValue = prim;
}

/*--------------------------------------------
  This file has been generated by cigen       
  using the following command :               

  $CIBIN/cigen.exe -p -h X11/Xlib.h -f XMailbox.h -n CiBindXMailbox -o ../gen/XMailbox_B.c

--------------------------------------------*/

#include <X11/Xlib.h>
#include <XMailbox.h>

#ifndef __CI_SWITCH_DEFS__
#define __CI_SWITCH_DEFS__

#ifdef __cplusplus
#define SWITCH_ELLIPSIS ...
#else
#define SWITCH_ELLIPSIS 

#endif

#ifndef __CiDefs__

typedef void            (*CiRoutine)(SWITCH_ELLIPSIS);
typedef char            (*CiCRoutine)(SWITCH_ELLIPSIS);
typedef short           (*CiSRoutine)(SWITCH_ELLIPSIS);
typedef int             (*CiIRoutine)(SWITCH_ELLIPSIS);
typedef long            (*CiLRoutine)(SWITCH_ELLIPSIS);
typedef unsigned char   (*CiUCRoutine)(SWITCH_ELLIPSIS);
typedef unsigned short  (*CiUSRoutine)(SWITCH_ELLIPSIS);
typedef unsigned int    (*CiUIRoutine)(SWITCH_ELLIPSIS);
typedef unsigned long   (*CiULRoutine)(SWITCH_ELLIPSIS);
typedef float           (*CiFRoutine)(SWITCH_ELLIPSIS);
typedef double          (*CiDRoutine)(SWITCH_ELLIPSIS);
typedef void*           (*CiPRoutine)(SWITCH_ELLIPSIS);

#endif

#ifndef __CiType__

typedef union {
  char c;
  short s;
  int i;
  long l;
  char* p;
  float f;
  double d;
} CiPrimValueRec, *CiPrimValue;

#endif

#endif

#ifdef __cplusplus
extern "C" {
#endif

CiRoutine CiBindXMailbox (char* library);

static void CiBindXMailboxInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew);

static char* CiBindXMailboxSetupFunction (CiRoutine* switchFunction);

static void CiBindXMailboxSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue);
void CiBindXMailboxCleanup ();

static CiRoutine CiBindXMailboxFileCompile       = 0;
static CiRoutine CiBindXMailboxFunctionBind      = 0;
static CiRoutine CiBindXMailboxVariableBind      = 0;
static CiRoutine CiBindXMailboxFunctionSwitchNew = 0;

#ifdef __cplusplus
}
#endif

/*- Procedure ------------------------------------------*/
CiRoutine CiBindXMailbox (char* library)
/*------------------------------------------------------*/
{
  static int first = 1;

  if (first)
    {
      first = 0;
    }
  else if (CiBindXMailboxFunctionSwitchNew)
    {
      CiBindXMailboxFunctionSwitchNew ((CiRoutine) CiBindXMailboxSetupFunction);
    }

  library = 0;

  return ((CiRoutine) CiBindXMailboxInitFunction);
}

/*- Procedure ------------------------------------------*/
static void CiBindXMailboxInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew)
/*------------------------------------------------------*/
{
  CiBindXMailboxFileCompile       = compileFunction;
  pathFunction = 0;
  CiBindXMailboxFunctionBind      = bindFunction;
  CiBindXMailboxVariableBind      = bindVariable;
  CiBindXMailboxFunctionSwitchNew = switchNew;
  CiBindXMailboxVariableBind (0, 0);
  CiBindXMailboxFunctionBind (0, 0);
}

/*- Procedure ------------------------------------------*/
static char* CiBindXMailboxSetupFunction (CiRoutine* switchFunction)
/*------------------------------------------------------*/
{
  static char cases[] = {
    5, 6, 6, 0,
    6, 6, 6, 0,
    1, 0,
    4, 5, 6, 4, 0,
    4, 5, 6, 0,
    6, 0,
    0
  };
  static int first = 1;
  
  if (first)
    {
      first = 0;
  
      CiBindXMailboxFileCompile ("X11/Xlib.h");
      CiBindXMailboxFileCompile ("XMailbox.h");
      CiBindXMailboxFunctionBind ("XMailboxClearClass", (CiRoutine) XMailboxClearClass);
      CiBindXMailboxFunctionBind ("XMailboxGetIdentifier", (CiRoutine) XMailboxGetIdentifier);
      CiBindXMailboxFunctionBind ("XMailboxSendMessage", (CiRoutine) XMailboxSendMessage);
      CiBindXMailboxFunctionBind ("XMailboxGetMessage", (CiRoutine) XMailboxGetMessage);
      CiBindXMailboxFunctionBind ("XMailboxWaitMessage", (CiRoutine) XMailboxWaitMessage);
      CiBindXMailboxFunctionBind ("XMailboxGetDisplay", (CiRoutine) XMailboxGetDisplay);
      CiBindXMailboxFunctionBind ("XMailboxCreate", (CiRoutine) XMailboxCreate);
      CiBindXMailboxFunctionBind ("XMailboxSendString", (CiRoutine) XMailboxSendString);
    }
  *switchFunction = (CiRoutine) CiBindXMailboxSwitchFunction;
  return ((char*) cases);
}

/*- Procedure ------------------------------------------*/
static void CiBindXMailboxSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue)
/*------------------------------------------------------*/
{
  CiPrimValueRec prim;
  
  prim.l = 0;
  
  switch (code)
  {
    case 0 :
      switch (position)
      {
        case 1 :
          {
            CiLRoutine g = (CiLRoutine) f;

            prim.l = g (args[0].p, args[1].p);
          }
          break;
      }
      break;
    case 9 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p, args[1].p);
          }
          break;
      }
      break;
    case 14 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g ();
          }
          break;
      }
      break;
    case 15 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].l, args[1].p, args[2].i);
          }
          break;
      }
      break;
    case 18 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].l, args[1].p);
          }
          break;
      }
      break;
    case 19 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g ();
          }
          break;
      }
      break;
  }
  
  args = 0;
  position = 0;
  
  if (retValue) *retValue = prim;
}

/*--------------------------------------------
  This file has been generated by cigen       
  using the following command :               

  $CIBIN/cigen.exe -p -h X11/Xlib.h -f XSelection.h -n CiBindXSelection -o ../gen/XSelection_B.c

--------------------------------------------*/

#include <X11/Xlib.h>
#include <XSelection.h>

#ifndef __CI_SWITCH_DEFS__
#define __CI_SWITCH_DEFS__

#ifdef __cplusplus
#define SWITCH_ELLIPSIS ...
#else
#define SWITCH_ELLIPSIS 

#endif

#ifndef __CiDefs__

typedef void            (*CiRoutine)(SWITCH_ELLIPSIS);
typedef char            (*CiCRoutine)(SWITCH_ELLIPSIS);
typedef short           (*CiSRoutine)(SWITCH_ELLIPSIS);
typedef int             (*CiIRoutine)(SWITCH_ELLIPSIS);
typedef long            (*CiLRoutine)(SWITCH_ELLIPSIS);
typedef unsigned char   (*CiUCRoutine)(SWITCH_ELLIPSIS);
typedef unsigned short  (*CiUSRoutine)(SWITCH_ELLIPSIS);
typedef unsigned int    (*CiUIRoutine)(SWITCH_ELLIPSIS);
typedef unsigned long   (*CiULRoutine)(SWITCH_ELLIPSIS);
typedef float           (*CiFRoutine)(SWITCH_ELLIPSIS);
typedef double          (*CiDRoutine)(SWITCH_ELLIPSIS);
typedef void*           (*CiPRoutine)(SWITCH_ELLIPSIS);

#endif

#ifndef __CiType__

typedef union {
  char c;
  short s;
  int i;
  long l;
  char* p;
  float f;
  double d;
} CiPrimValueRec, *CiPrimValue;

#endif

#endif

#ifdef __cplusplus
extern "C" {
#endif

CiRoutine CiBindXSelection (char* library);

static void CiBindXSelectionInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew);

static char* CiBindXSelectionSetupFunction (CiRoutine* switchFunction);

static void CiBindXSelectionSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue);
void CiBindXSelectionCleanup ();

static CiRoutine CiBindXSelectionFileCompile       = 0;
static CiRoutine CiBindXSelectionFunctionBind      = 0;
static CiRoutine CiBindXSelectionVariableBind      = 0;
static CiRoutine CiBindXSelectionFunctionSwitchNew = 0;

#ifdef __cplusplus
}
#endif

/*- Procedure ------------------------------------------*/
CiRoutine CiBindXSelection (char* library)
/*------------------------------------------------------*/
{
  static int first = 1;

  if (first)
    {
      first = 0;
    }
  else if (CiBindXSelectionFunctionSwitchNew)
    {
      CiBindXSelectionFunctionSwitchNew ((CiRoutine) CiBindXSelectionSetupFunction);
    }

  library = 0;

  return ((CiRoutine) CiBindXSelectionInitFunction);
}

/*- Procedure ------------------------------------------*/
static void CiBindXSelectionInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew)
/*------------------------------------------------------*/
{
  CiBindXSelectionFileCompile       = compileFunction;
  pathFunction = 0;
  CiBindXSelectionFunctionBind      = bindFunction;
  CiBindXSelectionVariableBind      = bindVariable;
  CiBindXSelectionFunctionSwitchNew = switchNew;
  CiBindXSelectionVariableBind (0, 0);
  CiBindXSelectionFunctionBind (0, 0);
}

/*- Procedure ------------------------------------------*/
static char* CiBindXSelectionSetupFunction (CiRoutine* switchFunction)
/*------------------------------------------------------*/
{
  static char cases[] = {
    1, 6, 6, 0,
    1, 0,
    6, 0,
    6, 6, 0,
    4, 6, 0,
    1, 6, 0,
    0
  };
  static int first = 1;
  
  if (first)
    {
      first = 0;
  
      CiBindXSelectionFileCompile ("X11/Xlib.h");
      CiBindXSelectionFileCompile ("XSelection.h");
      CiBindXSelectionFunctionBind ("XSelectionIsEndOfCopyEvent", (CiRoutine) XSelectionIsEndOfCopyEvent);
      CiBindXSelectionFunctionBind ("XSelectionSendFile", (CiRoutine) XSelectionSendFile);
      CiBindXSelectionFunctionBind ("XSelectionClearClass", (CiRoutine) XSelectionClearClass);
      CiBindXSelectionFunctionBind ("XSelectionIsNotificationEvent", (CiRoutine) XSelectionIsNotificationEvent);
      CiBindXSelectionFunctionBind ("XSelectionGetPasteFunction", (CiRoutine) XSelectionGetPasteFunction);
      CiBindXSelectionFunctionBind ("XSelectionIsRequestEvent", (CiRoutine) XSelectionIsRequestEvent);
      CiBindXSelectionFunctionBind ("XSelectionDispatchEvent", (CiRoutine) XSelectionDispatchEvent);
      CiBindXSelectionFunctionBind ("XSelectionPutBufferInFile", (CiRoutine) XSelectionPutBufferInFile);
      CiBindXSelectionFunctionBind ("XSelectionSetPasteFunction", (CiRoutine) XSelectionSetPasteFunction);
      CiBindXSelectionFunctionBind ("XSelectionRequireData", (CiRoutine) XSelectionRequireData);
      CiBindXSelectionFunctionBind ("XSelectionPutBufferInString", (CiRoutine) XSelectionPutBufferInString);
      CiBindXSelectionFunctionBind ("XSelectionSendString", (CiRoutine) XSelectionSendString);
    }
  *switchFunction = (CiRoutine) CiBindXSelectionSwitchFunction;
  return ((char*) cases);
}

/*- Procedure ------------------------------------------*/
static void CiBindXSelectionSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue)
/*------------------------------------------------------*/
{
  CiPrimValueRec prim;
  
  prim.l = 0;
  
  switch (code)
  {
    case 4 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p);
          }
          break;
      }
      break;
    case 14 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g ();
          }
          break;
      }
      break;
    case 19 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g ();
          }
          break;
      }
      break;
    case 22 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p);
          }
          break;
      }
      break;
    case 36 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p);
          }
          break;
      }
      break;
    case 37 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p);
          }
          break;
      }
      break;
  }
  
  args = 0;
  position = 0;
  
  if (retValue) *retValue = prim;
}

/*--------------------------------------------
  This file has been generated by cigen       
  using the following command :               

  $CIBIN/cigen.exe -p -h X11/Intrinsic.h -h XDisplay.h -f XWidget.h -n CiBindXWidget -o ../gen/XWidget_B.c

--------------------------------------------*/

#include <X11/Intrinsic.h>
#include <XDisplay.h>
#include <XWidget.h>

#ifndef __CI_SWITCH_DEFS__
#define __CI_SWITCH_DEFS__

#ifdef __cplusplus
#define SWITCH_ELLIPSIS ...
#else
#define SWITCH_ELLIPSIS 

#endif

#ifndef __CiDefs__

typedef void            (*CiRoutine)(SWITCH_ELLIPSIS);
typedef char            (*CiCRoutine)(SWITCH_ELLIPSIS);
typedef short           (*CiSRoutine)(SWITCH_ELLIPSIS);
typedef int             (*CiIRoutine)(SWITCH_ELLIPSIS);
typedef long            (*CiLRoutine)(SWITCH_ELLIPSIS);
typedef unsigned char   (*CiUCRoutine)(SWITCH_ELLIPSIS);
typedef unsigned short  (*CiUSRoutine)(SWITCH_ELLIPSIS);
typedef unsigned int    (*CiUIRoutine)(SWITCH_ELLIPSIS);
typedef unsigned long   (*CiULRoutine)(SWITCH_ELLIPSIS);
typedef float           (*CiFRoutine)(SWITCH_ELLIPSIS);
typedef double          (*CiDRoutine)(SWITCH_ELLIPSIS);
typedef void*           (*CiPRoutine)(SWITCH_ELLIPSIS);

#endif

#ifndef __CiType__

typedef union {
  char c;
  short s;
  int i;
  long l;
  char* p;
  float f;
  double d;
} CiPrimValueRec, *CiPrimValue;

#endif

#endif

#ifdef __cplusplus
extern "C" {
#endif

CiRoutine CiBindXWidget (char* library);

static void CiBindXWidgetInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew);

static char* CiBindXWidgetSetupFunction (CiRoutine* switchFunction);

static void CiBindXWidgetSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue);
void CiBindXWidgetCleanup ();

static CiRoutine CiBindXWidgetFileCompile       = 0;
static CiRoutine CiBindXWidgetFunctionBind      = 0;
static CiRoutine CiBindXWidgetVariableBind      = 0;
static CiRoutine CiBindXWidgetFunctionSwitchNew = 0;

#ifdef __cplusplus
}
#endif

/*- Procedure ------------------------------------------*/
CiRoutine CiBindXWidget (char* library)
/*------------------------------------------------------*/
{
  static int first = 1;

  if (first)
    {
      first = 0;
    }
  else if (CiBindXWidgetFunctionSwitchNew)
    {
      CiBindXWidgetFunctionSwitchNew ((CiRoutine) CiBindXWidgetSetupFunction);
    }

  library = 0;

  return ((CiRoutine) CiBindXWidgetInitFunction);
}

/*- Procedure ------------------------------------------*/
static void CiBindXWidgetInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew)
/*------------------------------------------------------*/
{
  CiBindXWidgetFileCompile       = compileFunction;
  pathFunction = 0;
  CiBindXWidgetFunctionBind      = bindFunction;
  CiBindXWidgetVariableBind      = bindVariable;
  CiBindXWidgetFunctionSwitchNew = switchNew;
  CiBindXWidgetVariableBind (0, 0);
  CiBindXWidgetFunctionBind (0, 0);
}

/*- Procedure ------------------------------------------*/
static char* CiBindXWidgetSetupFunction (CiRoutine* switchFunction)
/*------------------------------------------------------*/
{
  static char cases[] = {
    5, 6, 6, 0,
    1, 6, 2, 0,
    1, 6, 4, 0,
    1, 6, 6, 0,
    6, 6, 4, 0,
    6, 6, 5, 0,
    6, 6, 6, 0,
    5, 6, 0,
    1, 6, 4, 6, 0,
    2, 6, 0,
    4, 6, 5, 5, 0,
    2, 6, 6, 0,
    1, 0,
    4, 0,
    1, 4, 6, 0,
    6, 0,
    4, 6, 6, 6, 4, 6, 6, 6, 0,
    1, 6, 4, 5, 6, 6, 6, 6, 0,
    4, 6, 6, 6, 6, 4, 0,
    6, 6, 0,
    1, 6, 5, 6, 0,
    4, 6, 6, 6, 6, 6, 0,
    1, 6, 6, 6, 5, 0,
    1, 6, 6, 6, 6, 0,
    5, 6, 4, 5, 6, 6, 0,
    4, 6, 6, 6, 0,
    8, 6, 6, 0,
    4, 6, 6, 0,
    2, 6, 6, 6, 0,
    1, 6, 3, 3, 0,
    1, 6, 6, 4, 0,
    1, 6, 6, 5, 0,
    1, 3, 0,
    1, 6, 6, 6, 0,
    4, 6, 0,
    6, 6, 6, 6, 0,
    1, 5, 0,
    1, 6, 0,
    1, 6, 3, 3, 3, 3, 0,
    0
  };
  static int first = 1;
  
  if (first)
    {
      first = 0;
  
      CiBindXWidgetFileCompile ("X11/Intrinsic.h");
      CiBindXWidgetFileCompile ("XDisplay.h");
      CiBindXWidgetFileCompile ("XWidget.h");
      CiBindXWidgetFunctionBind ("XWidgetPopdown", (CiRoutine) XWidgetPopdown);
      CiBindXWidgetFunctionBind ("XWidgetSetAttribute", (CiRoutine) XWidgetSetAttribute);
      CiBindXWidgetFunctionBind ("XDisplayIsGrabbingPointer", (CiRoutine) XDisplayIsGrabbingPointer);
      CiBindXWidgetFunctionBind ("XWidgetSetCursor", (CiRoutine) XWidgetSetCursor);
      CiBindXWidgetFunctionBind ("XWidgetUniconify", (CiRoutine) XWidgetUniconify);
      CiBindXWidgetFunctionBind ("XWidgetGrab", (CiRoutine) XWidgetGrab);
      CiBindXWidgetFunctionBind ("XWidgetGetPopupChildren", (CiRoutine) XWidgetGetPopupChildren);
      CiBindXWidgetFunctionBind ("XtConvertStringToResourceChange", (CiRoutine) XtConvertStringToResourceChange);
      CiBindXWidgetFunctionBind ("XWidgetSetPositionAndDimension", (CiRoutine) XWidgetSetPositionAndDimension);
      CiBindXWidgetFunctionBind ("XWidgetPutPixmapInPS_Stream", (CiRoutine) XWidgetPutPixmapInPS_Stream);
      CiBindXWidgetFunctionBind ("XWidgetGetGetLocalTargetFunction", (CiRoutine) XWidgetGetGetLocalTargetFunction);
      CiBindXWidgetFunctionBind ("XWidgetUnmanage", (CiRoutine) XWidgetUnmanage);
      CiBindXWidgetFunctionBind ("XDisplayGrabPointer", (CiRoutine) XDisplayGrabPointer);
      CiBindXWidgetFunctionBind ("XWidgetSetResource", (CiRoutine) XWidgetSetResource);
      CiBindXWidgetFunctionBind ("XWidgetSetPosition", (CiRoutine) XWidgetSetPosition);
      CiBindXWidgetFunctionBind ("XWidgetGetMaximumNameIndex", (CiRoutine) XWidgetGetMaximumNameIndex);
      CiBindXWidgetFunctionBind ("XWidgetSetIntegerResource", (CiRoutine) XWidgetSetIntegerResource);
      CiBindXWidgetFunctionBind ("XWidgetSetDimension", (CiRoutine) XWidgetSetDimension);
      CiBindXWidgetFunctionBind ("XWidgetUnmap", (CiRoutine) XWidgetUnmap);
      CiBindXWidgetFunctionBind ("XWidgetSetCallbackEventFunction", (CiRoutine) XWidgetSetCallbackEventFunction);
      CiBindXWidgetFunctionBind ("XClassGetDestroyFunction", (CiRoutine) XClassGetDestroyFunction);
      CiBindXWidgetFunctionBind ("XDisplaySetGrabDispatchFunction", (CiRoutine) XDisplaySetGrabDispatchFunction);
      CiBindXWidgetFunctionBind ("XWidgetVisitHierarchyForward", (CiRoutine) XWidgetVisitHierarchyForward);
      CiBindXWidgetFunctionBind ("XWidgetPopup", (CiRoutine) XWidgetPopup);
      CiBindXWidgetFunctionBind ("XWidgetFindInHierarchy", (CiRoutine) XWidgetFindInHierarchy);
      CiBindXWidgetFunctionBind ("XWidgetGetRecordSize", (CiRoutine) XWidgetGetRecordSize);
      CiBindXWidgetFunctionBind ("XWidgetCallCallbacks", (CiRoutine) XWidgetCallCallbacks);
      CiBindXWidgetFunctionBind ("XResourceChangesInitialize", (CiRoutine) XResourceChangesInitialize);
      CiBindXWidgetFunctionBind ("WidgetListConvertToString", (CiRoutine) WidgetListConvertToString);
      CiBindXWidgetFunctionBind ("WidgetListGetNames", (CiRoutine) WidgetListGetNames);
      CiBindXWidgetFunctionBind ("XWidgetGetAndConvertStringResourceToInteger", (CiRoutine) XWidgetGetAndConvertStringResourceToInteger);
      CiBindXWidgetFunctionBind ("XClassIncrementWidgetRecordSize", (CiRoutine) XClassIncrementWidgetRecordSize);
      CiBindXWidgetFunctionBind ("XWidgetGetPosition", (CiRoutine) XWidgetGetPosition);
      CiBindXWidgetFunctionBind ("XWidgetGetWidgetListResource", (CiRoutine) XWidgetGetWidgetListResource);
      CiBindXWidgetFunctionBind ("XWidgetConvertStringToPixel", (CiRoutine) XWidgetConvertStringToPixel);
      CiBindXWidgetFunctionBind ("XWidgetGetTarget", (CiRoutine) XWidgetGetTarget);
      CiBindXWidgetFunctionBind ("XWidgetGetCallValue", (CiRoutine) XWidgetGetCallValue);
      CiBindXWidgetFunctionBind ("XWidgetGetBooleanResource", (CiRoutine) XWidgetGetBooleanResource);
      CiBindXWidgetFunctionBind ("XWidgetConvertStringToCursor", (CiRoutine) XWidgetConvertStringToCursor);
      CiBindXWidgetFunctionBind ("XWidgetInitializeClass", (CiRoutine) XWidgetInitializeClass);
      CiBindXWidgetFunctionBind ("XWidgetSetTargetBorderPixel", (CiRoutine) XWidgetSetTargetBorderPixel);
      CiBindXWidgetFunctionBind ("XWidgetShowDisarming", (CiRoutine) XWidgetShowDisarming);
      CiBindXWidgetFunctionBind ("XWidgetSavePixmapInGIF_File", (CiRoutine) XWidgetSavePixmapInGIF_File);
      CiBindXWidgetFunctionBind ("XWidgetSetUnmapFunction", (CiRoutine) XWidgetSetUnmapFunction);
      CiBindXWidgetFunctionBind ("XWidgetSetTargetChangedFunction", (CiRoutine) XWidgetSetTargetChangedFunction);
      CiBindXWidgetFunctionBind ("XWidgetRemoveEntryFromWidgetListResource", (CiRoutine) XWidgetRemoveEntryFromWidgetListResource);
      CiBindXWidgetFunctionBind ("XWidgetSetCallValue", (CiRoutine) XWidgetSetCallValue);
      CiBindXWidgetFunctionBind ("XWidgetGetNumberOfSubWidgets", (CiRoutine) XWidgetGetNumberOfSubWidgets);
      CiBindXWidgetFunctionBind ("WidgetListCreateFromString", (CiRoutine) WidgetListCreateFromString);
      CiBindXWidgetFunctionBind ("XWidgetGetClassName", (CiRoutine) XWidgetGetClassName);
      CiBindXWidgetFunctionBind ("XClassSetIsValidFunction", (CiRoutine) XClassSetIsValidFunction);
      CiBindXWidgetFunctionBind ("XWidgetLower", (CiRoutine) XWidgetLower);
      CiBindXWidgetFunctionBind ("XWidgetGetLeaves", (CiRoutine) XWidgetGetLeaves);
      CiBindXWidgetFunctionBind ("XWidgetGetAllChildren", (CiRoutine) XWidgetGetAllChildren);
      CiBindXWidgetFunctionBind ("XWidgetSetWidgetResource", (CiRoutine) XWidgetSetWidgetResource);
      CiBindXWidgetFunctionBind ("XWidgetIsValid", (CiRoutine) XWidgetIsValid);
      CiBindXWidgetFunctionBind ("XDisplayUpdate", (CiRoutine) XDisplayUpdate);
      CiBindXWidgetFunctionBind ("XWidgetInstallColormap", (CiRoutine) XWidgetInstallColormap);
      CiBindXWidgetFunctionBind ("XWidgetGetPixmap", (CiRoutine) XWidgetGetPixmap);
      CiBindXWidgetFunctionBind ("XWidgetGetLocalTarget", (CiRoutine) XWidgetGetLocalTarget);
      CiBindXWidgetFunctionBind ("XWidgetGetResourceOptions", (CiRoutine) XWidgetGetResourceOptions);
      CiBindXWidgetFunctionBind ("XWidgetSetGrabButtonAndCursor", (CiRoutine) XWidgetSetGrabButtonAndCursor);
      CiBindXWidgetFunctionBind ("XWidgetSetMapFunction", (CiRoutine) XWidgetSetMapFunction);
      CiBindXWidgetFunctionBind ("XWidgetGetResources", (CiRoutine) XWidgetGetResources);
      CiBindXWidgetFunctionBind ("XWidgetGetInformations", (CiRoutine) XWidgetGetInformations);
      CiBindXWidgetFunctionBind ("XWidgetSetTarget", (CiRoutine) XWidgetSetTarget);
      CiBindXWidgetFunctionBind ("XWidgetSetCallData", (CiRoutine) XWidgetSetCallData);
      CiBindXWidgetFunctionBind ("XWidgetDoMethod", (CiRoutine) XWidgetDoMethod);
      CiBindXWidgetFunctionBind ("XWidgetSetPixelResource", (CiRoutine) XWidgetSetPixelResource);
      CiBindXWidgetFunctionBind ("XWidgetMapChildren", (CiRoutine) XWidgetMapChildren);
      CiBindXWidgetFunctionBind ("XWidgetPutFrameInPS_Stream", (CiRoutine) XWidgetPutFrameInPS_Stream);
      CiBindXWidgetFunctionBind ("XWidgetGetChildren", (CiRoutine) XWidgetGetChildren);
      CiBindXWidgetFunctionBind ("XWidgetBuildName", (CiRoutine) XWidgetBuildName);
      CiBindXWidgetFunctionBind ("XWidgetGrabRootWindowPart", (CiRoutine) XWidgetGrabRootWindowPart);
      CiBindXWidgetFunctionBind ("XWidgetRealize", (CiRoutine) XWidgetRealize);
      CiBindXWidgetFunctionBind ("XWidgetIsEntryOfWidgetListResource", (CiRoutine) XWidgetIsEntryOfWidgetListResource);
      CiBindXWidgetFunctionBind ("XWidgetGetNextBrother", (CiRoutine) XWidgetGetNextBrother);
      CiBindXWidgetFunctionBind ("XWidgetLoadPixmapFile", (CiRoutine) XWidgetLoadPixmapFile);
      CiBindXWidgetFunctionBind ("XWidgetSetGetLocalTargetFunction", (CiRoutine) XWidgetSetGetLocalTargetFunction);
      CiBindXWidgetFunctionBind ("XWidgetMapWindow", (CiRoutine) XWidgetMapWindow);
      CiBindXWidgetFunctionBind ("XWidgetIconify", (CiRoutine) XWidgetIconify);
      CiBindXWidgetFunctionBind ("XWidgetShowArming", (CiRoutine) XWidgetShowArming);
      CiBindXWidgetFunctionBind ("XWidgetGetTop", (CiRoutine) XWidgetGetTop);
      CiBindXWidgetFunctionBind ("XWidgetPutPixmapPageInPS_Stream", (CiRoutine) XWidgetPutPixmapPageInPS_Stream);
      CiBindXWidgetFunctionBind ("XWidgetSetWindowManagerCloseFunction", (CiRoutine) XWidgetSetWindowManagerCloseFunction);
      CiBindXWidgetFunctionBind ("XWidgetPutPixmapInRootWindow", (CiRoutine) XWidgetPutPixmapInRootWindow);
      CiBindXWidgetFunctionBind ("XResourceChangesCommit", (CiRoutine) XResourceChangesCommit);
      CiBindXWidgetFunctionBind ("XWidgetAddEntryInWidgetListResource", (CiRoutine) XWidgetAddEntryInWidgetListResource);
      CiBindXWidgetFunctionBind ("XWidgetGetResource", (CiRoutine) XWidgetGetResource);
      CiBindXWidgetFunctionBind ("XWidgetGetAndConvertStringResourceToWidget", (CiRoutine) XWidgetGetAndConvertStringResourceToWidget);
      CiBindXWidgetFunctionBind ("XWidgetGetQuarkifiedName", (CiRoutine) XWidgetGetQuarkifiedName);
      CiBindXWidgetFunctionBind ("XResourceChangesFlush", (CiRoutine) XResourceChangesFlush);
      CiBindXWidgetFunctionBind ("XWidgetClearClass", (CiRoutine) XWidgetClearClass);
      CiBindXWidgetFunctionBind ("XWidgetSavePixmapInXBM_File", (CiRoutine) XWidgetSavePixmapInXBM_File);
      CiBindXWidgetFunctionBind ("XWidgetGetAddressResource", (CiRoutine) XWidgetGetAddressResource);
      CiBindXWidgetFunctionBind ("XWidgetMove", (CiRoutine) XWidgetMove);
      CiBindXWidgetFunctionBind ("XWidgetGetPixelResource", (CiRoutine) XWidgetGetPixelResource);
      CiBindXWidgetFunctionBind ("XClassIsSubclass", (CiRoutine) XClassIsSubclass);
      CiBindXWidgetFunctionBind ("XWidgetGetFirstEntryOfWidgetListResource", (CiRoutine) XWidgetGetFirstEntryOfWidgetListResource);
      CiBindXWidgetFunctionBind ("XWidgetGetIthResource", (CiRoutine) XWidgetGetIthResource);
      CiBindXWidgetFunctionBind ("XWidgetConvertStringToFont", (CiRoutine) XWidgetConvertStringToFont);
      CiBindXWidgetFunctionBind ("XWidgetManage", (CiRoutine) XWidgetManage);
      CiBindXWidgetFunctionBind ("XWidgetIsVisible", (CiRoutine) XWidgetIsVisible);
      CiBindXWidgetFunctionBind ("XWidgetSendMessage", (CiRoutine) XWidgetSendMessage);
      CiBindXWidgetFunctionBind ("XWidgetExecuteChangeSizeFunction", (CiRoutine) XWidgetExecuteChangeSizeFunction);
      CiBindXWidgetFunctionBind ("XWidgetGetAndConvertStringResourceToDouble", (CiRoutine) XWidgetGetAndConvertStringResourceToDouble);
      CiBindXWidgetFunctionBind ("XWidgetGetNumberOfResources", (CiRoutine) XWidgetGetNumberOfResources);
      CiBindXWidgetFunctionBind ("XResourceChangesAddEntry", (CiRoutine) XResourceChangesAddEntry);
      CiBindXWidgetFunctionBind ("XWidgetUnmapWindow", (CiRoutine) XWidgetUnmapWindow);
      CiBindXWidgetFunctionBind ("XWidgetGetThisWidget", (CiRoutine) XWidgetGetThisWidget);
      CiBindXWidgetFunctionBind ("XWidgetGetFirstChild", (CiRoutine) XWidgetGetFirstChild);
      CiBindXWidgetFunctionBind ("XWidgetMap", (CiRoutine) XWidgetMap);
      CiBindXWidgetFunctionBind ("XWidgetSetThisWidget", (CiRoutine) XWidgetSetThisWidget);
      CiBindXWidgetFunctionBind ("XWidgetGetDimension", (CiRoutine) XWidgetGetDimension);
      CiBindXWidgetFunctionBind ("XWidgetSetName", (CiRoutine) XWidgetSetName);
      CiBindXWidgetFunctionBind ("XWidgetSetSensitive", (CiRoutine) XWidgetSetSensitive);
      CiBindXWidgetFunctionBind ("XWidgetUninstallColormap", (CiRoutine) XWidgetUninstallColormap);
      CiBindXWidgetFunctionBind ("XWidgetSetTargetBorderWidth", (CiRoutine) XWidgetSetTargetBorderWidth);
      CiBindXWidgetFunctionBind ("XClassGetIdentifier", (CiRoutine) XClassGetIdentifier);
      CiBindXWidgetFunctionBind ("XWidgetSetTop", (CiRoutine) XWidgetSetTop);
      CiBindXWidgetFunctionBind ("XWidgetRaise", (CiRoutine) XWidgetRaise);
      CiBindXWidgetFunctionBind ("XClassSetGetIdentifierFunction", (CiRoutine) XClassSetGetIdentifierFunction);
      CiBindXWidgetFunctionBind ("XDisplayDoRubberBandGrab", (CiRoutine) XDisplayDoRubberBandGrab);
      CiBindXWidgetFunctionBind ("XWidgetSpawnShellScript", (CiRoutine) XWidgetSpawnShellScript);
      CiBindXWidgetFunctionBind ("XWidgetGetIdentifiers", (CiRoutine) XWidgetGetIdentifiers);
      CiBindXWidgetFunctionBind ("XWidgetGetShell", (CiRoutine) XWidgetGetShell);
      CiBindXWidgetFunctionBind ("XClassIsValid", (CiRoutine) XClassIsValid);
      CiBindXWidgetFunctionBind ("XClassGetName", (CiRoutine) XClassGetName);
      CiBindXWidgetFunctionBind ("XWidgetGetIntegerResource", (CiRoutine) XWidgetGetIntegerResource);
      CiBindXWidgetFunctionBind ("XWidgetSetShape", (CiRoutine) XWidgetSetShape);
      CiBindXWidgetFunctionBind ("XResourceChangesSetWidget", (CiRoutine) XResourceChangesSetWidget);
      CiBindXWidgetFunctionBind ("XWidgetIsConstraint", (CiRoutine) XWidgetIsConstraint);
      CiBindXWidgetFunctionBind ("XWidgetGetCallData", (CiRoutine) XWidgetGetCallData);
      CiBindXWidgetFunctionBind ("XWidgetGetWidgetResource", (CiRoutine) XWidgetGetWidgetResource);
      CiBindXWidgetFunctionBind ("XWidgetIsInHierarchy", (CiRoutine) XWidgetIsInHierarchy);
      CiBindXWidgetFunctionBind ("XWidgetGetIdentifier", (CiRoutine) XWidgetGetIdentifier);
      CiBindXWidgetFunctionBind ("XWidgetGetRootPosition", (CiRoutine) XWidgetGetRootPosition);
      CiBindXWidgetFunctionBind ("XWidgetExecuteExposeFunction", (CiRoutine) XWidgetExecuteExposeFunction);
      CiBindXWidgetFunctionBind ("XWidgetGetAttribute", (CiRoutine) XWidgetGetAttribute);
      CiBindXWidgetFunctionBind ("XWidgetConvertStringToFontStruct", (CiRoutine) XWidgetConvertStringToFontStruct);
      CiBindXWidgetFunctionBind ("XWidgetSwapWindows", (CiRoutine) XWidgetSwapWindows);
      CiBindXWidgetFunctionBind ("XWidgetGetAndConvertStringResourceToBoolean", (CiRoutine) XWidgetGetAndConvertStringResourceToBoolean);
    }
  *switchFunction = (CiRoutine) CiBindXWidgetSwitchFunction;
  return ((char*) cases);
}

/*- Procedure ------------------------------------------*/
static void CiBindXWidgetSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue)
/*------------------------------------------------------*/
{
  CiPrimValueRec prim;
  
  prim.l = 0;
  
  switch (code)
  {
    case 0 :
      switch (position)
      {
        case 1 :
          {
            CiLRoutine g = (CiLRoutine) f;

            prim.l = g (args[0].p, args[1].p);
          }
          break;
        case 2 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].c);
          }
          break;
      }
      break;
    case 2 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].i);
          }
          break;
      }
      break;
    case 4 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p);
          }
          break;
      }
      break;
    case 7 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p, args[1].i);
          }
          break;
      }
      break;
    case 8 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p, args[1].l);
          }
          break;
      }
      break;
    case 9 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p, args[1].p);
          }
          break;
        case 2 :
          {
            CiLRoutine g = (CiLRoutine) f;

            prim.l = g (args[0].p);
          }
          break;
        case 3 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].i, args[2].p);
          }
          break;
      }
      break;
    case 10 :
      switch (position)
      {
        case 1 :
          {
            CiCRoutine g = (CiCRoutine) f;

            prim.c = g (args[0].p);
          }
          break;
      }
      break;
    case 12 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].l, args[2].l);
          }
          break;
      }
      break;
    case 13 :
      switch (position)
      {
        case 1 :
          {
            CiCRoutine g = (CiCRoutine) f;

            prim.c = g (args[0].p, args[1].p);
          }
          break;
      }
      break;
    case 14 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g ();
          }
          break;
      }
      break;
    case 17 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g ();
          }
          break;
      }
      break;
    case 18 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].i, args[1].p);
          }
          break;
      }
      break;
    case 19 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g ();
          }
          break;
      }
      break;
    case 20 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].p, args[2].p, args[3].i, 
                        args[4].p, args[5].p, args[6].p);
          }
          break;
        case 2 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].i, args[2].l, args[3].p, 
               args[4].p, args[5].p, args[6].p);
          }
          break;
      }
      break;
    case 22 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].p, args[2].p, args[3].p, 
                        args[4].i);
          }
          break;
        case 2 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p);
          }
          break;
        case 3 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].l, args[2].p);
          }
          break;
      }
      break;
    case 24 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].p, args[2].p, args[3].p, 
                        args[4].p);
          }
          break;
      }
      break;
    case 25 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p, args[2].p, args[3].l);
          }
          break;
      }
      break;
    case 26 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p, args[2].p, args[3].p);
          }
          break;
        case 2 :
          {
            CiLRoutine g = (CiLRoutine) f;

            prim.l = g (args[0].p, args[1].i, args[2].l, args[3].p, 
                        args[4].p);
          }
          break;
        case 3 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].p, args[2].p);
          }
          break;
      }
      break;
    case 27 :
      switch (position)
      {
        case 1 :
          {
            CiDRoutine g = (CiDRoutine) f;

            prim.d = g (args[0].p, args[1].p);
          }
          break;
      }
      break;
    case 31 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].p);
          }
          break;
      }
      break;
    case 32 :
      switch (position)
      {
        case 1 :
          {
            CiCRoutine g = (CiCRoutine) f;

            prim.c = g (args[0].p, args[1].p, args[2].p);
          }
          break;
      }
      break;
    case 33 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].s, args[2].s);
          }
          break;
        case 2 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p, args[2].i);
          }
          break;
      }
      break;
    case 34 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p, args[2].l);
          }
          break;
        case 2 :
          {
            CiRoutine g = f;

            g (args[0].s);
          }
          break;
      }
      break;
    case 35 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p, args[2].p);
          }
          break;
      }
      break;
    case 36 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p);
          }
          break;
        case 2 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p, args[1].p, args[2].p);
          }
          break;
        case 3 :
          {
            CiRoutine g = f;

            g (args[0].l);
          }
          break;
      }
      break;
    case 37 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p);
          }
          break;
        case 2 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].s, args[2].s, args[3].s, 
               args[4].s);
          }
          break;
      }
      break;
  }
  
  args = 0;
  position = 0;
  
  if (retValue) *retValue = prim;
}

/*--------------------------------------------
  This file has been generated by cigen       
  using the following command :               

  $CIBIN/cigen.exe -p -h FString.h -f XxF77.h -n CiBindXxF77 -o ../gen/XxF77_B.c

--------------------------------------------*/

#include <FString.h>
#include <XxF77.h>

#ifndef __CI_SWITCH_DEFS__
#define __CI_SWITCH_DEFS__

#ifdef __cplusplus
#define SWITCH_ELLIPSIS ...
#else
#define SWITCH_ELLIPSIS 

#endif

#ifndef __CiDefs__

typedef void            (*CiRoutine)(SWITCH_ELLIPSIS);
typedef char            (*CiCRoutine)(SWITCH_ELLIPSIS);
typedef short           (*CiSRoutine)(SWITCH_ELLIPSIS);
typedef int             (*CiIRoutine)(SWITCH_ELLIPSIS);
typedef long            (*CiLRoutine)(SWITCH_ELLIPSIS);
typedef unsigned char   (*CiUCRoutine)(SWITCH_ELLIPSIS);
typedef unsigned short  (*CiUSRoutine)(SWITCH_ELLIPSIS);
typedef unsigned int    (*CiUIRoutine)(SWITCH_ELLIPSIS);
typedef unsigned long   (*CiULRoutine)(SWITCH_ELLIPSIS);
typedef float           (*CiFRoutine)(SWITCH_ELLIPSIS);
typedef double          (*CiDRoutine)(SWITCH_ELLIPSIS);
typedef void*           (*CiPRoutine)(SWITCH_ELLIPSIS);

#endif

#ifndef __CiType__

typedef union {
  char c;
  short s;
  int i;
  long l;
  char* p;
  float f;
  double d;
} CiPrimValueRec, *CiPrimValue;

#endif

#endif

#ifdef __cplusplus
extern "C" {
#endif

CiRoutine CiBindXxF77 (char* library);

static void CiBindXxF77InitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew);

static char* CiBindXxF77SetupFunction (CiRoutine* switchFunction);

static void CiBindXxF77SwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue);
void CiBindXxF77Cleanup ();

static CiRoutine CiBindXxF77FileCompile       = 0;
static CiRoutine CiBindXxF77FunctionBind      = 0;
static CiRoutine CiBindXxF77VariableBind      = 0;
static CiRoutine CiBindXxF77FunctionSwitchNew = 0;

#ifdef __cplusplus
}
#endif

/*- Procedure ------------------------------------------*/
CiRoutine CiBindXxF77 (char* library)
/*------------------------------------------------------*/
{
  static int first = 1;

  if (first)
    {
      first = 0;
    }
  else if (CiBindXxF77FunctionSwitchNew)
    {
      CiBindXxF77FunctionSwitchNew ((CiRoutine) CiBindXxF77SetupFunction);
    }

  library = 0;

  return ((CiRoutine) CiBindXxF77InitFunction);
}

/*- Procedure ------------------------------------------*/
static void CiBindXxF77InitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew)
/*------------------------------------------------------*/
{
  CiBindXxF77FileCompile       = compileFunction;
  pathFunction = 0;
  CiBindXxF77FunctionBind      = bindFunction;
  CiBindXxF77VariableBind      = bindVariable;
  CiBindXxF77FunctionSwitchNew = switchNew;
  CiBindXxF77VariableBind (0, 0);
  CiBindXxF77FunctionBind (0, 0);
}

/*- Procedure ------------------------------------------*/
static char* CiBindXxF77SetupFunction (CiRoutine* switchFunction)
/*------------------------------------------------------*/
{
  static char cases[] = {
    1, 6, 6, 0,
    1, 0,
    4, 0,
    4, 6, 6, 0,
    0
  };
  static int first = 1;
  
  if (first)
    {
      first = 0;
  
      CiBindXxF77FileCompile ("FString.h");
      CiBindXxF77FileCompile ("XxF77.h");
      CiBindXxF77FunctionBind ("xdpope", (CiRoutine) xdpope);
      CiBindXxF77FunctionBind ("xmbsen", (CiRoutine) xmbsen);
      CiBindXxF77FunctionBind ("xdpclo", (CiRoutine) xdpclo);
      CiBindXxF77FunctionBind ("xmbope", (CiRoutine) xmbope);
    }
  *switchFunction = (CiRoutine) CiBindXxF77SwitchFunction;
  return ((char*) cases);
}

/*- Procedure ------------------------------------------*/
static void CiBindXxF77SwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue)
/*------------------------------------------------------*/
{
  CiPrimValueRec prim;
  
  prim.l = 0;
  
  switch (code)
  {
    case 4 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p);
          }
          break;
      }
      break;
    case 14 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g ();
          }
          break;
      }
      break;
    case 17 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g ();
          }
          break;
      }
      break;
    case 31 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].p);
          }
          break;
      }
      break;
  }
  
  args = 0;
  position = 0;
  
  if (retValue) *retValue = prim;
}

/*--------------------------------------------
  This file has been generated by cigen       
  using the following command :               

  $CIBIN/cigen.exe -p -f XxTypes.h -n CiBindXxTypes -o ../gen/XxTypes_B.c

--------------------------------------------*/

#include <XxTypes.h>

#ifndef __CI_SWITCH_DEFS__
#define __CI_SWITCH_DEFS__

#ifdef __cplusplus
#define SWITCH_ELLIPSIS ...
#else
#define SWITCH_ELLIPSIS 

#endif

#ifndef __CiDefs__

typedef void            (*CiRoutine)(SWITCH_ELLIPSIS);
typedef char            (*CiCRoutine)(SWITCH_ELLIPSIS);
typedef short           (*CiSRoutine)(SWITCH_ELLIPSIS);
typedef int             (*CiIRoutine)(SWITCH_ELLIPSIS);
typedef long            (*CiLRoutine)(SWITCH_ELLIPSIS);
typedef unsigned char   (*CiUCRoutine)(SWITCH_ELLIPSIS);
typedef unsigned short  (*CiUSRoutine)(SWITCH_ELLIPSIS);
typedef unsigned int    (*CiUIRoutine)(SWITCH_ELLIPSIS);
typedef unsigned long   (*CiULRoutine)(SWITCH_ELLIPSIS);
typedef float           (*CiFRoutine)(SWITCH_ELLIPSIS);
typedef double          (*CiDRoutine)(SWITCH_ELLIPSIS);
typedef void*           (*CiPRoutine)(SWITCH_ELLIPSIS);

#endif

#ifndef __CiType__

typedef union {
  char c;
  short s;
  int i;
  long l;
  char* p;
  float f;
  double d;
} CiPrimValueRec, *CiPrimValue;

#endif

#endif

#ifdef __cplusplus
extern "C" {
#endif

CiRoutine CiBindXxTypes (char* library);

static void CiBindXxTypesInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew);

static char* CiBindXxTypesSetupFunction (CiRoutine* switchFunction);

static void CiBindXxTypesSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue);
void CiBindXxTypesCleanup ();

static CiRoutine CiBindXxTypesFileCompile       = 0;
static CiRoutine CiBindXxTypesFunctionBind      = 0;
static CiRoutine CiBindXxTypesVariableBind      = 0;
static CiRoutine CiBindXxTypesFunctionSwitchNew = 0;

#ifdef __cplusplus
}
#endif

/*- Procedure ------------------------------------------*/
CiRoutine CiBindXxTypes (char* library)
/*------------------------------------------------------*/
{
  static int first = 1;

  if (first)
    {
      first = 0;
    }
  else if (CiBindXxTypesFunctionSwitchNew)
    {
      CiBindXxTypesFunctionSwitchNew ((CiRoutine) CiBindXxTypesSetupFunction);
    }

  library = 0;

  return ((CiRoutine) CiBindXxTypesInitFunction);
}

/*- Procedure ------------------------------------------*/
static void CiBindXxTypesInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew)
/*------------------------------------------------------*/
{
  CiBindXxTypesFileCompile       = compileFunction;
  pathFunction = 0;
  CiBindXxTypesFunctionBind      = bindFunction;
  CiBindXxTypesVariableBind      = bindVariable;
  CiBindXxTypesFunctionSwitchNew = switchNew;
  CiBindXxTypesVariableBind (0, 0);
  CiBindXxTypesFunctionBind (0, 0);
}

/*- Procedure ------------------------------------------*/
static char* CiBindXxTypesSetupFunction (CiRoutine* switchFunction)
/*------------------------------------------------------*/
{
  static char cases[] = {
    1, 0,
    0
  };
  static int first = 1;
  
  if (first)
    {
      first = 0;
  
      CiBindXxTypesFileCompile ("XxTypes.h");
      CiBindXxTypesFunctionBind ("XxSetTypes", (CiRoutine) XxSetTypes);
    }
  *switchFunction = (CiRoutine) CiBindXxTypesSwitchFunction;
  return ((char*) cases);
}

/*- Procedure ------------------------------------------*/
static void CiBindXxTypesSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue)
/*------------------------------------------------------*/
{
  CiPrimValueRec prim;
  
  prim.l = 0;
  
  switch (code)
  {
    case 14 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g ();
          }
          break;
      }
      break;
  }
  
  args = 0;
  position = 0;
  
  if (retValue) *retValue = prim;
}

