/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>
/* Header for class Wo */

#ifndef _Included_Wo
#define _Included_Wo

#pragma pack(4)

typedef struct ClassWo {
    char PAD;	/* ANSI C requires structures to have a least one member */
} ClassWo;
HandleTo(Wo);

#pragma pack()

#ifdef __cplusplus
extern "C" {
#endif
extern void Wo_Startup(struct HWo *);
extern void Wo_ProcessEvents(struct HWo *);
extern void Wo_ClearClass(struct HWo *);
struct Hjava_lang_String;
extern void Wo_SetInterfaceFile(struct HWo *,struct Hjava_lang_String *);
#ifdef __cplusplus
}
#endif
#endif
