/*--------------------------------------------
  This file has been generated by cigen       
  using the following command :               

  $CIBIN/cigen.exe -p -f HoTypes.h -n CiBindHoTypes -o ../gen/HoTypes_B.c

--------------------------------------------*/

#include <HoTypes.h>

#ifndef __CI_SWITCH_DEFS__
#define __CI_SWITCH_DEFS__

#ifdef __cplusplus
#define SWITCH_ELLIPSIS ...
#else
#define SWITCH_ELLIPSIS 

#endif

#ifndef __CiDefs__

typedef void            (*CiRoutine)(SWITCH_ELLIPSIS);
typedef char            (*CiCRoutine)(SWITCH_ELLIPSIS);
typedef short           (*CiSRoutine)(SWITCH_ELLIPSIS);
typedef int             (*CiIRoutine)(SWITCH_ELLIPSIS);
typedef long            (*CiLRoutine)(SWITCH_ELLIPSIS);
typedef unsigned char   (*CiUCRoutine)(SWITCH_ELLIPSIS);
typedef unsigned short  (*CiUSRoutine)(SWITCH_ELLIPSIS);
typedef unsigned int    (*CiUIRoutine)(SWITCH_ELLIPSIS);
typedef unsigned long   (*CiULRoutine)(SWITCH_ELLIPSIS);
typedef float           (*CiFRoutine)(SWITCH_ELLIPSIS);
typedef double          (*CiDRoutine)(SWITCH_ELLIPSIS);
typedef void*           (*CiPRoutine)(SWITCH_ELLIPSIS);

#endif

#ifndef __CiType__

typedef union {
  char c;
  short s;
  int i;
  long l;
  char* p;
  float f;
  double d;
} CiPrimValueRec, *CiPrimValue;

#endif

#endif

#ifdef __cplusplus
extern "C" {
#endif

CiRoutine CiBindHoTypes (char* library);

static void CiBindHoTypesInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew);

static char* CiBindHoTypesSetupFunction (CiRoutine* switchFunction);

static void CiBindHoTypesSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue);
void CiBindHoTypesCleanup ();

static CiRoutine CiBindHoTypesFileCompile       = 0;
static CiRoutine CiBindHoTypesFunctionBind      = 0;
static CiRoutine CiBindHoTypesVariableBind      = 0;
static CiRoutine CiBindHoTypesFunctionSwitchNew = 0;

#ifdef __cplusplus
}
#endif

/*- Procedure ------------------------------------------*/
CiRoutine CiBindHoTypes (char* library)
/*------------------------------------------------------*/
{
  static int first = 1;

  if (first)
    {
      first = 0;
    }
  else if (CiBindHoTypesFunctionSwitchNew)
    {
      CiBindHoTypesFunctionSwitchNew ((CiRoutine) CiBindHoTypesSetupFunction);
    }

  library = 0;

  return ((CiRoutine) CiBindHoTypesInitFunction);
}

/*- Procedure ------------------------------------------*/
static void CiBindHoTypesInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew)
/*------------------------------------------------------*/
{
  CiBindHoTypesFileCompile       = compileFunction;
  pathFunction = 0;
  CiBindHoTypesFunctionBind      = bindFunction;
  CiBindHoTypesVariableBind      = bindVariable;
  CiBindHoTypesFunctionSwitchNew = switchNew;
  CiBindHoTypesVariableBind (0, 0);
  CiBindHoTypesFunctionBind (0, 0);
}

/*- Procedure ------------------------------------------*/
static char* CiBindHoTypesSetupFunction (CiRoutine* switchFunction)
/*------------------------------------------------------*/
{
  static char cases[] = {
    1, 0,
    0
  };
  static int first = 1;
  
  if (first)
    {
      first = 0;
  
      CiBindHoTypesFileCompile ("HoTypes.h");
      CiBindHoTypesFunctionBind ("HoSetTypes", (CiRoutine) HoSetTypes);
    }
  *switchFunction = (CiRoutine) CiBindHoTypesSwitchFunction;
  return ((char*) cases);
}

/*- Procedure ------------------------------------------*/
static void CiBindHoTypesSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue)
/*------------------------------------------------------*/
{
  CiPrimValueRec prim;
  
  prim.l = 0;
  
  switch (code)
  {
    case 14 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g ();
          }
          break;
      }
      break;
  }
  
  args = 0;
  position = 0;
  
  if (retValue) *retValue = prim;
}

/*--------------------------------------------
  This file has been generated by cigen       
  using the following command :               

  $CIBIN/cigen.exe -p -h OHistogram.h -h OScatter.h -h OTuple.h -h OCut.h -h OFit.h -f Ho.h -n CiBindHo -o ../gen/Ho_B.c

--------------------------------------------*/

#include <OHistogram.h>
#include <OScatter.h>
#include <OTuple.h>
#include <OCut.h>
#include <OFit.h>
#include <Ho.h>

#ifndef __CI_SWITCH_DEFS__
#define __CI_SWITCH_DEFS__

#ifdef __cplusplus
#define SWITCH_ELLIPSIS ...
#else
#define SWITCH_ELLIPSIS 

#endif

#ifndef __CiDefs__

typedef void            (*CiRoutine)(SWITCH_ELLIPSIS);
typedef char            (*CiCRoutine)(SWITCH_ELLIPSIS);
typedef short           (*CiSRoutine)(SWITCH_ELLIPSIS);
typedef int             (*CiIRoutine)(SWITCH_ELLIPSIS);
typedef long            (*CiLRoutine)(SWITCH_ELLIPSIS);
typedef unsigned char   (*CiUCRoutine)(SWITCH_ELLIPSIS);
typedef unsigned short  (*CiUSRoutine)(SWITCH_ELLIPSIS);
typedef unsigned int    (*CiUIRoutine)(SWITCH_ELLIPSIS);
typedef unsigned long   (*CiULRoutine)(SWITCH_ELLIPSIS);
typedef float           (*CiFRoutine)(SWITCH_ELLIPSIS);
typedef double          (*CiDRoutine)(SWITCH_ELLIPSIS);
typedef void*           (*CiPRoutine)(SWITCH_ELLIPSIS);

#endif

#ifndef __CiType__

typedef union {
  char c;
  short s;
  int i;
  long l;
  char* p;
  float f;
  double d;
} CiPrimValueRec, *CiPrimValue;

#endif

#endif

#ifdef __cplusplus
extern "C" {
#endif

CiRoutine CiBindHo (char* library);

static void CiBindHoInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew);

static char* CiBindHoSetupFunction (CiRoutine* switchFunction);

static void CiBindHoSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue);
void CiBindHoCleanup ();

static CiRoutine CiBindHoFileCompile       = 0;
static CiRoutine CiBindHoFunctionBind      = 0;
static CiRoutine CiBindHoVariableBind      = 0;
static CiRoutine CiBindHoFunctionSwitchNew = 0;

#ifdef __cplusplus
}
#endif

/*- Procedure ------------------------------------------*/
CiRoutine CiBindHo (char* library)
/*------------------------------------------------------*/
{
  static int first = 1;

  if (first)
    {
      first = 0;
    }
  else if (CiBindHoFunctionSwitchNew)
    {
      CiBindHoFunctionSwitchNew ((CiRoutine) CiBindHoSetupFunction);
    }

  library = 0;

  return ((CiRoutine) CiBindHoInitFunction);
}

/*- Procedure ------------------------------------------*/
static void CiBindHoInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew)
/*------------------------------------------------------*/
{
  CiBindHoFileCompile       = compileFunction;
  pathFunction = 0;
  CiBindHoFunctionBind      = bindFunction;
  CiBindHoVariableBind      = bindVariable;
  CiBindHoFunctionSwitchNew = switchNew;
  CiBindHoVariableBind (0, 0);
  CiBindHoFunctionBind (0, 0);
}

/*- Procedure ------------------------------------------*/
static char* CiBindHoSetupFunction (CiRoutine* switchFunction)
/*------------------------------------------------------*/
{
  static char cases[] = {
    4, 6, 6, 4, 6, 6, 0,
    6, 6, 6, 4, 6, 4, 6, 0,
    1, 0,
    6, 6, 0,
    6, 6, 6, 4, 6, 4, 6, 4, 0,
    1, 6, 0,
    0
  };
  static int first = 1;
  
  if (first)
    {
      first = 0;
  
      CiBindHoFileCompile ("OHistogram.h");
      CiBindHoFileCompile ("OScatter.h");
      CiBindHoFileCompile ("OTuple.h");
      CiBindHoFileCompile ("OCut.h");
      CiBindHoFileCompile ("OFit.h");
      CiBindHoFileCompile ("Ho.h");
      CiBindHoFunctionBind ("HoFillScatterFromTuple", (CiRoutine) HoFillScatterFromTuple);
      CiBindHoFunctionBind ("HoClearClass", (CiRoutine) HoClearClass);
      CiBindHoFunctionBind ("HoConvert", (CiRoutine) HoConvert);
      CiBindHoFunctionBind ("HoFitHistogram", (CiRoutine) HoFitHistogram);
      CiBindHoFunctionBind ("HoFillHistogramFromTuple", (CiRoutine) HoFillHistogramFromTuple);
      CiBindHoFunctionBind ("HoAddConverter", (CiRoutine) HoAddConverter);
    }
  *switchFunction = (CiRoutine) CiBindHoSwitchFunction;
  return ((char*) cases);
}

/*- Procedure ------------------------------------------*/
static void CiBindHoSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue)
/*------------------------------------------------------*/
{
  CiPrimValueRec prim;
  
  prim.l = 0;
  
  switch (code)
  {
    case 6 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].p, args[2].i, args[3].p, 
                        args[4].p);
          }
          break;
      }
      break;
    case 9 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p, args[1].p, args[2].i, args[3].p, 
                                args[4].i, args[5].p);
          }
          break;
      }
      break;
    case 14 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g ();
          }
          break;
      }
      break;
    case 22 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p);
          }
          break;
      }
      break;
    case 34 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p, args[1].p, args[2].i, args[3].p, 
                                args[4].i, args[5].p, args[6].i);
          }
          break;
      }
      break;
    case 37 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p);
          }
          break;
      }
      break;
  }
  
  args = 0;
  position = 0;
  
  if (retValue) *retValue = prim;
}

/*--------------------------------------------
  This file has been generated by cigen       
  using the following command :               

  $CIBIN/cigen.exe -p -h stdarg.h -f OAxis.h -n CiBindOAxis -o ../gen/OAxis_B.c

--------------------------------------------*/

#include <stdarg.h>
#include <OAxis.h>

#ifndef __CI_SWITCH_DEFS__
#define __CI_SWITCH_DEFS__

#ifdef __cplusplus
#define SWITCH_ELLIPSIS ...
#else
#define SWITCH_ELLIPSIS 

#endif

#ifndef __CiDefs__

typedef void            (*CiRoutine)(SWITCH_ELLIPSIS);
typedef char            (*CiCRoutine)(SWITCH_ELLIPSIS);
typedef short           (*CiSRoutine)(SWITCH_ELLIPSIS);
typedef int             (*CiIRoutine)(SWITCH_ELLIPSIS);
typedef long            (*CiLRoutine)(SWITCH_ELLIPSIS);
typedef unsigned char   (*CiUCRoutine)(SWITCH_ELLIPSIS);
typedef unsigned short  (*CiUSRoutine)(SWITCH_ELLIPSIS);
typedef unsigned int    (*CiUIRoutine)(SWITCH_ELLIPSIS);
typedef unsigned long   (*CiULRoutine)(SWITCH_ELLIPSIS);
typedef float           (*CiFRoutine)(SWITCH_ELLIPSIS);
typedef double          (*CiDRoutine)(SWITCH_ELLIPSIS);
typedef void*           (*CiPRoutine)(SWITCH_ELLIPSIS);

#endif

#ifndef __CiType__

typedef union {
  char c;
  short s;
  int i;
  long l;
  char* p;
  float f;
  double d;
} CiPrimValueRec, *CiPrimValue;

#endif

#endif

#ifdef __cplusplus
extern "C" {
#endif

CiRoutine CiBindOAxis (char* library);

static void CiBindOAxisInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew);

static char* CiBindOAxisSetupFunction (CiRoutine* switchFunction);

static void CiBindOAxisSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue);
void CiBindOAxisCleanup ();

static CiRoutine CiBindOAxisFileCompile       = 0;
static CiRoutine CiBindOAxisFunctionBind      = 0;
static CiRoutine CiBindOAxisVariableBind      = 0;
static CiRoutine CiBindOAxisFunctionSwitchNew = 0;

#ifdef __cplusplus
}
#endif

/*- Procedure ------------------------------------------*/
CiRoutine CiBindOAxis (char* library)
/*------------------------------------------------------*/
{
  static int first = 1;

  if (first)
    {
      first = 0;
    }
  else if (CiBindOAxisFunctionSwitchNew)
    {
      CiBindOAxisFunctionSwitchNew ((CiRoutine) CiBindOAxisSetupFunction);
    }

  library = 0;

  return ((CiRoutine) CiBindOAxisInitFunction);
}

/*- Procedure ------------------------------------------*/
static void CiBindOAxisInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew)
/*------------------------------------------------------*/
{
  CiBindOAxisFileCompile       = compileFunction;
  pathFunction = 0;
  CiBindOAxisFunctionBind      = bindFunction;
  CiBindOAxisVariableBind      = bindVariable;
  CiBindOAxisFunctionSwitchNew = switchNew;
  CiBindOAxisVariableBind (0, 0);
  CiBindOAxisFunctionBind (0, 0);
}

/*- Procedure ------------------------------------------*/
static char* CiBindOAxisSetupFunction (CiRoutine* switchFunction)
/*------------------------------------------------------*/
{
  static char cases[] = {
    1, 6, 6, 0,
    6, 6, 4, 0,
    8, 6, 0,
    6, 0,
    6, 6, 0,
    1, 6, 8, 8, 0,
    8, 6, 4, 0,
    1, 6, 6, 6, 6, 0,
    4, 6, 4, 0,
    4, 6, 6, 0,
    4, 4, 0,
    1, 6, 6, 6, 0,
    4, 6, 0,
    1, 6, 0,
    0
  };
  static int first = 1;
  
  if (first)
    {
      first = 0;
  
      CiBindOAxisFileCompile ("stdarg.h");
      CiBindOAxisFileCompile ("OAxis.h");
      CiBindOAxisFunctionBind ("OAxisVerifyNumberOfBins", (CiRoutine) OAxisVerifyNumberOfBins);
      CiBindOAxisFunctionBind ("OAxisAdjust", (CiRoutine) OAxisAdjust);
      CiBindOAxisFunctionBind ("OAxisDelete", (CiRoutine) OAxisDelete);
      CiBindOAxisFunctionBind ("OAxisGetTitle", (CiRoutine) OAxisGetTitle);
      CiBindOAxisFunctionBind ("OAxisGetNumberOfTicks", (CiRoutine) OAxisGetNumberOfTicks);
      CiBindOAxisFunctionBind ("OAxisMake", (CiRoutine) OAxisMake);
      CiBindOAxisFunctionBind ("OAxisCopy", (CiRoutine) OAxisCopy);
      CiBindOAxisFunctionBind ("OAxisClear", (CiRoutine) OAxisClear);
      CiBindOAxisFunctionBind ("OAxisSetAttributesF", (CiRoutine) OAxisSetAttributesF);
      CiBindOAxisFunctionBind ("OAxisVerifyRange", (CiRoutine) OAxisVerifyRange);
      CiBindOAxisFunctionBind ("OAxisGetIthTickLabel", (CiRoutine) OAxisGetIthTickLabel);
      CiBindOAxisFunctionBind ("OAxisSetAttributesV", (CiRoutine) OAxisSetAttributesV);
      CiBindOAxisFunctionBind ("OAxisSetAttributes", (CiRoutine) OAxisSetAttributes);
      CiBindOAxisFunctionBind ("OAxisGetIthTickValue", (CiRoutine) OAxisGetIthTickValue);
      CiBindOAxisFunctionBind ("OAxisGetNumberOfBins", (CiRoutine) OAxisGetNumberOfBins);
      CiBindOAxisFunctionBind ("OAxisVerifyIndex", (CiRoutine) OAxisVerifyIndex);
      CiBindOAxisFunctionBind ("OAxisGetMaximumValue", (CiRoutine) OAxisGetMaximumValue);
      CiBindOAxisFunctionBind ("OAxisInitialize", (CiRoutine) OAxisInitialize);
      CiBindOAxisFunctionBind ("OAxisGetAttributesF", (CiRoutine) OAxisGetAttributesF);
      CiBindOAxisFunctionBind ("OAxisGetAttributesV", (CiRoutine) OAxisGetAttributesV);
      CiBindOAxisFunctionBind ("OAxisComputeTicks", (CiRoutine) OAxisComputeTicks);
      CiBindOAxisFunctionBind ("OAxisGetMinimumValue", (CiRoutine) OAxisGetMinimumValue);
    }
  *switchFunction = (CiRoutine) CiBindOAxisSwitchFunction;
  return ((char*) cases);
}

/*- Procedure ------------------------------------------*/
static void CiBindOAxisSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue)
/*------------------------------------------------------*/
{
  CiPrimValueRec prim;
  
  prim.l = 0;
  
  switch (code)
  {
    case 4 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p);
          }
          break;
      }
      break;
    case 7 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p, args[1].i);
          }
          break;
      }
      break;
    case 8 :
      switch (position)
      {
        case 1 :
          {
            CiDRoutine g = (CiDRoutine) f;

            prim.d = g (args[0].p);
          }
          break;
      }
      break;
    case 19 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g ();
          }
          break;
      }
      break;
    case 22 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p);
          }
          break;
      }
      break;
    case 23 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].d, args[2].d);
          }
          break;
      }
      break;
    case 25 :
      switch (position)
      {
        case 1 :
          {
            CiDRoutine g = (CiDRoutine) f;

            prim.d = g (args[0].p, args[1].i);
          }
          break;
      }
      break;
    case 26 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p, args[2].p, args[3].p);
          }
          break;
      }
      break;
    case 29 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].i);
          }
          break;
      }
      break;
    case 31 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].p);
          }
          break;
      }
      break;
    case 34 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].i);
          }
          break;
      }
      break;
    case 35 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p, args[2].p);
          }
          break;
      }
      break;
    case 36 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p);
          }
          break;
      }
      break;
    case 37 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p);
          }
          break;
      }
      break;
  }
  
  args = 0;
  position = 0;
  
  if (retValue) *retValue = prim;
}

/*--------------------------------------------
  This file has been generated by cigen       
  using the following command :               

  $CIBIN/cigen.exe -p -f OCut.h -n CiBindOCut -o ../gen/OCut_B.c

--------------------------------------------*/

#include <OCut.h>

#ifndef __CI_SWITCH_DEFS__
#define __CI_SWITCH_DEFS__

#ifdef __cplusplus
#define SWITCH_ELLIPSIS ...
#else
#define SWITCH_ELLIPSIS 

#endif

#ifndef __CiDefs__

typedef void            (*CiRoutine)(SWITCH_ELLIPSIS);
typedef char            (*CiCRoutine)(SWITCH_ELLIPSIS);
typedef short           (*CiSRoutine)(SWITCH_ELLIPSIS);
typedef int             (*CiIRoutine)(SWITCH_ELLIPSIS);
typedef long            (*CiLRoutine)(SWITCH_ELLIPSIS);
typedef unsigned char   (*CiUCRoutine)(SWITCH_ELLIPSIS);
typedef unsigned short  (*CiUSRoutine)(SWITCH_ELLIPSIS);
typedef unsigned int    (*CiUIRoutine)(SWITCH_ELLIPSIS);
typedef unsigned long   (*CiULRoutine)(SWITCH_ELLIPSIS);
typedef float           (*CiFRoutine)(SWITCH_ELLIPSIS);
typedef double          (*CiDRoutine)(SWITCH_ELLIPSIS);
typedef void*           (*CiPRoutine)(SWITCH_ELLIPSIS);

#endif

#ifndef __CiType__

typedef union {
  char c;
  short s;
  int i;
  long l;
  char* p;
  float f;
  double d;
} CiPrimValueRec, *CiPrimValue;

#endif

#endif

#ifdef __cplusplus
extern "C" {
#endif

CiRoutine CiBindOCut (char* library);

static void CiBindOCutInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew);

static char* CiBindOCutSetupFunction (CiRoutine* switchFunction);

static void CiBindOCutSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue);
void CiBindOCutCleanup ();

static CiRoutine CiBindOCutFileCompile       = 0;
static CiRoutine CiBindOCutFunctionBind      = 0;
static CiRoutine CiBindOCutVariableBind      = 0;
static CiRoutine CiBindOCutFunctionSwitchNew = 0;

#ifdef __cplusplus
}
#endif

/*- Procedure ------------------------------------------*/
CiRoutine CiBindOCut (char* library)
/*------------------------------------------------------*/
{
  static int first = 1;

  if (first)
    {
      first = 0;
    }
  else if (CiBindOCutFunctionSwitchNew)
    {
      CiBindOCutFunctionSwitchNew ((CiRoutine) CiBindOCutSetupFunction);
    }

  library = 0;

  return ((CiRoutine) CiBindOCutInitFunction);
}

/*- Procedure ------------------------------------------*/
static void CiBindOCutInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew)
/*------------------------------------------------------*/
{
  CiBindOCutFileCompile       = compileFunction;
  pathFunction = 0;
  CiBindOCutFunctionBind      = bindFunction;
  CiBindOCutVariableBind      = bindVariable;
  CiBindOCutFunctionSwitchNew = switchNew;
  CiBindOCutVariableBind (0, 0);
  CiBindOCutFunctionBind (0, 0);
}

/*- Procedure ------------------------------------------*/
static char* CiBindOCutSetupFunction (CiRoutine* switchFunction)
/*------------------------------------------------------*/
{
  static char cases[] = {
    4, 6, 4, 6, 0,
    1, 6, 6, 0,
    1, 6, 4, 6, 0,
    1, 0,
    6, 0,
    6, 6, 0,
    4, 6, 6, 6, 6, 4, 0,
    4, 6, 6, 6, 6, 6, 0,
    4, 6, 0,
    1, 6, 0,
    0
  };
  static int first = 1;
  
  if (first)
    {
      first = 0;
  
      CiBindOCutFileCompile ("OCut.h");
      CiBindOCutFunctionBind ("OCutMake", (CiRoutine) OCutMake);
      CiBindOCutFunctionBind ("OCutIsValid", (CiRoutine) OCutIsValid);
      CiBindOCutFunctionBind ("OCutGetName", (CiRoutine) OCutGetName);
      CiBindOCutFunctionBind ("OCutDelete", (CiRoutine) OCutDelete);
      CiBindOCutFunctionBind ("OCutSetColumns", (CiRoutine) OCutSetColumns);
      CiBindOCutFunctionBind ("OCutGetCurrentRow", (CiRoutine) OCutGetCurrentRow);
      CiBindOCutFunctionBind ("OCutGetAttribute", (CiRoutine) OCutGetAttribute);
      CiBindOCutFunctionBind ("OCutSetAttribute", (CiRoutine) OCutSetAttribute);
      CiBindOCutFunctionBind ("OCutSetScript", (CiRoutine) OCutSetScript);
      CiBindOCutFunctionBind ("OCutSetName", (CiRoutine) OCutSetName);
      CiBindOCutFunctionBind ("OCutGetScript", (CiRoutine) OCutGetScript);
      CiBindOCutFunctionBind ("OCutGetIdentifier", (CiRoutine) OCutGetIdentifier);
      CiBindOCutFunctionBind ("OCutIsRowAccepted", (CiRoutine) OCutIsRowAccepted);
      CiBindOCutFunctionBind ("OCutCreate", (CiRoutine) OCutCreate);
      CiBindOCutFunctionBind ("OCutGetIdentifiers", (CiRoutine) OCutGetIdentifiers);
      CiBindOCutFunctionBind ("OCutClearClass", (CiRoutine) OCutClearClass);
    }
  *switchFunction = (CiRoutine) CiBindOCutSwitchFunction;
  return ((char*) cases);
}

/*- Procedure ------------------------------------------*/
static void CiBindOCutSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue)
/*------------------------------------------------------*/
{
  CiPrimValueRec prim;
  
  prim.l = 0;
  
  switch (code)
  {
    case 0 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].i, args[2].p);
          }
          break;
      }
      break;
    case 4 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p);
          }
          break;
      }
      break;
    case 9 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].i, args[2].p);
          }
          break;
      }
      break;
    case 14 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g ();
          }
          break;
      }
      break;
    case 19 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g ();
          }
          break;
      }
      break;
    case 22 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p);
          }
          break;
        case 2 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].p, args[2].p, args[3].p, 
                        args[4].i);
          }
          break;
      }
      break;
    case 24 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].p, args[2].p, args[3].p, 
                        args[4].p);
          }
          break;
      }
      break;
    case 36 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p);
          }
          break;
      }
      break;
    case 37 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p);
          }
          break;
      }
      break;
  }
  
  args = 0;
  position = 0;
  
  if (retValue) *retValue = prim;
}

/*--------------------------------------------
  This file has been generated by cigen       
  using the following command :               

  $CIBIN/cigen.exe -p -f OFit.h -n CiBindOFit -o ../gen/OFit_B.c

--------------------------------------------*/

#include <OFit.h>

#ifndef __CI_SWITCH_DEFS__
#define __CI_SWITCH_DEFS__

#ifdef __cplusplus
#define SWITCH_ELLIPSIS ...
#else
#define SWITCH_ELLIPSIS 

#endif

#ifndef __CiDefs__

typedef void            (*CiRoutine)(SWITCH_ELLIPSIS);
typedef char            (*CiCRoutine)(SWITCH_ELLIPSIS);
typedef short           (*CiSRoutine)(SWITCH_ELLIPSIS);
typedef int             (*CiIRoutine)(SWITCH_ELLIPSIS);
typedef long            (*CiLRoutine)(SWITCH_ELLIPSIS);
typedef unsigned char   (*CiUCRoutine)(SWITCH_ELLIPSIS);
typedef unsigned short  (*CiUSRoutine)(SWITCH_ELLIPSIS);
typedef unsigned int    (*CiUIRoutine)(SWITCH_ELLIPSIS);
typedef unsigned long   (*CiULRoutine)(SWITCH_ELLIPSIS);
typedef float           (*CiFRoutine)(SWITCH_ELLIPSIS);
typedef double          (*CiDRoutine)(SWITCH_ELLIPSIS);
typedef void*           (*CiPRoutine)(SWITCH_ELLIPSIS);

#endif

#ifndef __CiType__

typedef union {
  char c;
  short s;
  int i;
  long l;
  char* p;
  float f;
  double d;
} CiPrimValueRec, *CiPrimValue;

#endif

#endif

#ifdef __cplusplus
extern "C" {
#endif

CiRoutine CiBindOFit (char* library);

static void CiBindOFitInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew);

static char* CiBindOFitSetupFunction (CiRoutine* switchFunction);

static void CiBindOFitSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue);
void CiBindOFitCleanup ();

static CiRoutine CiBindOFitFileCompile       = 0;
static CiRoutine CiBindOFitFunctionBind      = 0;
static CiRoutine CiBindOFitVariableBind      = 0;
static CiRoutine CiBindOFitFunctionSwitchNew = 0;

#ifdef __cplusplus
}
#endif

/*- Procedure ------------------------------------------*/
CiRoutine CiBindOFit (char* library)
/*------------------------------------------------------*/
{
  static int first = 1;

  if (first)
    {
      first = 0;
    }
  else if (CiBindOFitFunctionSwitchNew)
    {
      CiBindOFitFunctionSwitchNew ((CiRoutine) CiBindOFitSetupFunction);
    }

  library = 0;

  return ((CiRoutine) CiBindOFitInitFunction);
}

/*- Procedure ------------------------------------------*/
static void CiBindOFitInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew)
/*------------------------------------------------------*/
{
  CiBindOFitFileCompile       = compileFunction;
  pathFunction = 0;
  CiBindOFitFunctionBind      = bindFunction;
  CiBindOFitVariableBind      = bindVariable;
  CiBindOFitFunctionSwitchNew = switchNew;
  CiBindOFitVariableBind (0, 0);
  CiBindOFitFunctionBind (0, 0);
}

/*- Procedure ------------------------------------------*/
static char* CiBindOFitSetupFunction (CiRoutine* switchFunction)
/*------------------------------------------------------*/
{
  static char cases[] = {
    1, 6, 6, 4, 6, 0,
    1, 6, 4, 0,
    1, 6, 4, 6, 0,
    6, 6, 6, 0,
    4, 6, 4, 6, 6, 6, 0,
    6, 0,
    6, 4, 0,
    6, 6, 0,
    8, 6, 4, 0,
    8, 6, 8, 4, 6, 0,
    4, 6, 0,
    1, 6, 0,
    1, 6, 4, 4, 6, 6, 6, 4, 6, 6, 0,
    0
  };
  static int first = 1;
  
  if (first)
    {
      first = 0;
  
      CiBindOFitFileCompile ("OFit.h");
      CiBindOFitFunctionBind ("OFitTypeGetNames", (CiRoutine) OFitTypeGetNames);
      CiBindOFitFunctionBind ("OFitGetType", (CiRoutine) OFitGetType);
      CiBindOFitFunctionBind ("OFitTypeGetIdentifier", (CiRoutine) OFitTypeGetIdentifier);
      CiBindOFitFunctionBind ("OFitSetStartValues", (CiRoutine) OFitSetStartValues);
      CiBindOFitFunctionBind ("OFitSetSteps", (CiRoutine) OFitSetSteps);
      CiBindOFitFunctionBind ("OFitAreStartValuesAutomated", (CiRoutine) OFitAreStartValuesAutomated);
      CiBindOFitFunctionBind ("OFitBuildScript", (CiRoutine) OFitBuildScript);
      CiBindOFitFunctionBind ("OFitSetStepsAutomated", (CiRoutine) OFitSetStepsAutomated);
      CiBindOFitFunctionBind ("OFitDelete", (CiRoutine) OFitDelete);
      CiBindOFitFunctionBind ("OFitExecute", (CiRoutine) OFitExecute);
      CiBindOFitFunctionBind ("OFitSetNumberOfParameters", (CiRoutine) OFitSetNumberOfParameters);
      CiBindOFitFunctionBind ("OFitGetNumberOfParameters", (CiRoutine) OFitGetNumberOfParameters);
      CiBindOFitFunctionBind ("OFitGetIthStartValue", (CiRoutine) OFitGetIthStartValue);
      CiBindOFitFunctionBind ("OFitMake", (CiRoutine) OFitMake);
      CiBindOFitFunctionBind ("OFitSetType", (CiRoutine) OFitSetType);
      CiBindOFitFunctionBind ("OFitEvaluateScript", (CiRoutine) OFitEvaluateScript);
      CiBindOFitFunctionBind ("OFitGetVariableNames", (CiRoutine) OFitGetVariableNames);
      CiBindOFitFunctionBind ("OFitAreStepsAutomated", (CiRoutine) OFitAreStepsAutomated);
      CiBindOFitFunctionBind ("OFitSetStartValuesAutomated", (CiRoutine) OFitSetStartValuesAutomated);
      CiBindOFitFunctionBind ("OFitGetScript", (CiRoutine) OFitGetScript);
      CiBindOFitFunctionBind ("OFitSetFitFunction", (CiRoutine) OFitSetFitFunction);
      CiBindOFitFunctionBind ("OFitGetIthStep", (CiRoutine) OFitGetIthStep);
      CiBindOFitFunctionBind ("OFitSetScript", (CiRoutine) OFitSetScript);
      CiBindOFitFunctionBind ("OFitGetInformations", (CiRoutine) OFitGetInformations);
      CiBindOFitFunctionBind ("OFitTypeGetName", (CiRoutine) OFitTypeGetName);
    }
  *switchFunction = (CiRoutine) CiBindOFitSwitchFunction;
  return ((char*) cases);
}

/*- Procedure ------------------------------------------*/
static void CiBindOFitSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue)
/*------------------------------------------------------*/
{
  CiPrimValueRec prim;
  
  prim.l = 0;
  
  switch (code)
  {
    case 0 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p, args[2].i, args[3].p);
          }
          break;
      }
      break;
    case 2 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].i);
          }
          break;
      }
      break;
    case 9 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].i, args[2].p);
          }
          break;
        case 2 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p, args[1].p);
          }
          break;
      }
      break;
    case 14 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].i, args[2].p, args[3].p, 
                        args[4].p);
          }
          break;
      }
      break;
    case 19 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g ();
          }
          break;
      }
      break;
    case 20 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].i);
          }
          break;
      }
      break;
    case 22 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p);
          }
          break;
      }
      break;
    case 25 :
      switch (position)
      {
        case 1 :
          {
            CiDRoutine g = (CiDRoutine) f;

            prim.d = g (args[0].p, args[1].i);
          }
          break;
        case 2 :
          {
            CiDRoutine g = (CiDRoutine) f;

            prim.d = g (args[0].p, args[1].d, args[2].i, args[3].p);
          }
          break;
      }
      break;
    case 36 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p);
          }
          break;
      }
      break;
    case 37 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p);
          }
          break;
      }
      break;
    case 39 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].i, args[2].i, args[3].p, 
               args[4].p, args[5].p, args[6].i, args[7].p, 
               args[8].p);
          }
          break;
      }
      break;
  }
  
  args = 0;
  position = 0;
  
  if (retValue) *retValue = prim;
}

/*--------------------------------------------
  This file has been generated by cigen       
  using the following command :               

  $CIBIN/cigen.exe -p -h OAxis.h -f OFunction.h -n CiBindOFunction -o ../gen/OFunction_B.c

--------------------------------------------*/

#include <OAxis.h>
#include <OFunction.h>

#ifndef __CI_SWITCH_DEFS__
#define __CI_SWITCH_DEFS__

#ifdef __cplusplus
#define SWITCH_ELLIPSIS ...
#else
#define SWITCH_ELLIPSIS 

#endif

#ifndef __CiDefs__

typedef void            (*CiRoutine)(SWITCH_ELLIPSIS);
typedef char            (*CiCRoutine)(SWITCH_ELLIPSIS);
typedef short           (*CiSRoutine)(SWITCH_ELLIPSIS);
typedef int             (*CiIRoutine)(SWITCH_ELLIPSIS);
typedef long            (*CiLRoutine)(SWITCH_ELLIPSIS);
typedef unsigned char   (*CiUCRoutine)(SWITCH_ELLIPSIS);
typedef unsigned short  (*CiUSRoutine)(SWITCH_ELLIPSIS);
typedef unsigned int    (*CiUIRoutine)(SWITCH_ELLIPSIS);
typedef unsigned long   (*CiULRoutine)(SWITCH_ELLIPSIS);
typedef float           (*CiFRoutine)(SWITCH_ELLIPSIS);
typedef double          (*CiDRoutine)(SWITCH_ELLIPSIS);
typedef void*           (*CiPRoutine)(SWITCH_ELLIPSIS);

#endif

#ifndef __CiType__

typedef union {
  char c;
  short s;
  int i;
  long l;
  char* p;
  float f;
  double d;
} CiPrimValueRec, *CiPrimValue;

#endif

#endif

#ifdef __cplusplus
extern "C" {
#endif

CiRoutine CiBindOFunction (char* library);

static void CiBindOFunctionInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew);

static char* CiBindOFunctionSetupFunction (CiRoutine* switchFunction);

static void CiBindOFunctionSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue);
void CiBindOFunctionCleanup ();

static CiRoutine CiBindOFunctionFileCompile       = 0;
static CiRoutine CiBindOFunctionFunctionBind      = 0;
static CiRoutine CiBindOFunctionVariableBind      = 0;
static CiRoutine CiBindOFunctionFunctionSwitchNew = 0;

#ifdef __cplusplus
}
#endif

/*- Procedure ------------------------------------------*/
CiRoutine CiBindOFunction (char* library)
/*------------------------------------------------------*/
{
  static int first = 1;

  if (first)
    {
      first = 0;
    }
  else if (CiBindOFunctionFunctionSwitchNew)
    {
      CiBindOFunctionFunctionSwitchNew ((CiRoutine) CiBindOFunctionSetupFunction);
    }

  library = 0;

  return ((CiRoutine) CiBindOFunctionInitFunction);
}

/*- Procedure ------------------------------------------*/
static void CiBindOFunctionInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew)
/*------------------------------------------------------*/
{
  CiBindOFunctionFileCompile       = compileFunction;
  pathFunction = 0;
  CiBindOFunctionFunctionBind      = bindFunction;
  CiBindOFunctionVariableBind      = bindVariable;
  CiBindOFunctionFunctionSwitchNew = switchNew;
  CiBindOFunctionVariableBind (0, 0);
  CiBindOFunctionFunctionBind (0, 0);
}

/*- Procedure ------------------------------------------*/
static char* CiBindOFunctionSetupFunction (CiRoutine* switchFunction)
/*------------------------------------------------------*/
{
  static char cases[] = {
    4, 6, 4, 6, 0,
    1, 6, 4, 0,
    1, 6, 6, 0,
    8, 6, 4, 6, 0,
    6, 6, 4, 0,
    1, 6, 4, 6, 0,
    1, 0,
    6, 0,
    6, 6, 0,
    8, 6, 4, 0,
    1, 6, 6, 6, 0,
    4, 6, 0,
    1, 6, 0,
    0
  };
  static int first = 1;
  
  if (first)
    {
      first = 0;
  
      CiBindOFunctionFileCompile ("OAxis.h");
      CiBindOFunctionFileCompile ("OFunction.h");
      CiBindOFunctionFunctionBind ("OFunctionGetIdentifier", (CiRoutine) OFunctionGetIdentifier);
      CiBindOFunctionFunctionBind ("OFunctionMake", (CiRoutine) OFunctionMake);
      CiBindOFunctionFunctionBind ("OFunctionSetScript", (CiRoutine) OFunctionSetScript);
      CiBindOFunctionFunctionBind ("OFunctionEvaluate", (CiRoutine) OFunctionEvaluate);
      CiBindOFunctionFunctionBind ("OFunctionClearClass", (CiRoutine) OFunctionClearClass);
      CiBindOFunctionFunctionBind ("OFunctionCreate", (CiRoutine) OFunctionCreate);
      CiBindOFunctionFunctionBind ("OFunctionIsValid", (CiRoutine) OFunctionIsValid);
      CiBindOFunctionFunctionBind ("OFunctionGetName", (CiRoutine) OFunctionGetName);
      CiBindOFunctionFunctionBind ("OFunctionGetIthAxisAttributesF", (CiRoutine) OFunctionGetIthAxisAttributesF);
      CiBindOFunctionFunctionBind ("OFunctionSetVariable", (CiRoutine) OFunctionSetVariable);
      CiBindOFunctionFunctionBind ("OFunctionGetDimension", (CiRoutine) OFunctionGetDimension);
      CiBindOFunctionFunctionBind ("OFunctionGetRange", (CiRoutine) OFunctionGetRange);
      CiBindOFunctionFunctionBind ("OFunctionAdjustAxisOfValues", (CiRoutine) OFunctionAdjustAxisOfValues);
      CiBindOFunctionFunctionBind ("OFunctionEvaluateF", (CiRoutine) OFunctionEvaluateF);
      CiBindOFunctionFunctionBind ("OFunctionGetIthAxis", (CiRoutine) OFunctionGetIthAxis);
      CiBindOFunctionFunctionBind ("OFunctionDelete", (CiRoutine) OFunctionDelete);
      CiBindOFunctionFunctionBind ("OFunctionSetDimension", (CiRoutine) OFunctionSetDimension);
      CiBindOFunctionFunctionBind ("OFunctionGetScript", (CiRoutine) OFunctionGetScript);
      CiBindOFunctionFunctionBind ("OFunctionSetIthAxisAttributesF", (CiRoutine) OFunctionSetIthAxisAttributesF);
    }
  *switchFunction = (CiRoutine) CiBindOFunctionSwitchFunction;
  return ((char*) cases);
}

/*- Procedure ------------------------------------------*/
static void CiBindOFunctionSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue)
/*------------------------------------------------------*/
{
  CiPrimValueRec prim;
  
  prim.l = 0;
  
  switch (code)
  {
    case 0 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].i, args[2].p);
          }
          break;
      }
      break;
    case 2 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].i);
          }
          break;
      }
      break;
    case 4 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p);
          }
          break;
        case 2 :
          {
            CiDRoutine g = (CiDRoutine) f;

            prim.d = g (args[0].p, args[1].i, args[2].p);
          }
          break;
      }
      break;
    case 7 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p, args[1].i);
          }
          break;
      }
      break;
    case 9 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].i, args[2].p);
          }
          break;
      }
      break;
    case 14 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g ();
          }
          break;
      }
      break;
    case 19 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g ();
          }
          break;
      }
      break;
    case 22 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p);
          }
          break;
      }
      break;
    case 25 :
      switch (position)
      {
        case 1 :
          {
            CiDRoutine g = (CiDRoutine) f;

            prim.d = g (args[0].p, args[1].i);
          }
          break;
      }
      break;
    case 35 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p, args[2].p);
          }
          break;
      }
      break;
    case 36 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p);
          }
          break;
      }
      break;
    case 37 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p);
          }
          break;
      }
      break;
  }
  
  args = 0;
  position = 0;
  
  if (retValue) *retValue = prim;
}

/*--------------------------------------------
  This file has been generated by cigen       
  using the following command :               

  $CIBIN/cigen.exe -p -h OAxis.h -f OHistogram.h -n CiBindOHistogram -o ../gen/OHistogram_B.c

--------------------------------------------*/

#include <OAxis.h>
#include <OHistogram.h>

#ifndef __CI_SWITCH_DEFS__
#define __CI_SWITCH_DEFS__

#ifdef __cplusplus
#define SWITCH_ELLIPSIS ...
#else
#define SWITCH_ELLIPSIS 

#endif

#ifndef __CiDefs__

typedef void            (*CiRoutine)(SWITCH_ELLIPSIS);
typedef char            (*CiCRoutine)(SWITCH_ELLIPSIS);
typedef short           (*CiSRoutine)(SWITCH_ELLIPSIS);
typedef int             (*CiIRoutine)(SWITCH_ELLIPSIS);
typedef long            (*CiLRoutine)(SWITCH_ELLIPSIS);
typedef unsigned char   (*CiUCRoutine)(SWITCH_ELLIPSIS);
typedef unsigned short  (*CiUSRoutine)(SWITCH_ELLIPSIS);
typedef unsigned int    (*CiUIRoutine)(SWITCH_ELLIPSIS);
typedef unsigned long   (*CiULRoutine)(SWITCH_ELLIPSIS);
typedef float           (*CiFRoutine)(SWITCH_ELLIPSIS);
typedef double          (*CiDRoutine)(SWITCH_ELLIPSIS);
typedef void*           (*CiPRoutine)(SWITCH_ELLIPSIS);

#endif

#ifndef __CiType__

typedef union {
  char c;
  short s;
  int i;
  long l;
  char* p;
  float f;
  double d;
} CiPrimValueRec, *CiPrimValue;

#endif

#endif

#ifdef __cplusplus
extern "C" {
#endif

CiRoutine CiBindOHistogram (char* library);

static void CiBindOHistogramInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew);

static char* CiBindOHistogramSetupFunction (CiRoutine* switchFunction);

static void CiBindOHistogramSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue);
void CiBindOHistogramCleanup ();

static CiRoutine CiBindOHistogramFileCompile       = 0;
static CiRoutine CiBindOHistogramFunctionBind      = 0;
static CiRoutine CiBindOHistogramVariableBind      = 0;
static CiRoutine CiBindOHistogramFunctionSwitchNew = 0;

#ifdef __cplusplus
}
#endif

/*- Procedure ------------------------------------------*/
CiRoutine CiBindOHistogram (char* library)
/*------------------------------------------------------*/
{
  static int first = 1;

  if (first)
    {
      first = 0;
    }
  else if (CiBindOHistogramFunctionSwitchNew)
    {
      CiBindOHistogramFunctionSwitchNew ((CiRoutine) CiBindOHistogramSetupFunction);
    }

  library = 0;

  return ((CiRoutine) CiBindOHistogramInitFunction);
}

/*- Procedure ------------------------------------------*/
static void CiBindOHistogramInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew)
/*------------------------------------------------------*/
{
  CiBindOHistogramFileCompile       = compileFunction;
  pathFunction = 0;
  CiBindOHistogramFunctionBind      = bindFunction;
  CiBindOHistogramVariableBind      = bindVariable;
  CiBindOHistogramFunctionSwitchNew = switchNew;
  CiBindOHistogramVariableBind (0, 0);
  CiBindOHistogramFunctionBind (0, 0);
}

/*- Procedure ------------------------------------------*/
static char* CiBindOHistogramSetupFunction (CiRoutine* switchFunction)
/*------------------------------------------------------*/
{
  static char cases[] = {
    4, 6, 4, 6, 0,
    1, 6, 4, 0,
    8, 6, 4, 4, 0,
    4, 6, 4, 8, 0,
    1, 6, 6, 0,
    1, 6, 8, 0,
    1, 6, 4, 4, 0,
    6, 6, 4, 0,
    8, 6, 0,
    1, 6, 4, 6, 0,
    1, 6, 4, 8, 0,
    1, 0,
    6, 0,
    4, 6, 6, 6, 4, 6, 6, 6, 0,
    4, 6, 6, 6, 4, 8, 8, 0,
    6, 6, 0,
    4, 6, 6, 6, 6, 4, 0,
    1, 6, 8, 8, 0,
    4, 6, 4, 6, 6, 6, 6, 6, 6, 0,
    4, 6, 6, 6, 6, 6, 0,
    8, 6, 4, 0,
    4, 6, 6, 6, 0,
    4, 6, 4, 0,
    1, 6, 8, 8, 8, 0,
    1, 6, 6, 6, 0,
    4, 6, 0,
    1, 6, 6, 8, 0,
    1, 6, 0,
    0
  };
  static int first = 1;
  
  if (first)
    {
      first = 0;
  
      CiBindOHistogramFileCompile ("OAxis.h");
      CiBindOHistogramFileCompile ("OHistogram.h");
      CiBindOHistogramFunctionBind ("OHistogramGetIdentifiers", (CiRoutine) OHistogramGetIdentifiers);
      CiBindOHistogramFunctionBind ("OHistogramIsProfile", (CiRoutine) OHistogramIsProfile);
      CiBindOHistogramFunctionBind ("OHistogramGetIthAxisStandardDeviation", (CiRoutine) OHistogramGetIthAxisStandardDeviation);
      CiBindOHistogramFunctionBind ("OHistogramGetSumOfWeights", (CiRoutine) OHistogramGetSumOfWeights);
      CiBindOHistogramFunctionBind ("OHistogramGetIdentifier", (CiRoutine) OHistogramGetIdentifier);
      CiBindOHistogramFunctionBind ("OHistogramFindLastNotEmptyBin", (CiRoutine) OHistogramFindLastNotEmptyBin);
      CiBindOHistogramFunctionBind ("OHistogramSetNumberOfEntries", (CiRoutine) OHistogramSetNumberOfEntries);
      CiBindOHistogramFunctionBind ("OHistogramFillTwoDimensional", (CiRoutine) OHistogramFillTwoDimensional);
      CiBindOHistogramFunctionBind ("OHistogramMake", (CiRoutine) OHistogramMake);
      CiBindOHistogramFunctionBind ("OHistogramSetMonitoringMode", (CiRoutine) OHistogramSetMonitoringMode);
      CiBindOHistogramFunctionBind ("OHistogramSetTitle", (CiRoutine) OHistogramSetTitle);
      CiBindOHistogramFunctionBind ("OHistogramGetIthAxisBinMinimum", (CiRoutine) OHistogramGetIthAxisBinMinimum);
      CiBindOHistogramFunctionBind ("OHistogramSetAttribute", (CiRoutine) OHistogramSetAttribute);
      CiBindOHistogramFunctionBind ("OHistogramSetIthAxisUnderflow", (CiRoutine) OHistogramSetIthAxisUnderflow);
      CiBindOHistogramFunctionBind ("OHistogramGetTitle", (CiRoutine) OHistogramGetTitle);
      CiBindOHistogramFunctionBind ("OHistogramGetHalfLowerMeanPoint", (CiRoutine) OHistogramGetHalfLowerMeanPoint);
      CiBindOHistogramFunctionBind ("OHistogramClearClass", (CiRoutine) OHistogramClearClass);
      CiBindOHistogramFunctionBind ("OHistogramAdjustAxisOfValues", (CiRoutine) OHistogramAdjustAxisOfValues);
      CiBindOHistogramFunctionBind ("OHistogramGetIthAxisSumOfWeightedCoordinates", (CiRoutine) OHistogramGetIthAxisSumOfWeightedCoordinates);
      CiBindOHistogramFunctionBind ("OHistogramFillOneDimensional", (CiRoutine) OHistogramFillOneDimensional);
      CiBindOHistogramFunctionBind ("OHistogramSetIthAxisAttributesF", (CiRoutine) OHistogramSetIthAxisAttributesF);
      CiBindOHistogramFunctionBind ("OHistogramGetIthAxisAttributesF", (CiRoutine) OHistogramGetIthAxisAttributesF);
      CiBindOHistogramFunctionBind ("OHistogramSetDimension", (CiRoutine) OHistogramSetDimension);
      CiBindOHistogramFunctionBind ("OHistogramFillFromArray", (CiRoutine) OHistogramFillFromArray);
      CiBindOHistogramFunctionBind ("OHistogramGetBinBar", (CiRoutine) OHistogramGetBinBar);
      CiBindOHistogramFunctionBind ("OHistogramGetIthAxisMeanValue", (CiRoutine) OHistogramGetIthAxisMeanValue);
      CiBindOHistogramFunctionBind ("OHistogramDoProfile", (CiRoutine) OHistogramDoProfile);
      CiBindOHistogramFunctionBind ("OHistogramFindFirstEmptyBin", (CiRoutine) OHistogramFindFirstEmptyBin);
      CiBindOHistogramFunctionBind ("OHistogramGetIthAxisUnderflow", (CiRoutine) OHistogramGetIthAxisUnderflow);
      CiBindOHistogramFunctionBind ("OHistogramDelete", (CiRoutine) OHistogramDelete);
      CiBindOHistogramFunctionBind ("OHistogramSetBinSumOfSquaredWeights", (CiRoutine) OHistogramSetBinSumOfSquaredWeights);
      CiBindOHistogramFunctionBind ("OHistogramFill", (CiRoutine) OHistogramFill);
      CiBindOHistogramFunctionBind ("OHistogramSetAxisOfValuesTitle", (CiRoutine) OHistogramSetAxisOfValuesTitle);
      CiBindOHistogramFunctionBind ("OHistogramIsValid", (CiRoutine) OHistogramIsValid);
      CiBindOHistogramFunctionBind ("OHistogramGetName", (CiRoutine) OHistogramGetName);
      CiBindOHistogramFunctionBind ("OHistogramAllocateMemory", (CiRoutine) OHistogramAllocateMemory);
      CiBindOHistogramFunctionBind ("OHistogramAddContents", (CiRoutine) OHistogramAddContents);
      CiBindOHistogramFunctionBind ("OHistogramSetProfile", (CiRoutine) OHistogramSetProfile);
      CiBindOHistogramFunctionBind ("OHistogramGetIthAxisBinMiddle", (CiRoutine) OHistogramGetIthAxisBinMiddle);
      CiBindOHistogramFunctionBind ("OHistogramSetBinNumberOfEntries", (CiRoutine) OHistogramSetBinNumberOfEntries);
      CiBindOHistogramFunctionBind ("OHistogramSetUserData", (CiRoutine) OHistogramSetUserData);
      CiBindOHistogramFunctionBind ("OHistogramDump", (CiRoutine) OHistogramDump);
      CiBindOHistogramFunctionBind ("OHistogramGetBinsRange", (CiRoutine) OHistogramGetBinsRange);
      CiBindOHistogramFunctionBind ("OHistogramGetBinNumberOfEntries", (CiRoutine) OHistogramGetBinNumberOfEntries);
      CiBindOHistogramFunctionBind ("OHistogramClear", (CiRoutine) OHistogramClear);
      CiBindOHistogramFunctionBind ("OHistogramGetAxisOfValuesTitle", (CiRoutine) OHistogramGetAxisOfValuesTitle);
      CiBindOHistogramFunctionBind ("OHistogramGetDimensions", (CiRoutine) OHistogramGetDimensions);
      CiBindOHistogramFunctionBind ("OHistogramGetBinSumOfWeightsRange", (CiRoutine) OHistogramGetBinSumOfWeightsRange);
      CiBindOHistogramFunctionBind ("OHistogramGetIthAxisBinIndex", (CiRoutine) OHistogramGetIthAxisBinIndex);
      CiBindOHistogramFunctionBind ("OHistogramConfigure", (CiRoutine) OHistogramConfigure);
      CiBindOHistogramFunctionBind ("OHistogramGetBinSumOfWeights", (CiRoutine) OHistogramGetBinSumOfWeights);
      CiBindOHistogramFunctionBind ("OHistogramSetBarsType", (CiRoutine) OHistogramSetBarsType);
      CiBindOHistogramFunctionBind ("OHistogramGetIthAxis", (CiRoutine) OHistogramGetIthAxis);
      CiBindOHistogramFunctionBind ("OHistogramGetMonitoringMode", (CiRoutine) OHistogramGetMonitoringMode);
      CiBindOHistogramFunctionBind ("OHistogramDoMethod", (CiRoutine) OHistogramDoMethod);
      CiBindOHistogramFunctionBind ("OHistogramGetIthAxisBinWidth", (CiRoutine) OHistogramGetIthAxisBinWidth);
      CiBindOHistogramFunctionBind ("OHistogramGetHalfUpperMeanPoint", (CiRoutine) OHistogramGetHalfUpperMeanPoint);
      CiBindOHistogramFunctionBind ("OHistogramGetIthAxisBinMaximum", (CiRoutine) OHistogramGetIthAxisBinMaximum);
      CiBindOHistogramFunctionBind ("OHistogramSetSumOfWeights", (CiRoutine) OHistogramSetSumOfWeights);
      CiBindOHistogramFunctionBind ("OHistogramGetIthAxisSumOfWeightedSquaredCoordinates", (CiRoutine) OHistogramGetIthAxisSumOfWeightedSquaredCoordinates);
      CiBindOHistogramFunctionBind ("OHistogramGetAttribute", (CiRoutine) OHistogramGetAttribute);
      CiBindOHistogramFunctionBind ("OHistogramIsBarsType", (CiRoutine) OHistogramIsBarsType);
      CiBindOHistogramFunctionBind ("OHistogramSetIthAxisSumOfWeightedSquaredCoordinates", (CiRoutine) OHistogramSetIthAxisSumOfWeightedSquaredCoordinates);
      CiBindOHistogramFunctionBind ("OHistogramSetIthAxisOverflow", (CiRoutine) OHistogramSetIthAxisOverflow);
      CiBindOHistogramFunctionBind ("OHistogramSetName", (CiRoutine) OHistogramSetName);
      CiBindOHistogramFunctionBind ("OHistogramGetNumberOfEntries", (CiRoutine) OHistogramGetNumberOfEntries);
      CiBindOHistogramFunctionBind ("OHistogramSetBinSumOfWeights", (CiRoutine) OHistogramSetBinSumOfWeights);
      CiBindOHistogramFunctionBind ("OHistogramCreate", (CiRoutine) OHistogramCreate);
      CiBindOHistogramFunctionBind ("OHistogramGetDimension", (CiRoutine) OHistogramGetDimension);
      CiBindOHistogramFunctionBind ("OHistogramGetBinSumOfSquaredWeights", (CiRoutine) OHistogramGetBinSumOfSquaredWeights);
      CiBindOHistogramFunctionBind ("OHistogramGetIthAxisOverflow", (CiRoutine) OHistogramGetIthAxisOverflow);
      CiBindOHistogramFunctionBind ("OHistogramOperateBinary", (CiRoutine) OHistogramOperateBinary);
      CiBindOHistogramFunctionBind ("OHistogramGetUserData", (CiRoutine) OHistogramGetUserData);
      CiBindOHistogramFunctionBind ("OHistogramFindFirstNotEmptyBin", (CiRoutine) OHistogramFindFirstNotEmptyBin);
      CiBindOHistogramFunctionBind ("OHistogramSetIthAxisSumOfWeightedCoordinates", (CiRoutine) OHistogramSetIthAxisSumOfWeightedCoordinates);
    }
  *switchFunction = (CiRoutine) CiBindOHistogramSwitchFunction;
  return ((char*) cases);
}

/*- Procedure ------------------------------------------*/
static void CiBindOHistogramSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue)
/*------------------------------------------------------*/
{
  CiPrimValueRec prim;
  
  prim.l = 0;
  
  switch (code)
  {
    case 0 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].i, args[2].p);
          }
          break;
      }
      break;
    case 2 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].i);
          }
          break;
        case 2 :
          {
            CiDRoutine g = (CiDRoutine) f;

            prim.d = g (args[0].p, args[1].i, args[2].i);
          }
          break;
        case 3 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].i, args[2].d);
          }
          break;
      }
      break;
    case 4 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p);
          }
          break;
      }
      break;
    case 6 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].d);
          }
          break;
      }
      break;
    case 7 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].i, args[2].i);
          }
          break;
        case 2 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p, args[1].i);
          }
          break;
      }
      break;
    case 8 :
      switch (position)
      {
        case 1 :
          {
            CiDRoutine g = (CiDRoutine) f;

            prim.d = g (args[0].p);
          }
          break;
      }
      break;
    case 9 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].i, args[2].p);
          }
          break;
      }
      break;
    case 11 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].i, args[2].d);
          }
          break;
      }
      break;
    case 14 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g ();
          }
          break;
      }
      break;
    case 19 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g ();
          }
          break;
      }
      break;
    case 20 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].p, args[2].p, args[3].i, 
                        args[4].p, args[5].p, args[6].p);
          }
          break;
      }
      break;
    case 21 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].p, args[2].p, args[3].i, 
                        args[4].d, args[5].d);
          }
          break;
      }
      break;
    case 22 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p);
          }
          break;
        case 2 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].p, args[2].p, args[3].p, 
                        args[4].i);
          }
          break;
      }
      break;
    case 23 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].d, args[2].d);
          }
          break;
        case 2 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].i, args[2].p, args[3].p, 
                        args[4].p, args[5].p, args[6].p, args[7].p);
          }
          break;
      }
      break;
    case 24 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].p, args[2].p, args[3].p, 
                        args[4].p);
          }
          break;
      }
      break;
    case 25 :
      switch (position)
      {
        case 1 :
          {
            CiDRoutine g = (CiDRoutine) f;

            prim.d = g (args[0].p, args[1].i);
          }
          break;
      }
      break;
    case 26 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].p, args[2].p);
          }
          break;
      }
      break;
    case 29 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].i);
          }
          break;
      }
      break;
    case 32 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].d, args[2].d, args[3].d);
          }
          break;
      }
      break;
    case 35 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p, args[2].p);
          }
          break;
      }
      break;
    case 36 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p);
          }
          break;
      }
      break;
    case 37 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p, args[2].d);
          }
          break;
        case 2 :
          {
            CiRoutine g = f;

            g (args[0].p);
          }
          break;
      }
      break;
  }
  
  args = 0;
  position = 0;
  
  if (retValue) *retValue = prim;
}

/*--------------------------------------------
  This file has been generated by cigen       
  using the following command :               

  $CIBIN/cigen.exe -p -h OAxis.h -f OScatter.h -n CiBindOScatter -o ../gen/OScatter_B.c

--------------------------------------------*/

#include <OAxis.h>
#include <OScatter.h>

#ifndef __CI_SWITCH_DEFS__
#define __CI_SWITCH_DEFS__

#ifdef __cplusplus
#define SWITCH_ELLIPSIS ...
#else
#define SWITCH_ELLIPSIS 

#endif

#ifndef __CiDefs__

typedef void            (*CiRoutine)(SWITCH_ELLIPSIS);
typedef char            (*CiCRoutine)(SWITCH_ELLIPSIS);
typedef short           (*CiSRoutine)(SWITCH_ELLIPSIS);
typedef int             (*CiIRoutine)(SWITCH_ELLIPSIS);
typedef long            (*CiLRoutine)(SWITCH_ELLIPSIS);
typedef unsigned char   (*CiUCRoutine)(SWITCH_ELLIPSIS);
typedef unsigned short  (*CiUSRoutine)(SWITCH_ELLIPSIS);
typedef unsigned int    (*CiUIRoutine)(SWITCH_ELLIPSIS);
typedef unsigned long   (*CiULRoutine)(SWITCH_ELLIPSIS);
typedef float           (*CiFRoutine)(SWITCH_ELLIPSIS);
typedef double          (*CiDRoutine)(SWITCH_ELLIPSIS);
typedef void*           (*CiPRoutine)(SWITCH_ELLIPSIS);

#endif

#ifndef __CiType__

typedef union {
  char c;
  short s;
  int i;
  long l;
  char* p;
  float f;
  double d;
} CiPrimValueRec, *CiPrimValue;

#endif

#endif

#ifdef __cplusplus
extern "C" {
#endif

CiRoutine CiBindOScatter (char* library);

static void CiBindOScatterInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew);

static char* CiBindOScatterSetupFunction (CiRoutine* switchFunction);

static void CiBindOScatterSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue);
void CiBindOScatterCleanup ();

static CiRoutine CiBindOScatterFileCompile       = 0;
static CiRoutine CiBindOScatterFunctionBind      = 0;
static CiRoutine CiBindOScatterVariableBind      = 0;
static CiRoutine CiBindOScatterFunctionSwitchNew = 0;

#ifdef __cplusplus
}
#endif

/*- Procedure ------------------------------------------*/
CiRoutine CiBindOScatter (char* library)
/*------------------------------------------------------*/
{
  static int first = 1;

  if (first)
    {
      first = 0;
    }
  else if (CiBindOScatterFunctionSwitchNew)
    {
      CiBindOScatterFunctionSwitchNew ((CiRoutine) CiBindOScatterSetupFunction);
    }

  library = 0;

  return ((CiRoutine) CiBindOScatterInitFunction);
}

/*- Procedure ------------------------------------------*/
static void CiBindOScatterInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew)
/*------------------------------------------------------*/
{
  CiBindOScatterFileCompile       = compileFunction;
  pathFunction = 0;
  CiBindOScatterFunctionBind      = bindFunction;
  CiBindOScatterVariableBind      = bindVariable;
  CiBindOScatterFunctionSwitchNew = switchNew;
  CiBindOScatterVariableBind (0, 0);
  CiBindOScatterFunctionBind (0, 0);
}

/*- Procedure ------------------------------------------*/
static char* CiBindOScatterSetupFunction (CiRoutine* switchFunction)
/*------------------------------------------------------*/
{
  static char cases[] = {
    4, 6, 4, 6, 0,
    1, 6, 4, 0,
    1, 6, 6, 0,
    1, 6, 8, 0,
    1, 6, 4, 4, 0,
    6, 6, 4, 0,
    1, 6, 4, 6, 0,
    1, 0,
    6, 0,
    6, 6, 0,
    4, 6, 6, 6, 6, 4, 0,
    1, 6, 8, 8, 0,
    4, 6, 6, 6, 6, 6, 0,
    8, 6, 4, 0,
    4, 6, 4, 0,
    1, 6, 8, 8, 8, 0,
    4, 6, 0,
    1, 6, 0,
    0
  };
  static int first = 1;
  
  if (first)
    {
      first = 0;
  
      CiBindOScatterFileCompile ("OAxis.h");
      CiBindOScatterFileCompile ("OScatter.h");
      CiBindOScatterFunctionBind ("OScatterGetIthAxisOverflow", (CiRoutine) OScatterGetIthAxisOverflow);
      CiBindOScatterFunctionBind ("OScatterGetTitle", (CiRoutine) OScatterGetTitle);
      CiBindOScatterFunctionBind ("OScatterFill", (CiRoutine) OScatterFill);
      CiBindOScatterFunctionBind ("OScatterSetIthAxisOverflow", (CiRoutine) OScatterSetIthAxisOverflow);
      CiBindOScatterFunctionBind ("OScatterGetIthAxisStandardDeviation", (CiRoutine) OScatterGetIthAxisStandardDeviation);
      CiBindOScatterFunctionBind ("OScatterGetIthAxisUnderflow", (CiRoutine) OScatterGetIthAxisUnderflow);
      CiBindOScatterFunctionBind ("OScatterFillOneDimensional", (CiRoutine) OScatterFillOneDimensional);
      CiBindOScatterFunctionBind ("OScatterConfigure", (CiRoutine) OScatterConfigure);
      CiBindOScatterFunctionBind ("OScatterGetIthAxisAttributesF", (CiRoutine) OScatterGetIthAxisAttributesF);
      CiBindOScatterFunctionBind ("OScatterDump", (CiRoutine) OScatterDump);
      CiBindOScatterFunctionBind ("OScatterFillThreeDimensional", (CiRoutine) OScatterFillThreeDimensional);
      CiBindOScatterFunctionBind ("OScatterSetTitle", (CiRoutine) OScatterSetTitle);
      CiBindOScatterFunctionBind ("OScatterGetIthPoint", (CiRoutine) OScatterGetIthPoint);
      CiBindOScatterFunctionBind ("OScatterGetAttribute", (CiRoutine) OScatterGetAttribute);
      CiBindOScatterFunctionBind ("OScatterSetIthAxisUnderflow", (CiRoutine) OScatterSetIthAxisUnderflow);
      CiBindOScatterFunctionBind ("OScatterCreate", (CiRoutine) OScatterCreate);
      CiBindOScatterFunctionBind ("OScatterIsValid", (CiRoutine) OScatterIsValid);
      CiBindOScatterFunctionBind ("OScatterGetName", (CiRoutine) OScatterGetName);
      CiBindOScatterFunctionBind ("OScatterFillTwoDimensional", (CiRoutine) OScatterFillTwoDimensional);
      CiBindOScatterFunctionBind ("OScatterGetDimension", (CiRoutine) OScatterGetDimension);
      CiBindOScatterFunctionBind ("OScatterAllocatePoints", (CiRoutine) OScatterAllocatePoints);
      CiBindOScatterFunctionBind ("OScatterDelete", (CiRoutine) OScatterDelete);
      CiBindOScatterFunctionBind ("OScatterClearClass", (CiRoutine) OScatterClearClass);
      CiBindOScatterFunctionBind ("OScatterGetIthAxisMeanValue", (CiRoutine) OScatterGetIthAxisMeanValue);
      CiBindOScatterFunctionBind ("OScatterGetIdentifier", (CiRoutine) OScatterGetIdentifier);
      CiBindOScatterFunctionBind ("OScatterGetIthAxis", (CiRoutine) OScatterGetIthAxis);
      CiBindOScatterFunctionBind ("OScatterClear", (CiRoutine) OScatterClear);
      CiBindOScatterFunctionBind ("OScatterSetAttribute", (CiRoutine) OScatterSetAttribute);
      CiBindOScatterFunctionBind ("OScatterSetName", (CiRoutine) OScatterSetName);
      CiBindOScatterFunctionBind ("OScatterGetNumberOfEntries", (CiRoutine) OScatterGetNumberOfEntries);
      CiBindOScatterFunctionBind ("OScatterSetDimension", (CiRoutine) OScatterSetDimension);
      CiBindOScatterFunctionBind ("OScatterSetIthAxisAttributesF", (CiRoutine) OScatterSetIthAxisAttributesF);
      CiBindOScatterFunctionBind ("OScatterGetIdentifiers", (CiRoutine) OScatterGetIdentifiers);
      CiBindOScatterFunctionBind ("OScatterMake", (CiRoutine) OScatterMake);
    }
  *switchFunction = (CiRoutine) CiBindOScatterSwitchFunction;
  return ((char*) cases);
}

/*- Procedure ------------------------------------------*/
static void CiBindOScatterSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue)
/*------------------------------------------------------*/
{
  CiPrimValueRec prim;
  
  prim.l = 0;
  
  switch (code)
  {
    case 0 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].i, args[2].p);
          }
          break;
      }
      break;
    case 2 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].i);
          }
          break;
      }
      break;
    case 4 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p);
          }
          break;
      }
      break;
    case 6 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].d);
          }
          break;
      }
      break;
    case 7 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].i, args[2].i);
          }
          break;
        case 2 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p, args[1].i);
          }
          break;
      }
      break;
    case 9 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].i, args[2].p);
          }
          break;
      }
      break;
    case 14 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g ();
          }
          break;
      }
      break;
    case 19 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g ();
          }
          break;
      }
      break;
    case 22 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p);
          }
          break;
        case 2 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].p, args[2].p, args[3].p, 
                        args[4].i);
          }
          break;
      }
      break;
    case 23 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].d, args[2].d);
          }
          break;
      }
      break;
    case 24 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].p, args[2].p, args[3].p, 
                        args[4].p);
          }
          break;
      }
      break;
    case 25 :
      switch (position)
      {
        case 1 :
          {
            CiDRoutine g = (CiDRoutine) f;

            prim.d = g (args[0].p, args[1].i);
          }
          break;
      }
      break;
    case 29 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].i);
          }
          break;
      }
      break;
    case 32 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].d, args[2].d, args[3].d);
          }
          break;
      }
      break;
    case 36 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p);
          }
          break;
      }
      break;
    case 37 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p);
          }
          break;
      }
      break;
  }
  
  args = 0;
  position = 0;
  
  if (retValue) *retValue = prim;
}

/*--------------------------------------------
  This file has been generated by cigen       
  using the following command :               

  $CIBIN/cigen.exe -p -f OStatement.h -n CiBindOStatement -o ../gen/OStatement_B.c

--------------------------------------------*/

#include <OStatement.h>

#ifndef __CI_SWITCH_DEFS__
#define __CI_SWITCH_DEFS__

#ifdef __cplusplus
#define SWITCH_ELLIPSIS ...
#else
#define SWITCH_ELLIPSIS 

#endif

#ifndef __CiDefs__

typedef void            (*CiRoutine)(SWITCH_ELLIPSIS);
typedef char            (*CiCRoutine)(SWITCH_ELLIPSIS);
typedef short           (*CiSRoutine)(SWITCH_ELLIPSIS);
typedef int             (*CiIRoutine)(SWITCH_ELLIPSIS);
typedef long            (*CiLRoutine)(SWITCH_ELLIPSIS);
typedef unsigned char   (*CiUCRoutine)(SWITCH_ELLIPSIS);
typedef unsigned short  (*CiUSRoutine)(SWITCH_ELLIPSIS);
typedef unsigned int    (*CiUIRoutine)(SWITCH_ELLIPSIS);
typedef unsigned long   (*CiULRoutine)(SWITCH_ELLIPSIS);
typedef float           (*CiFRoutine)(SWITCH_ELLIPSIS);
typedef double          (*CiDRoutine)(SWITCH_ELLIPSIS);
typedef void*           (*CiPRoutine)(SWITCH_ELLIPSIS);

#endif

#ifndef __CiType__

typedef union {
  char c;
  short s;
  int i;
  long l;
  char* p;
  float f;
  double d;
} CiPrimValueRec, *CiPrimValue;

#endif

#endif

#ifdef __cplusplus
extern "C" {
#endif

CiRoutine CiBindOStatement (char* library);

static void CiBindOStatementInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew);

static char* CiBindOStatementSetupFunction (CiRoutine* switchFunction);

static void CiBindOStatementSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue);
void CiBindOStatementCleanup ();

static CiRoutine CiBindOStatementFileCompile       = 0;
static CiRoutine CiBindOStatementFunctionBind      = 0;
static CiRoutine CiBindOStatementVariableBind      = 0;
static CiRoutine CiBindOStatementFunctionSwitchNew = 0;

#ifdef __cplusplus
}
#endif

/*- Procedure ------------------------------------------*/
CiRoutine CiBindOStatement (char* library)
/*------------------------------------------------------*/
{
  static int first = 1;

  if (first)
    {
      first = 0;
    }
  else if (CiBindOStatementFunctionSwitchNew)
    {
      CiBindOStatementFunctionSwitchNew ((CiRoutine) CiBindOStatementSetupFunction);
    }

  library = 0;

  return ((CiRoutine) CiBindOStatementInitFunction);
}

/*- Procedure ------------------------------------------*/
static void CiBindOStatementInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew)
/*------------------------------------------------------*/
{
  CiBindOStatementFileCompile       = compileFunction;
  pathFunction = 0;
  CiBindOStatementFunctionBind      = bindFunction;
  CiBindOStatementVariableBind      = bindVariable;
  CiBindOStatementFunctionSwitchNew = switchNew;
  CiBindOStatementVariableBind (0, 0);
  CiBindOStatementFunctionBind (0, 0);
}

/*- Procedure ------------------------------------------*/
static char* CiBindOStatementSetupFunction (CiRoutine* switchFunction)
/*------------------------------------------------------*/
{
  static char cases[] = {
    8, 6, 4, 6, 0,
    6, 6, 4, 6, 0,
    1, 0,
    6, 6, 0,
    1, 1, 0,
    1, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0,
    1, 6, 0,
    0
  };
  static int first = 1;
  
  if (first)
    {
      first = 0;
  
      CiBindOStatementFileCompile ("OStatement.h");
      CiBindOStatementFunctionBind ("OStatementCreate", (CiRoutine) OStatementCreate);
      CiBindOStatementFunctionBind ("OStatementClearClass", (CiRoutine) OStatementClearClass);
      CiBindOStatementFunctionBind ("OStatementGetFunctionIdentifier", (CiRoutine) OStatementGetFunctionIdentifier);
      CiBindOStatementFunctionBind ("OStatementDelete", (CiRoutine) OStatementDelete);
      CiBindOStatementFunctionBind ("OStatementEvaluate", (CiRoutine) OStatementEvaluate);
      CiBindOStatementFunctionBind ("OStatementSetFunctions", (CiRoutine) OStatementSetFunctions);
      CiBindOStatementFunctionBind ("OStatementGetSymbolIdentifier", (CiRoutine) OStatementGetSymbolIdentifier);
    }
  *switchFunction = (CiRoutine) CiBindOStatementSwitchFunction;
  return ((char*) cases);
}

/*- Procedure ------------------------------------------*/
static void CiBindOStatementSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue)
/*------------------------------------------------------*/
{
  CiPrimValueRec prim;
  
  prim.l = 0;
  
  switch (code)
  {
    case 4 :
      switch (position)
      {
        case 1 :
          {
            CiDRoutine g = (CiDRoutine) f;

            prim.d = g (args[0].p, args[1].i, args[2].p);
          }
          break;
      }
      break;
    case 10 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p, args[1].i, args[2].p);
          }
          break;
      }
      break;
    case 14 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g ();
          }
          break;
      }
      break;
    case 22 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p);
          }
          break;
      }
      break;
    case 32 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g ();
          }
          break;
      }
      break;
    case 36 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p, args[2].p, args[3].p, 
               args[4].p, args[5].p, args[6].p, args[7].p, 
               args[8].p, args[9].p, args[10].p, args[11].p, 
               args[12].p, args[13].p, args[14].p, args[15].p, 
               args[16].p, args[17].p, args[18].p, args[19].p, 
               args[20].p, args[21].p, args[22].p, args[23].p, 
               args[24].p, args[25].p);
          }
          break;
      }
      break;
    case 37 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p);
          }
          break;
      }
      break;
  }
  
  args = 0;
  position = 0;
  
  if (retValue) *retValue = prim;
}

/*--------------------------------------------
  This file has been generated by cigen       
  using the following command :               

  $CIBIN/cigen.exe -p -f OTuple.h -n CiBindOTuple -o ../gen/OTuple_B.c

--------------------------------------------*/

#include <OTuple.h>

#ifndef __CI_SWITCH_DEFS__
#define __CI_SWITCH_DEFS__

#ifdef __cplusplus
#define SWITCH_ELLIPSIS ...
#else
#define SWITCH_ELLIPSIS 

#endif

#ifndef __CiDefs__

typedef void            (*CiRoutine)(SWITCH_ELLIPSIS);
typedef char            (*CiCRoutine)(SWITCH_ELLIPSIS);
typedef short           (*CiSRoutine)(SWITCH_ELLIPSIS);
typedef int             (*CiIRoutine)(SWITCH_ELLIPSIS);
typedef long            (*CiLRoutine)(SWITCH_ELLIPSIS);
typedef unsigned char   (*CiUCRoutine)(SWITCH_ELLIPSIS);
typedef unsigned short  (*CiUSRoutine)(SWITCH_ELLIPSIS);
typedef unsigned int    (*CiUIRoutine)(SWITCH_ELLIPSIS);
typedef unsigned long   (*CiULRoutine)(SWITCH_ELLIPSIS);
typedef float           (*CiFRoutine)(SWITCH_ELLIPSIS);
typedef double          (*CiDRoutine)(SWITCH_ELLIPSIS);
typedef void*           (*CiPRoutine)(SWITCH_ELLIPSIS);

#endif

#ifndef __CiType__

typedef union {
  char c;
  short s;
  int i;
  long l;
  char* p;
  float f;
  double d;
} CiPrimValueRec, *CiPrimValue;

#endif

#endif

#ifdef __cplusplus
extern "C" {
#endif

CiRoutine CiBindOTuple (char* library);

static void CiBindOTupleInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew);

static char* CiBindOTupleSetupFunction (CiRoutine* switchFunction);

static void CiBindOTupleSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue);
void CiBindOTupleCleanup ();

static CiRoutine CiBindOTupleFileCompile       = 0;
static CiRoutine CiBindOTupleFunctionBind      = 0;
static CiRoutine CiBindOTupleVariableBind      = 0;
static CiRoutine CiBindOTupleFunctionSwitchNew = 0;

#ifdef __cplusplus
}
#endif

/*- Procedure ------------------------------------------*/
CiRoutine CiBindOTuple (char* library)
/*------------------------------------------------------*/
{
  static int first = 1;

  if (first)
    {
      first = 0;
    }
  else if (CiBindOTupleFunctionSwitchNew)
    {
      CiBindOTupleFunctionSwitchNew ((CiRoutine) CiBindOTupleSetupFunction);
    }

  library = 0;

  return ((CiRoutine) CiBindOTupleInitFunction);
}

/*- Procedure ------------------------------------------*/
static void CiBindOTupleInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew)
/*------------------------------------------------------*/
{
  CiBindOTupleFileCompile       = compileFunction;
  pathFunction = 0;
  CiBindOTupleFunctionBind      = bindFunction;
  CiBindOTupleVariableBind      = bindVariable;
  CiBindOTupleFunctionSwitchNew = switchNew;
  CiBindOTupleVariableBind (0, 0);
  CiBindOTupleFunctionBind (0, 0);
}

/*- Procedure ------------------------------------------*/
static char* CiBindOTupleSetupFunction (CiRoutine* switchFunction)
/*------------------------------------------------------*/
{
  static char cases[] = {
    1, 6, 4, 0,
    8, 6, 4, 4, 0,
    1, 6, 6, 0,
    6, 6, 4, 0,
    1, 6, 4, 6, 6, 0,
    6, 6, 6, 0,
    1, 6, 4, 6, 0,
    1, 0,
    1, 6, 4, 4, 4, 4, 0,
    6, 0,
    4, 6, 6, 6, 4, 6, 6, 6, 0,
    6, 6, 0,
    4, 6, 6, 6, 6, 4, 0,
    4, 6, 6, 6, 6, 6, 0,
    1, 6, 4, 4, 8, 0,
    4, 6, 4, 0,
    4, 6, 6, 0,
    4, 6, 0,
    1, 6, 0,
    6, 6, 4, 4, 6, 4, 6, 0,
    0
  };
  static int first = 1;
  
  if (first)
    {
      first = 0;
  
      CiBindOTupleFileCompile ("OTuple.h");
      CiBindOTupleFunctionBind ("OTupleGetIdentifiers", (CiRoutine) OTupleGetIdentifiers);
      CiBindOTupleFunctionBind ("OTupleGetIdentifier", (CiRoutine) OTupleGetIdentifier);
      CiBindOTupleFunctionBind ("OTupleGetColumnRange", (CiRoutine) OTupleGetColumnRange);
      CiBindOTupleFunctionBind ("OTupleIsEmpty", (CiRoutine) OTupleIsEmpty);
      CiBindOTupleFunctionBind ("OTupleGetColumnIndexFromString", (CiRoutine) OTupleGetColumnIndexFromString);
      CiBindOTupleFunctionBind ("OTupleIsValid", (CiRoutine) OTupleIsValid);
      CiBindOTupleFunctionBind ("OTupleGetName", (CiRoutine) OTupleGetName);
      CiBindOTupleFunctionBind ("OTupleInitialize", (CiRoutine) OTupleInitialize);
      CiBindOTupleFunctionBind ("OTupleGetLabels", (CiRoutine) OTupleGetLabels);
      CiBindOTupleFunctionBind ("OTupleSave", (CiRoutine) OTupleSave);
      CiBindOTupleFunctionBind ("OTupleEndFilling", (CiRoutine) OTupleEndFilling);
      CiBindOTupleFunctionBind ("OTupleMake", (CiRoutine) OTupleMake);
      CiBindOTupleFunctionBind ("OTupleCopy", (CiRoutine) OTupleCopy);
      CiBindOTupleFunctionBind ("OTupleGetIthLabel", (CiRoutine) OTupleGetIthLabel);
      CiBindOTupleFunctionBind ("OTupleGetAttribute", (CiRoutine) OTupleGetAttribute);
      CiBindOTupleFunctionBind ("OTupleDelete", (CiRoutine) OTupleDelete);
      CiBindOTupleFunctionBind ("OTupleGetColumnIndex", (CiRoutine) OTupleGetColumnIndex);
      CiBindOTupleFunctionBind ("OTupleGetFileName", (CiRoutine) OTupleGetFileName);
      CiBindOTupleFunctionBind ("OTupleDoMethod", (CiRoutine) OTupleDoMethod);
      CiBindOTupleFunctionBind ("OTupleFillRowWithFloats", (CiRoutine) OTupleFillRowWithFloats);
      CiBindOTupleFunctionBind ("OTupleClearClass", (CiRoutine) OTupleClearClass);
      CiBindOTupleFunctionBind ("OTupleSetLabels", (CiRoutine) OTupleSetLabels);
      CiBindOTupleFunctionBind ("OTupleSetIthColumnLabel", (CiRoutine) OTupleSetIthColumnLabel);
      CiBindOTupleFunctionBind ("OTupleSetColumns", (CiRoutine) OTupleSetColumns);
      CiBindOTupleFunctionBind ("OTupleGetTitle", (CiRoutine) OTupleGetTitle);
      CiBindOTupleFunctionBind ("OTupleVerifyRowIndex", (CiRoutine) OTupleVerifyRowIndex);
      CiBindOTupleFunctionBind ("OTupleLoadFile", (CiRoutine) OTupleLoadFile);
      CiBindOTupleFunctionBind ("OTupleVerifyColumnIndex", (CiRoutine) OTupleVerifyColumnIndex);
      CiBindOTupleFunctionBind ("OTupleGetValue", (CiRoutine) OTupleGetValue);
      CiBindOTupleFunctionBind ("OTupleSetName", (CiRoutine) OTupleSetName);
      CiBindOTupleFunctionBind ("OTupleClear", (CiRoutine) OTupleClear);
      CiBindOTupleFunctionBind ("OTupleGetNumberOfColumns", (CiRoutine) OTupleGetNumberOfColumns);
      CiBindOTupleFunctionBind ("OTupleDump", (CiRoutine) OTupleDump);
      CiBindOTupleFunctionBind ("OTupleGetValueCareless", (CiRoutine) OTupleGetValueCareless);
      CiBindOTupleFunctionBind ("OTupleGetInformations", (CiRoutine) OTupleGetInformations);
      CiBindOTupleFunctionBind ("OTupleGetRowPointer", (CiRoutine) OTupleGetRowPointer);
      CiBindOTupleFunctionBind ("OTupleGetNumberOfRows", (CiRoutine) OTupleGetNumberOfRows);
      CiBindOTupleFunctionBind ("OTupleSetAttribute", (CiRoutine) OTupleSetAttribute);
      CiBindOTupleFunctionBind ("OTupleSetTitle", (CiRoutine) OTupleSetTitle);
      CiBindOTupleFunctionBind ("OTupleFillRow", (CiRoutine) OTupleFillRow);
      CiBindOTupleFunctionBind ("OTupleAddRows", (CiRoutine) OTupleAddRows);
      CiBindOTupleFunctionBind ("OTupleCreate", (CiRoutine) OTupleCreate);
      CiBindOTupleFunctionBind ("OTupleSetFileName", (CiRoutine) OTupleSetFileName);
      CiBindOTupleFunctionBind ("OTupleFill", (CiRoutine) OTupleFill);
      CiBindOTupleFunctionBind ("OTupleLimitRows", (CiRoutine) OTupleLimitRows);
      CiBindOTupleFunctionBind ("OTupleSetRows", (CiRoutine) OTupleSetRows);
    }
  *switchFunction = (CiRoutine) CiBindOTupleSwitchFunction;
  return ((char*) cases);
}

/*- Procedure ------------------------------------------*/
static void CiBindOTupleSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue)
/*------------------------------------------------------*/
{
  CiPrimValueRec prim;
  
  prim.l = 0;
  
  switch (code)
  {
    case 2 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].i);
          }
          break;
        case 2 :
          {
            CiDRoutine g = (CiDRoutine) f;

            prim.d = g (args[0].p, args[1].i, args[2].i);
          }
          break;
      }
      break;
    case 4 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p);
          }
          break;
      }
      break;
    case 7 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p, args[1].i);
          }
          break;
      }
      break;
    case 8 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].i, args[2].p, args[3].p);
          }
          break;
      }
      break;
    case 9 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p, args[1].p);
          }
          break;
        case 2 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].i, args[2].p);
          }
          break;
      }
      break;
    case 14 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g ();
          }
          break;
      }
      break;
    case 17 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].i, args[2].i, args[3].i, 
               args[4].i);
          }
          break;
      }
      break;
    case 19 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g ();
          }
          break;
      }
      break;
    case 20 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].p, args[2].p, args[3].i, 
                        args[4].p, args[5].p, args[6].p);
          }
          break;
      }
      break;
    case 22 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p);
          }
          break;
        case 2 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].p, args[2].p, args[3].p, 
                        args[4].i);
          }
          break;
      }
      break;
    case 24 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].p, args[2].p, args[3].p, 
                        args[4].p);
          }
          break;
        case 2 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].i, args[2].i, args[3].d);
          }
          break;
      }
      break;
    case 29 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].i);
          }
          break;
      }
      break;
    case 31 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].p);
          }
          break;
      }
      break;
    case 36 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p);
          }
          break;
      }
      break;
    case 37 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p);
          }
          break;
      }
      break;
    case 39 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p, args[1].i, args[2].i, args[3].p, 
                                args[4].i, args[5].p);
          }
          break;
      }
      break;
  }
  
  args = 0;
  position = 0;
  
  if (retValue) *retValue = prim;
}

