bin            = ../${CONFIG}
mgr            = ../mgr
src            = ../src
app            = ../app
make_so        = sh ${COROOT}/mgr/maklibs.sh
Wo_CPPFLAGS    = -I${COROOT}/include -I${XXROOT}/include -I../include
libCo          = -L${COROOT}/${CONFIG} -lCo
libXx          = -L${XXROOT}/${CONFIG} -lXx
libWo          = -L../${CONFIG} -lWo
WoXm_CPPFLAGS  = -DHAS_XM
libWoXm        = -L../${CONFIG} -lWoXm
WoXaw_CPPFLAGS = -DHAS_XAW
libWoXaw       = -L../${CONFIG} -lWoXaw
WoGL_CPPFLAGS  = -I${GLOROOT}/usr/include
libWoGL        = -L../${CONFIG} -lWoGL
libGL          = -L${GLOROOT}/${CONFIG} -lGLo
libGLU         = -L${GLOROOT}/${CONFIG} -lGLUo
libGLX         = -L${GLOROOT}/${CONFIG} -lGLXo
#libGL          = -L${HOME}/${CONFIG}/lib -lGL
#libGLU         = -L${HOME}/${CONFIG}/lib -lGLU
#libGLX         = -L${HOME}/${CONFIG}/lib -lGLX
WoXo_CPPFLAGS  = -DHAS_XO -I${XOROOT}/include -I${GOROOT}/include -I${HOROOT}/include
libXo          = -L${XOROOT}/${CONFIG}  -lXo
libHo          = -L${HOROOT}/${CONFIG} -lHo
libGo          = -L${GOROOT}/${CONFIG}  -lGo
WoHTML_CPPFLAGS = -DHAS_HTML
libwww          = -L${W3OROOT}/${CONFIG} -lW3o
libhtmlw        = -L${HTMLOROOT}/${CONFIG} -lHTMLo
WoXz_CPPFLAGS  = -DHAS_XZ -DHAS_HO -I${XZROOT}/include -I${HOROOT}/include
libWoHoXz      = -L../${CONFIG} -lWoHoXz
libXz          = -L${XZROOT}/${CONFIG} -lXz
libXzPAWC      = -L${XZROOT}/${CONFIG} -lXzPAWC
libgraflib     = -L${CERNLIB} -lgraflib
libgrafX11     = -L${CERNLIB} -lgrafX11
libpacklib     = -L${CERNLIB} -lpacklib
libmathlib     = -L${CERNLIB} -lmathlib
WoPAW_CPPFLAGS  = -DHAS_PAW
libWoPAW        = -L../${CONFIG} -lWoPAW
libpawlib       = -L${CERNLIB} -lpawlib
WoG3o_CPPFLAGS  = -DHAS_G3O -I${G3OROOT}/include
libG3o          = -L${G3OROOT}/${CONFIG} -lG3o
libG3oEXPO      = -L${G3OROOT}/${CONFIG} -lG3oEXPO
libgeant        = -L${CERNLIB} -lgeant321
WoCi_CPPFLAGS   = -DHAS_CI -I${CIROOT}/src -I${CSETROOT}/src
libWoCi         = -L../${CONFIG} -lWoCi
libCi           = -L${CIROOT}/${METHODSCONFIG}  -lCiSwitches -lCi
libCSet         = -L${CSETROOT}/${METHODSCONFIG}  -lCSet -lReg
WoFNAL_CPPFLAGS = -DHAS_FNAL -I${HOME}/${CONFIG}/include/FNAL
libWoFNAL       = -L../${CONFIG} -lWoFNAL
libFNAL         = -L${HOME}/${CONFIG}/lib -lPlotW -lNUtil
Wotcl_CPPFLAGS  = -DHAS_TCL -I/usr/local/include
libtcl          = -L/usr/local/lib -ltcl
WoJAVA_CPPFLAGS = -DHAS_JAVA
WoInventor_CPPFLAGS = -DHAS_INVENTOR -I${OIHOME}/include
libInventorXt       = -L${OIHOME}/lib -lInventorXt 
libInventor         = -L${OIHOME}/lib -lInventor


