#/* +---------------------- Copyright notice -------------------------------+ */
#/* | Copyright (C) 1995, Guy Barrand, LAL Orsay. (barrand@lalcls.in2p3.fr) | */
#/* |   Permission to use, copy, modify, and distribute this software       | */
#/* |   and its documentation for any purpose and without fee is hereby     | */
#/* |   granted, provided that the above copyright notice appear in all     | */
#/* |   copies and that both that copyright notice and this permission      | */
#/* |   notice appear in supporting documentation.  This software is        | */
#/* |   provided "as is" without express or implied warranty.               | */
#/* +---------------------- Copyright notice -------------------------------+ */
#
# Macros for this package are in macros.mk.
#

include ${COROOT}/mgr/Config.mk

This_needed :
	@if test "${COROOT}"    = "" ; then echo "COROOT not set"    ; exit 1 ; else exit 0 ; fi
	@if test "${XXROOT}"    = "" ; then echo "XXROOT not set"    ; exit 1 ; else exit 0 ; fi
	@
	@if test "${HOROOT}"    = "" ; then echo "HOROOT not set"    ; else exit 0 ; fi
	@if test "${GLOROOT}"   = "" ; then echo "GLOROOT not set"   ; else exit 0 ; fi
	@if test "${GOROOT}"    = "" ; then echo "GOROOT not set"    ; else exit 0 ; fi
	@if test "${W3OROOT}"   = "" ; then echo "W3OROOT not set"   ; else exit 0 ; fi
	@if test "${HTMLOROOT}" = "" ; then echo "HTMLOROOT not set" ; else exit 0 ; fi
	@if test "${XOROOT}"    = "" ; then echo "XOROOT not set"    ; else exit 0 ; fi
	@if test "${CIROOT}"    = "" ; then echo "CIROOT not set"    ; else exit 0 ; fi
	@if test "${CSETROOT}"  = "" ; then echo "CSETROOT not set"  ; else exit 0 ; fi
	@if test "${CERNLIB}"   = "" ; then echo "CERNLIB not set"   ; else exit 0 ; fi



