/*--------------------------------------------
  This file has been generated by cigen       
  using the following command :               

  $CIBIN/cigen.exe -p -f G3oTypes.h -n CiBindG3oTypes -o ../gen/G3oTypes_B.c

--------------------------------------------*/

#include <G3oTypes.h>

#ifndef __CI_SWITCH_DEFS__
#define __CI_SWITCH_DEFS__

#ifdef __cplusplus
#define SWITCH_ELLIPSIS ...
#else
#define SWITCH_ELLIPSIS 

#endif

#ifndef __CiDefs__

typedef void            (*CiRoutine)(SWITCH_ELLIPSIS);
typedef char            (*CiCRoutine)(SWITCH_ELLIPSIS);
typedef short           (*CiSRoutine)(SWITCH_ELLIPSIS);
typedef int             (*CiIRoutine)(SWITCH_ELLIPSIS);
typedef long            (*CiLRoutine)(SWITCH_ELLIPSIS);
typedef unsigned char   (*CiUCRoutine)(SWITCH_ELLIPSIS);
typedef unsigned short  (*CiUSRoutine)(SWITCH_ELLIPSIS);
typedef unsigned int    (*CiUIRoutine)(SWITCH_ELLIPSIS);
typedef unsigned long   (*CiULRoutine)(SWITCH_ELLIPSIS);
typedef float           (*CiFRoutine)(SWITCH_ELLIPSIS);
typedef double          (*CiDRoutine)(SWITCH_ELLIPSIS);
typedef void*           (*CiPRoutine)(SWITCH_ELLIPSIS);

#endif

#ifndef __CiType__

typedef union {
  char c;
  short s;
  int i;
  long l;
  char* p;
  float f;
  double d;
} CiPrimValueRec, *CiPrimValue;

#endif

#endif

#ifdef __cplusplus
extern "C" {
#endif

CiRoutine CiBindG3oTypes (char* library);

static void CiBindG3oTypesInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew);

static char* CiBindG3oTypesSetupFunction (CiRoutine* switchFunction);

static void CiBindG3oTypesSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue);
void CiBindG3oTypesCleanup ();

static CiRoutine CiBindG3oTypesFileCompile       = 0;
static CiRoutine CiBindG3oTypesFunctionBind      = 0;
static CiRoutine CiBindG3oTypesVariableBind      = 0;
static CiRoutine CiBindG3oTypesFunctionSwitchNew = 0;

#ifdef __cplusplus
}
#endif

/*- Procedure ------------------------------------------*/
CiRoutine CiBindG3oTypes (char* library)
/*------------------------------------------------------*/
{
  static int first = 1;

  if (first)
    {
      first = 0;
    }
  else if (CiBindG3oTypesFunctionSwitchNew)
    {
      CiBindG3oTypesFunctionSwitchNew ((CiRoutine) CiBindG3oTypesSetupFunction);
    }

  library = 0;

  return ((CiRoutine) CiBindG3oTypesInitFunction);
}

/*- Procedure ------------------------------------------*/
static void CiBindG3oTypesInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew)
/*------------------------------------------------------*/
{
  CiBindG3oTypesFileCompile       = compileFunction;
  pathFunction = 0;
  CiBindG3oTypesFunctionBind      = bindFunction;
  CiBindG3oTypesVariableBind      = bindVariable;
  CiBindG3oTypesFunctionSwitchNew = switchNew;
  CiBindG3oTypesVariableBind (0, 0);
  CiBindG3oTypesFunctionBind (0, 0);
}

/*- Procedure ------------------------------------------*/
static char* CiBindG3oTypesSetupFunction (CiRoutine* switchFunction)
/*------------------------------------------------------*/
{
  static char cases[] = {
    1, 0,
    0
  };
  static int first = 1;
  
  if (first)
    {
      first = 0;
  
      CiBindG3oTypesFileCompile ("G3oTypes.h");
      CiBindG3oTypesFunctionBind ("G3oDeclareUDETsHitsAndDIGIs", (CiRoutine) G3oDeclareUDETsHitsAndDIGIs);
      CiBindG3oTypesFunctionBind ("G3oSetTypes", (CiRoutine) G3oSetTypes);
    }
  *switchFunction = (CiRoutine) CiBindG3oTypesSwitchFunction;
  return ((char*) cases);
}

/*- Procedure ------------------------------------------*/
static void CiBindG3oTypesSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue)
/*------------------------------------------------------*/
{
  CiPrimValueRec prim;
  
  prim.l = 0;
  
  switch (code)
  {
    case 14 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g ();
          }
          break;
      }
      break;
  }
  
  args = 0;
  position = 0;
  
  if (retValue) *retValue = prim;
}

/*--------------------------------------------
  This file has been generated by cigen       
  using the following command :               

  $CIBIN/cigen.exe -p -f GEANT.h -n CiBindGEANT -o ../gen/GEANT_B.c

--------------------------------------------*/

#include <GEANT.h>

#ifndef __CI_SWITCH_DEFS__
#define __CI_SWITCH_DEFS__

#ifdef __cplusplus
#define SWITCH_ELLIPSIS ...
#else
#define SWITCH_ELLIPSIS 

#endif

#ifndef __CiDefs__

typedef void            (*CiRoutine)(SWITCH_ELLIPSIS);
typedef char            (*CiCRoutine)(SWITCH_ELLIPSIS);
typedef short           (*CiSRoutine)(SWITCH_ELLIPSIS);
typedef int             (*CiIRoutine)(SWITCH_ELLIPSIS);
typedef long            (*CiLRoutine)(SWITCH_ELLIPSIS);
typedef unsigned char   (*CiUCRoutine)(SWITCH_ELLIPSIS);
typedef unsigned short  (*CiUSRoutine)(SWITCH_ELLIPSIS);
typedef unsigned int    (*CiUIRoutine)(SWITCH_ELLIPSIS);
typedef unsigned long   (*CiULRoutine)(SWITCH_ELLIPSIS);
typedef float           (*CiFRoutine)(SWITCH_ELLIPSIS);
typedef double          (*CiDRoutine)(SWITCH_ELLIPSIS);
typedef void*           (*CiPRoutine)(SWITCH_ELLIPSIS);

#endif

#ifndef __CiType__

typedef union {
  char c;
  short s;
  int i;
  long l;
  char* p;
  float f;
  double d;
} CiPrimValueRec, *CiPrimValue;

#endif

#endif

#ifdef __cplusplus
extern "C" {
#endif

CiRoutine CiBindGEANT (char* library);

static void CiBindGEANTInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew);

static char* CiBindGEANTSetupFunction (CiRoutine* switchFunction);

static void CiBindGEANTSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue);
void CiBindGEANTCleanup ();

static CiRoutine CiBindGEANTFileCompile       = 0;
static CiRoutine CiBindGEANTFunctionBind      = 0;
static CiRoutine CiBindGEANTVariableBind      = 0;
static CiRoutine CiBindGEANTFunctionSwitchNew = 0;

#ifdef __cplusplus
}
#endif

/*- Procedure ------------------------------------------*/
CiRoutine CiBindGEANT (char* library)
/*------------------------------------------------------*/
{
  static int first = 1;

  if (first)
    {
      first = 0;
    }
  else if (CiBindGEANTFunctionSwitchNew)
    {
      CiBindGEANTFunctionSwitchNew ((CiRoutine) CiBindGEANTSetupFunction);
    }

  library = 0;

  return ((CiRoutine) CiBindGEANTInitFunction);
}

/*- Procedure ------------------------------------------*/
static void CiBindGEANTInitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew)
/*------------------------------------------------------*/
{
  CiBindGEANTFileCompile       = compileFunction;
  pathFunction = 0;
  CiBindGEANTFunctionBind      = bindFunction;
  CiBindGEANTVariableBind      = bindVariable;
  CiBindGEANTFunctionSwitchNew = switchNew;
  CiBindGEANTVariableBind (0, 0);
  CiBindGEANTFunctionBind (0, 0);
}

/*- Procedure ------------------------------------------*/
static char* CiBindGEANTSetupFunction (CiRoutine* switchFunction)
/*------------------------------------------------------*/
{
  static char cases[] = {
    6, 6, 4, 0,
    6, 6, 6, 0,
    1, 0,
    1, 4, 6, 4, 0,
    4, 0,
    6, 0,
    4, 6, 6, 4, 6, 6, 6, 6, 0,
    6, 6, 0,
    1, 6, 6, 6, 6, 0,
    4, 6, 6, 0,
    1, 6, 6, 4, 0,
    4, 6, 4, 6, 6, 0,
    1, 4, 0,
    4, 6, 0,
    1, 6, 0,
    0
  };
  static int first = 1;
  
  if (first)
    {
      first = 0;
  
      CiBindGEANTFileCompile ("GEANT.h");
      CiBindGEANTFunctionBind ("GEANT_RepresentVolume", (CiRoutine) GEANT_RepresentVolume);
      CiBindGEANTFunctionBind ("GEANT_GetVolumeDrawingAttribute", (CiRoutine) GEANT_GetVolumeDrawingAttribute);
      CiBindGEANTFunctionBind ("GEANT_ProduceEvent", (CiRoutine) GEANT_ProduceEvent);
      CiBindGEANTFunctionBind ("GEANT_GetTopVolume", (CiRoutine) GEANT_GetTopVolume);
      CiBindGEANTFunctionBind ("GEANT_ClearEvent", (CiRoutine) GEANT_ClearEvent);
      CiBindGEANTFunctionBind ("GEANT_GetDetectorIthDIGI", (CiRoutine) GEANT_GetDetectorIthDIGI);
      CiBindGEANTFunctionBind ("GEANT_Initialize", (CiRoutine) GEANT_Initialize);
      CiBindGEANTFunctionBind ("GEANT_GetDetectorNumberOfDIGIs", (CiRoutine) GEANT_GetDetectorNumberOfDIGIs);
      CiBindGEANTFunctionBind ("GEANT_GetDetectorIthHit", (CiRoutine) GEANT_GetDetectorIthHit);
      CiBindGEANTFunctionBind ("GEANT_PrintVolumes", (CiRoutine) GEANT_PrintVolumes);
      CiBindGEANTFunctionBind ("GEANT_SetVolumeDrawingAttribute", (CiRoutine) GEANT_SetVolumeDrawingAttribute);
      CiBindGEANTFunctionBind ("GEANT_GetVolumeNumberOfSons", (CiRoutine) GEANT_GetVolumeNumberOfSons);
      CiBindGEANTFunctionBind ("GEANT_GetVolumeUpperVolumes", (CiRoutine) GEANT_GetVolumeUpperVolumes);
      CiBindGEANTFunctionBind ("GEANT_LoadGeometry", (CiRoutine) GEANT_LoadGeometry);
      CiBindGEANTFunctionBind ("GEANT_RepresentVertex", (CiRoutine) GEANT_RepresentVertex);
      CiBindGEANTFunctionBind ("GEANT_RepresentTrack", (CiRoutine) GEANT_RepresentTrack);
      CiBindGEANTFunctionBind ("GEANT_GetVolumeIthSon", (CiRoutine) GEANT_GetVolumeIthSon);
      CiBindGEANTFunctionBind ("GEANT_GetVolumeNames", (CiRoutine) GEANT_GetVolumeNames);
      CiBindGEANTFunctionBind ("GEANT_GetDetectorNumberOfHits", (CiRoutine) GEANT_GetDetectorNumberOfHits);
      CiBindGEANTFunctionBind ("GEANT_SetVolumeVisibility", (CiRoutine) GEANT_SetVolumeVisibility);
      CiBindGEANTFunctionBind ("GEANT_GetDetectorVolumes", (CiRoutine) GEANT_GetDetectorVolumes);
      CiBindGEANTFunctionBind ("GEANT_SaveGeometry", (CiRoutine) GEANT_SaveGeometry);
    }
  *switchFunction = (CiRoutine) CiBindGEANTSwitchFunction;
  return ((char*) cases);
}

/*- Procedure ------------------------------------------*/
static void CiBindGEANTSwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue)
/*------------------------------------------------------*/
{
  CiPrimValueRec prim;
  
  prim.l = 0;
  
  switch (code)
  {
    case 7 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p, args[1].i);
          }
          break;
      }
      break;
    case 9 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p, args[1].p);
          }
          break;
      }
      break;
    case 14 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g ();
          }
          break;
      }
      break;
    case 15 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].i, args[1].p, args[2].i);
          }
          break;
      }
      break;
    case 17 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g ();
          }
          break;
      }
      break;
    case 19 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g ();
          }
          break;
      }
      break;
    case 20 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].p, args[2].i, args[3].p, 
                        args[4].p, args[5].p, args[6].p);
          }
          break;
      }
      break;
    case 22 :
      switch (position)
      {
        case 1 :
          {
            CiPRoutine g = (CiPRoutine) f;

            prim.p = (char*) g (args[0].p);
          }
          break;
      }
      break;
    case 26 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p, args[2].p, args[3].p);
          }
          break;
      }
      break;
    case 31 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].p);
          }
          break;
      }
      break;
    case 33 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p, args[2].i);
          }
          break;
      }
      break;
    case 35 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].i, args[2].p, args[3].p);
          }
          break;
        case 2 :
          {
            CiRoutine g = f;

            g (args[0].i);
          }
          break;
      }
      break;
    case 36 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p);
          }
          break;
      }
      break;
    case 37 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p);
          }
          break;
      }
      break;
  }
  
  args = 0;
  position = 0;
  
  if (retValue) *retValue = prim;
}

/*--------------------------------------------
  This file has been generated by cigen       
  using the following command :               

  $CIBIN/cigen.exe -p -f GF77.h -n CiBindGF77 -o ../gen/GF77_B.c

--------------------------------------------*/

#include <GF77.h>

#ifndef __CI_SWITCH_DEFS__
#define __CI_SWITCH_DEFS__

#ifdef __cplusplus
#define SWITCH_ELLIPSIS ...
#else
#define SWITCH_ELLIPSIS 

#endif

#ifndef __CiDefs__

typedef void            (*CiRoutine)(SWITCH_ELLIPSIS);
typedef char            (*CiCRoutine)(SWITCH_ELLIPSIS);
typedef short           (*CiSRoutine)(SWITCH_ELLIPSIS);
typedef int             (*CiIRoutine)(SWITCH_ELLIPSIS);
typedef long            (*CiLRoutine)(SWITCH_ELLIPSIS);
typedef unsigned char   (*CiUCRoutine)(SWITCH_ELLIPSIS);
typedef unsigned short  (*CiUSRoutine)(SWITCH_ELLIPSIS);
typedef unsigned int    (*CiUIRoutine)(SWITCH_ELLIPSIS);
typedef unsigned long   (*CiULRoutine)(SWITCH_ELLIPSIS);
typedef float           (*CiFRoutine)(SWITCH_ELLIPSIS);
typedef double          (*CiDRoutine)(SWITCH_ELLIPSIS);
typedef void*           (*CiPRoutine)(SWITCH_ELLIPSIS);

#endif

#ifndef __CiType__

typedef union {
  char c;
  short s;
  int i;
  long l;
  char* p;
  float f;
  double d;
} CiPrimValueRec, *CiPrimValue;

#endif

#endif

#ifdef __cplusplus
extern "C" {
#endif

CiRoutine CiBindGF77 (char* library);

static void CiBindGF77InitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew);

static char* CiBindGF77SetupFunction (CiRoutine* switchFunction);

static void CiBindGF77SwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue);
void CiBindGF77Cleanup ();

static CiRoutine CiBindGF77FileCompile       = 0;
static CiRoutine CiBindGF77FunctionBind      = 0;
static CiRoutine CiBindGF77VariableBind      = 0;
static CiRoutine CiBindGF77FunctionSwitchNew = 0;

#ifdef __cplusplus
}
#endif

/*- Procedure ------------------------------------------*/
CiRoutine CiBindGF77 (char* library)
/*------------------------------------------------------*/
{
  static int first = 1;

  if (first)
    {
      first = 0;
    }
  else if (CiBindGF77FunctionSwitchNew)
    {
      CiBindGF77FunctionSwitchNew ((CiRoutine) CiBindGF77SetupFunction);
    }

  library = 0;

  return ((CiRoutine) CiBindGF77InitFunction);
}

/*- Procedure ------------------------------------------*/
static void CiBindGF77InitFunction (CiRoutine compileFunction,
                            CiRoutine pathFunction,
                            CiRoutine bindFunction,
                            CiRoutine bindVariable,
                            CiRoutine switchNew)
/*------------------------------------------------------*/
{
  CiBindGF77FileCompile       = compileFunction;
  pathFunction = 0;
  CiBindGF77FunctionBind      = bindFunction;
  CiBindGF77VariableBind      = bindVariable;
  CiBindGF77FunctionSwitchNew = switchNew;
  CiBindGF77VariableBind (0, 0);
  CiBindGF77FunctionBind (0, 0);
}

/*- Procedure ------------------------------------------*/
static char* CiBindGF77SetupFunction (CiRoutine* switchFunction)
/*------------------------------------------------------*/
{
  static char cases[] = {
    4, 6, 6, 6, 6, 6, 6, 6, 6, 0,
    1, 6, 6, 0,
    1, 6, 6, 6, 6, 6, 6, 0,
    4, 6, 6, 6, 6, 0,
    1, 0,
    4, 0,
    1, 6, 6, 6, 6, 6, 0,
    1, 6, 6, 6, 6, 0,
    4, 6, 6, 6, 6, 6, 6, 6, 0,
    1, 6, 6, 6, 0,
    4, 6, 0,
    1, 6, 0,
    0
  };
  static int first = 1;
  
  if (first)
    {
      first = 0;
  
      CiBindGF77FileCompile ("GF77.h");
      CiBindGF77FunctionBind ("gfmoth", (CiRoutine) gfmoth);
      CiBindGF77FunctionBind ("gpdigi", (CiRoutine) gpdigi);
      CiBindGF77FunctionBind ("ogkind", (CiRoutine) ogkind);
      CiBindGF77FunctionBind ("oginit", (CiRoutine) oginit);
      CiBindGF77FunctionBind ("oghitv", (CiRoutine) oghitv);
      CiBindGF77FunctionBind ("ogkinn", (CiRoutine) ogkinn);
      CiBindGF77FunctionBind ("gpvolu", (CiRoutine) gpvolu);
      CiBindGF77FunctionBind ("ogvonm", (CiRoutine) ogvonm);
      CiBindGF77FunctionBind ("ogkinv", (CiRoutine) ogkinv);
      CiBindGF77FunctionBind ("gdson", (CiRoutine) gdson);
      CiBindGF77FunctionBind ("gfatt", (CiRoutine) gfatt);
      CiBindGF77FunctionBind ("gtrigc", (CiRoutine) gtrigc);
      CiBindGF77FunctionBind ("ogevbg", (CiRoutine) ogevbg);
      CiBindGF77FunctionBind ("ogrgeo", (CiRoutine) ogrgeo);
      CiBindGF77FunctionBind ("gfndig", (CiRoutine) gfndig);
      CiBindGF77FunctionBind ("uhtoc", (CiRoutine) uhtoc);
      CiBindGF77FunctionBind ("ogdetn", (CiRoutine) ogdetn);
      CiBindGF77FunctionBind ("ogdeto", (CiRoutine) ogdeto);
      CiBindGF77FunctionBind ("ogdetv", (CiRoutine) ogdetv);
      CiBindGF77FunctionBind ("grun", (CiRoutine) grun);
      CiBindGF77FunctionBind ("gfnhit", (CiRoutine) gfnhit);
      CiBindGF77FunctionBind ("gphits", (CiRoutine) gphits);
      CiBindGF77FunctionBind ("ogwgeo", (CiRoutine) ogwgeo);
      CiBindGF77FunctionBind ("gsatt", (CiRoutine) gsatt);
      CiBindGF77FunctionBind ("ogmoth", (CiRoutine) ogmoth);
      CiBindGF77FunctionBind ("ogverd", (CiRoutine) ogverd);
      CiBindGF77FunctionBind ("ogdigv", (CiRoutine) ogdigv);
      CiBindGF77FunctionBind ("ogvern", (CiRoutine) ogvern);
      CiBindGF77FunctionBind ("ogvold", (CiRoutine) ogvold);
      CiBindGF77FunctionBind ("ogverv", (CiRoutine) ogverv);
      CiBindGF77FunctionBind ("ogvoln", (CiRoutine) ogvoln);
      CiBindGF77FunctionBind ("ogvolt", (CiRoutine) ogvolt);
      CiBindGF77FunctionBind ("ogvolv", (CiRoutine) ogvolv);
      CiBindGF77FunctionBind ("gdnson", (CiRoutine) gdnson);
    }
  *switchFunction = (CiRoutine) CiBindGF77SwitchFunction;
  return ((char*) cases);
}

/*- Procedure ------------------------------------------*/
static void CiBindGF77SwitchFunction (CiRoutine f,
                              int code,
                              int position,
                              CiPrimValue args,
                              CiPrimValue retValue)
/*------------------------------------------------------*/
{
  CiPrimValueRec prim;
  
  prim.l = 0;
  
  switch (code)
  {
    case 1 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].p, args[2].p, args[3].p, 
                        args[4].p, args[5].p, args[6].p, args[7].p);
          }
          break;
      }
      break;
    case 4 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p);
          }
          break;
      }
      break;
    case 8 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p, args[2].p, args[3].p, 
               args[4].p, args[5].p);
          }
          break;
      }
      break;
    case 13 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].p, args[2].p, args[3].p);
          }
          break;
      }
      break;
    case 14 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g ();
          }
          break;
      }
      break;
    case 17 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g ();
          }
          break;
        case 2 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p, args[2].p, args[3].p, 
               args[4].p);
          }
          break;
      }
      break;
    case 26 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p, args[2].p, args[3].p);
          }
          break;
      }
      break;
    case 30 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p, args[1].p, args[2].p, args[3].p, 
                        args[4].p, args[5].p, args[6].p);
          }
          break;
      }
      break;
    case 35 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p, args[1].p, args[2].p);
          }
          break;
      }
      break;
    case 36 :
      switch (position)
      {
        case 1 :
          {
            CiIRoutine g = (CiIRoutine) f;

            prim.i = g (args[0].p);
          }
          break;
      }
      break;
    case 37 :
      switch (position)
      {
        case 1 :
          {
            CiRoutine g = f;

            g (args[0].p);
          }
          break;
      }
      break;
  }
  
  args = 0;
  position = 0;
  
  if (retValue) *retValue = prim;
}

